### ISSUE TITLE
Any documentation?

### ISSUE THREAD

**Issue by jsiegenthaler** [MiguelRipoll23/homebridge-securitysystem#102]
I'd like to set this up properly but cannot find any documentation on how to use this plugin....

**Comment by MiguelRipoll23** [comment]
Hey there,

By the default, the easiest configuration is set. That means that if you arm the security system to any armed mode and create an automation that turns on its siren switch it will trigger the security system.

Please check the README for more details and the plugin settings to see what else it's possible (every option contains a description of what it dies).

If you got any questions be free to ask them here.

**Comment by jsiegenthaler** [comment]
Thanks
The Readme has extremely little in it. Nothing at all about the many options.
I deleted my config to start again
Questions:
What do Siren Away, Siren Home, Siren Night switches do?  Why three switches? Why not just one switch Siren On/Off?
I have a front door contact sensor. How do I use that to trigger the alarm?
I have many motion sensors. How do I use them to trigger the alarm?
How do I get the alarm to be set automatically when the last person leaves home?
How do I get the alarm to be turned off when the first person arrives home?

**Comment by MiguelRipoll23** [comment]
Sorry for the lack of details, by the way are you using Homebridge UI?
It's easier to see the plugin settings there.

> What do Siren Away, Siren Home, Siren Night switches do?
They trigger the security system if their mode is selected, otherwise they will fail.

> Why not just one switch Siren On/Off?
You can enable/disable the `Show Siren Mode Switches` option under the switches section from the plugin settings and enable the global siren switch with option `Show Siren Switch`. You will need to add a condition for the automation using a advanced HomeKit app like Eve to check the current mode.

> I have a front door contact sensor. How do I use that to trigger the alarm?
Create an automation that turns on the `Siren` or `Siren (mode required her)` switch.

> I have many motion sensors. How do I use them to trigger the alarm?
Same answer as the previous question :)

> How do I get the alarm to be set automatically when the last person leaves home?
Enable the `Show mode switches` option and create an automation turns on the `Mode away` switch when last person leaves the house (this will bypass the HomeKit confirmation from Apple).

> How do I get the alarm to be turned off when the first person arrives home?
Enable the `Show mode switches` option and create an automation turns on the `Mode off` switch when the first person arrives home (this will bypass the HomeKit confirmation from Apple).

**Comment by jsiegenthaler** [comment]
OK. 
Yes, I use Homebridge on a Raspberry Pi with the homebridge-config-ui-x v4.41.0 plugin installed.

What is really confusing is that the alarm trigger is named "Siren". 
Alarms get triggered, and then switch on various items: Sirens, Horns, Lamps, Remote Notification systems, etc.

From the wording on the switch, it appeared that the Siren switch was simply a way to enable or disable the siren, leaving the rest of the alarm system intact.

This is why documentation is so important. You know your product inside out, but I, as a user, struggle to understand it. And without documentation, I have struggled to understand this plugin for a year now... :(

Thanks for clarifying. I will now rename the switches to prevent confusion... ;)

**Comment by MiguelRipoll23** [comment]
Oh, I see!

I named the switch some long time ago, I think `Trigger`, `Trigger Home`, `Trigger Night` and `Trigger Away` would have been a better name (it will get renamed soon, thanks for the suggestion).

Back in the early days, [there was some documentation](https://github.com/MiguelRipoll23/homebridge-securitysystem/tree/1e682368513b756f99380124f397f004d6912a23) about all the options but there were so many that it probably scared new users from using this plugin.

The default options from the plugin were set to an easier configuration for beginners and then all the documentation that the README page had was moved to the plugin settings and organized by sections. A brief description was added behind each option but as shown, it's not very intuitive yet.

I'll do my best to improve it for new users, really appreciate the feedback. I'll move some of the questions you asked alongside my answers to the Wiki if you don't my mind.

Thanks!

**Comment by jsiegenthaler** [comment]
Actually the Mode switches are fine. It's the Siren that should be named Alarm Trigger. And that should be a momentary switch, automatically returning to Off state after 1 or 2 seconds.

**Comment by MiguelRipoll23** [comment]
Yeah, I was talking about the `Siren Mode` switches actually, the three of them plus the global one.

I generally avoid momentary switches as I think it adds way too much noise into the Home app, it's also a great visual indicator that the security system will trigger. Some breaking changes have happened during the life of this plugin though, nothing is written in stone :)
