### ISSUE TITLE
HOOBS crashes when alarm state changes

### ISSUE THREAD

**Issue by dmctavish** [MiguelRipoll23/homebridge-securitysystem#103]
**Describe the bug**
When I change the alarm state from off to nightly (or vice versa) hoobs will crash as follows:

2021-04-11, 7:20:57 AM [Security system] Target mode (Off)
2021-04-11, 7:20:57 AM [Security system] Current mode (Off)
2021-04-11, 7:20:57 AM Error: spawn ffplay ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
2021-04-11, 7:20:57 AM Got SIGTERM, shutting down Bridge...

**To Reproduce**
1. Go Home on ipad
2. Click on Security system
3. Toggle status to anything else

**Expected behavior**
should be able to change the status

**Plugin's configuration**
Configuration set is quite helpful, remove sensitive details though.

    "accessories": [
        {
            "accessory": "security-system",
            "plugin_map": {
                "plugin_name": "homebridge-securitysystem",
                "index": 0
            },
            "name": "Security system",
            "default_mode": "Off",
            "arm_seconds": 60,
            "trigger_seconds": 120,
            "reset_minutes": 10,
            "audio": true,
            "audio_language": "en-US",
            "save_state": true,
            "proxy_mode": false,
            "test_mode": false,
            "override_off": false,
            "night_arming_delay": false,
            "reset_off_flow": false,
            "siren_sensor": true,
            "siren_sensor_seconds": 5,
            "reset_sensor": false,
            "mode_switches": false,
            "mode_off_switch": true,
            "mode_away_extended_switch": false,
            "mode_pause_switch": false,
            "pause_minutes": 0,
            "siren_switch": true,
            "siren_mode_switches": false,
            "double_knock": false,
            "double_knock_seconds": 90,
            "audio_volume": 100,
            "audio_arming_looped": false,
            "audio_alert_looped": false
        }
    ],

**Additional context**

**Comment by MiguelRipoll23** [comment]
Hey there, 

That means ffmpeg isn't installed, please check instructions of how to install it on your device.

Temporarily you can disable the `Play audio` to avoid the crash.

**Comment by dmctavish** [comment]
that was it, thanks for the prompt reply!
