### ISSUE TITLE
Question: what does Sensor (Not armed) mean?

### ISSUE THREAD

**Issue by jsiegenthaler** [MiguelRipoll23/homebridge-securitysystem#104]
What does this mean:
`[12/04/2021, 18:05:08] [Security system] Sensor (Not armed)`

It appears in the Homebridge log with a Warning level

Using homebridge-securitysystem v4.2.0-beta.1

(note that your current release is a beta release...)

**Comment by MiguelRipoll23** [comment]
It means that you're turning on the `Siren` switch when the security system is not armed.

Yup, there's a beta release right now published in the stable channel but it's a safe release and the beta tag is gonna be removed today. Thanks for the warning!

**Comment by MiguelRipoll23** [comment]
Current release from the stable channel fixed.
