### ISSUE TITLE
Terminology Tweaking

### ISSUE THREAD

**Issue by jsiegenthaler** [MiguelRipoll23/homebridge-securitysystem#105]
So I've used the alarm system now for a night and a day.

And my eagle eyes note the following:

The switches labeled as "Mode Home", "Mode Away", etc. are actually arming switches
Changing the Alarm from an Off state to one of the other states shows an "**Arming...**" status in the Home app.
(This is probably a Home app text which you cannot influence.)

So the better names for the "Mode" switches would be "Arm" switches
eg:

**Arm Home
Arm Away
Arm Night**

------------------------------------------------------

**Order of Switches**
In the Security System tile, the switches are shown in this order:

[Security system]     [Alarm Trigger]
[Arm Away]             [Arm Home]
             [Arm Night]

The order of switches is not the same as the tile. The order would be better as follows:

[Security system]     [Alarm Trigger]
[Arm Home]             [Arm Away]
             [Arm Night]

Also, the default name should be "Security System", where both words are capitalized. This looks better in the English language.

**Comment by MiguelRipoll23** [comment]
I try to avoid using verbs in accessory names but it's true that some new users are struggling to understand the plugin so I'll considerate changing it or find an alternative.

Security system accessory name is now correctly capitalized in beta 2, appreciate the feedback.

**Comment by jsiegenthaler** [comment]
Thanks. I am still configuring and setting up the alarm so that the family doesn't get bothered.

Question:
How do you use the audio functions?
I'm confused as to what audio device is used to output the sounds.
I've currently gor TTS running on the my Sonos speaker system using the Webhooks when the alarm is triggered. But not sure how to add the native audio from the plugin.

**Comment by MiguelRipoll23** [comment]
For the audio feature, you just need to connect an speaker to the audio jack / USB port from your device and [follow the instructions](https://github.com/MiguelRipoll23/homebridge-securitysystem/wiki/Playing-sounds-with-ffmpeg).

Voice warnings are used bu default, you can also use custom ones by setting a path and following the instructions created.

Note: sometimes the default audio device isn't detected, there's a a closed issue which may help.

**Comment by MiguelRipoll23** [comment]
I was planning to rename the `Siren` switches to `Trigger` but during testing I found out that for example for the `Trigger Home` switch the text was broken in two lines and didn't look as good as the other ones...

I'll keep the issue open while I find alternatives that could help understand how the plugin works.

**Comment by MiguelRipoll23** [comment]
I'll keep the current names after some testing, although they could be changed in the future depending if they play nice with the Home app UI.
