### ISSUE TITLE
command_current_triggered generates command failed even when it executes successfully

### ISSUE THREAD

**Issue by jsiegenthaler** [MiguelRipoll23/homebridge-securitysystem#108]
**Describe the bug**
Executing a curl command for "command_current_triggered" results in `Command failed` being displayed, even though the command executed successfully with `Command output: {"status":"success"}` being logged, and (in my case) the TTS working correctly and the audio being broadcast correctly.

The relevant log lines are:
```
[12/04/2021, 21:57:15] [Security System] Command failed (curl http://192.168.0.100:5005/Kitchen/say/Hello%20Kitchen)
100    20  100    20    0     0     10      0  0:00:02  0:00:01  0:00:01    10

[12/04/2021, 21:57:15] [Security System] Command output: {"status":"success"}
```

**To Reproduce**
1. Add any curl command to command_current_triggered
2. Trigger the alarm to cause the command to be executed
3. Observe the results

**Expected behavior**
A curl command that executes without error, and returns success, should not generate a Command failed error.

**Plugin's configuration**
This is the curl command I use to trigger text-to-speech for my Sonos speakers:

`            "command_current_triggered": "curl http://192.168.0.100:5005/sayall/Warning%21%20Alarm%20system%20triggered%21%20Check%20the%20house%20for%20intruders%21",
`

**Comment by MiguelRipoll23** [comment]
Hey there,

The curl command was designed to output the speed and time of the request as an error. Please add the arguments `--silent --show-error` to your command to discard it and avoid the command failed message.

[More information here.](https://stackoverflow.com/a/45659500)
