### ISSUE TITLE
Change Request: Stateful Mode and Siren Name in iOS 13

### ISSUE THREAD

**Issue by Nastras** [MiguelRipoll23/homebridge-securitysystem#11]
Hello, I would like to use your plugin in the future. But first thank you very much for your work.
I tested it today and I noticed two things where I want to ask you if you can still adapt it?

1. After rebooting the Homebridge the switch of the alarm system will be reset to default mode. Can you add a stateful option in config.json to save the state of the switch?

2. The switch Siren has no name in the home app in iOS 13. I am currently using another switch that I want to replace with yours because the name of additional switches is displayed.

Your Plugin:
![IMG_1600](https://user-images.githubusercontent.com/27686185/65569672-99b1d880-df5e-11e9-8641-aa127aacc9dc.jpg)

Other Plugin:
![IMG_1601](https://user-images.githubusercontent.com/27686185/65569685-a6cec780-df5e-11e9-9478-470b81a761bd.jpg)

I would be very happy if you take a look at it.

Many greetings
Nastras

**Comment by MiguelRipoll23** [comment]
Thanks for the words.

I'll add these two features hopefully today if it's possible since I got a busy week ahead. Can you, by any change, give me the name of the other plugin to check how the accessory names are implemented to work on iOS 13?

**Comment by Nastras** [comment]
No problem. Here is the link:

https://github.com/grover/homebridge-automation-switches

It would be great if you make it today. If no also not tragically 😉

**Comment by MiguelRipoll23** [comment]
I just released a new version (v1.5.0) that adds state persistence as an option. Accessory names are received and shown correctly by the Home app but still don't appear on the accessory view controls so I need to continue investigating this. 

That plugin appears to be registering itself as a platform but I'm not sure if that's related so I'll take another look at it today to see if it can be helpful.

Thanks for the link.

**Comment by Nastras** [comment]
Thanks for the info. I am curious and keep my fingers crossed 👍👍👍

**Comment by MiguelRipoll23** [comment]
It looks like accessory names only appear when there's more than one switch :(

**Comment by Nastras** [comment]
That's stupid. I'm thinking all the time about an extra feature but I can't think of anything useful. 😔

Do you have another idea?

**Comment by MiguelRipoll23** [comment]
Nest Secure cancels any armed mode if motion is being detected while arming but I’m unable to implement it without making the plugin setup very cumbersome 😢

**Comment by Nastras** [comment]
But the idea is cool 🤪
but also only for the mode absence

**Comment by Krocko** [comment]
Maybe you can add a (fake)switch so we don‘t need to confirm the rule trigger?

**Comment by MiguelRipoll23** [comment]
Are you talking about the confirmation that appears when you’re using the arrive/leave home triggers, right?

These triggers are very unreliable, unfortunately. I would hesitate to add them to a security system at least until Apple allows you to improve its accuracy.

My lights turned off a few times without me leaving the house 😅

**Comment by Krocko** [comment]
Yes. I mean this.

**Comment by MiguelRipoll23** [comment]
Looks like Apple have listened to all the feedback and a option to separate tiles on the Home app has been added on iOS 13.2 beta 1.

This means that we can close this issue if the option hits the public 😇

**Comment by Nastras** [comment]
That's nice news. 

i actually think it's better if the devices are grouped. But that's a matter of taste. I noticed today that my lock at the homebridge-nuki plugin has a lock device two switches.

Both switches also have a name in one device, do you have any idea why it's being displayed?

![A1AAC37E-3BC3-4AD4-BE8B-AFEA76A77889](https://user-images.githubusercontent.com/27686185/66074396-6a502c80-e559-11e9-9d2b-120494b17fb6.jpeg)

**Comment by MiguelRipoll23** [comment]
My understanding is that If the accessory contains two or more sub-accessories from the same type (like the two locks in your screenshot) the name is displayed, otherwise it's not visible even though it's received correctly.

**Comment by Nastras** [comment]
Okay, that's not how I understood it. This is of course very stupidly solved -.-

**Comment by MiguelRipoll23** [comment]
I just added a characteristic to the security system called `Security System Siren Active` that allows to trigger it without needing the siren switch so an option to disable this switch has been added.

**Comment by CooperCGN** [comment]
Just to get it right: with Siren disabled in config.json the security system itself will never switch to triggered, instead my automations would look like this: sensor detects something and system is set to away then do this and that?

**Comment by MiguelRipoll23** [comment]
You need to set the action using the Eve app or a similar HomeKit app that displays custom characteristics as the Home app won’t display them.

You will see two custom characteristics there when adding an action, if you still need help feel free to ask more questions here.

**Comment by CooperCGN** [comment]
Got it, the switch is basically only hidden from Apple's home app. I still think there is a bug in it. try the following with eve app open.

Set systen to e.g. away
Trigger siren
System is set to trigged.
Set System to off
In the eve app siren stays active and when trying to turn it off I get a red exclamation mark next to it.

**Comment by MiguelRipoll23** [comment]
@CooperCGN bug fixed, update to the latest version.

Thanks for your help and sorry!

**Comment by CooperCGN** [comment]
No need to say sorry, I’m happy to help and ironing out any bugs.
