### ISSUE TITLE
Fix display name in package.json

### ISSUE THREAD

**Issue by jsiegenthaler** [MiguelRipoll23/homebridge-securitysystem#110]
**Describe the bug**
Display name needs fixing in package.json

package.json:
```
{
  "name": "homebridge-securitysystem",
  "displayName": "Security system",
```

displayName should be Security **S**ystem, with a capital **S** on System, to match the config.schema title

**Comment by MiguelRipoll23** [comment]
Plugin name changed to `Security System` in beta 2.

Thanks!
