### ISSUE TITLE
Home Screen (favorites) status is always off, 

### ISSUE THREAD

**Issue by ursusHU** [MiguelRipoll23/homebridge-securitysystem#112]
On the Home Screen the status changes not shown correctly. It is always OFF.
![F4AAEE5E-6EE4-47D2-AF30-C1D1E494A53B](https://user-images.githubusercontent.com/61931127/115948783-7a7b8400-a4d0-11eb-94fc-637b3c0845c6.jpeg)
![0A61699D-AF4F-407E-9591-057F5BDA755C](https://user-images.githubusercontent.com/61931127/115948913-4f456480-a4d1-11eb-8971-3c10d5a32848.png)

**Comment by MiguelRipoll23** [comment]
How your settings look like? This seems like a Home app bug.

**Comment by ursusHU** [comment]
Nothing really set, as I’m planning to connect the states to real relays in order to control my existing dumb alarm system. Just removed some switches and off mode.

{
            "name": "Security system",
            "default_mode": "Home",
            "arm_seconds": 5,
            "trigger_seconds": 0,
            "reset_minutes": 10,
            "audio": false,
            "audio_language": "en-US",
            "save_state": true,
            "proxy_mode": false,
            "test_mode": false,
            "override_off": false,
            "night_trigger_delay": false,
            "reset_off_flow": false,
            "disabled_modes": [
                "Off"
            ],
            "siren_sensor": false,
            "siren_sensor_seconds": 5,
            "reset_sensor": false,
            "mode_switches": false,
            "mode_off_switch": false,
            "mode_away_extended_switch": false,
            "mode_pause_switch": false,
            "pause_minutes": 0,
            "arming_lock_switch": false,
            "siren_switch": false,
            "siren_mode_switches": false,
            "double_knock": false,
            "double_knock_seconds": 90,
            "audio_volume": "100",
            "audio_arming_looped": false,
            "audio_alert_looped": false,
            "accessory": "security-system"
        }

**Comment by MiguelRipoll23** [comment]
Remove the `Off` mode from the list of disabled modes, the option to remove it will disappear soon (it's mandatory to have the `Off` mode enabled) and disabling it will produce errors.

Hopefully that fixes the issue.

**Comment by ursusHU** [comment]
Unfortunately, your suggestion didn’t solved The problem. When I shut down The Home app when loading for a few seconds the correct status is visible and then it is overwritten.

https://user-images.githubusercontent.com/61931127/115970100-a898ac80-a540-11eb-8609-92ff22b45c5d.mov

**Comment by ursusHU** [comment]
I think I see what is causing the problem. I have an Aqara hub which is also including a security system, and even though it isn’t included to show status on the Home Screen somehow overtakes the control.

**Comment by MiguelRipoll23** [comment]
It could be that, just to confirm. What are you doing to reproduce?

You just set a mode and restart the Home app?

**Comment by ursusHU** [comment]
Now I’m pretty sure the Aqara status is influencing it although the status isn’t connected to that tile. If I set the Aqara to away (it has only off and away) then the status of the security system appears correctly. (night/away/home/off) as soon as I turn off the Aqara alarm, the status remains always off. Weird...

**Comment by MiguelRipoll23** [comment]
Mystery solved 😄
