### ISSUE TITLE
Unknown switches  (siren away & siren night)

### ISSUE THREAD

**Issue by Nastras** [MiguelRipoll23/homebridge-securitysystem#113]
Hello @MiguelRipoll23,

since the last update I am shown two additional siren switches (siren away & siren night). I have not changed anything in config.json and can not explain why they are displayed. Both have no function when I turn them on.

Do you have any idea why they are displayed or how I can hide them?

![9481D453-853D-45C7-B3C2-4A89BF05310F](https://user-images.githubusercontent.com/27686185/115957367-48831580-a502-11eb-89f9-f15869d91915.jpeg)
![4B5EA2D0-FF03-4343-89A0-7F57C4B26512](https://user-images.githubusercontent.com/27686185/115957369-4a4cd900-a502-11eb-8c57-2155cc60df31.jpeg)
![2FD9CF81-4D07-4390-AB82-D72AC25C9EFD](https://user-images.githubusercontent.com/27686185/115957371-4ae56f80-a502-11eb-8a97-ff1a31f80ade.jpeg)

**Comment by MiguelRipoll23** [comment]
Hey there!

Add `siren_mode_switches` with **false** value, this was a change done a couple months ago to make the plugin more friendly for new users so the default values changed.

Sorry for the inconvenience.

**Comment by MiguelRipoll23** [comment]
By the way, those switches that you see only work if their mode is set. For example, you can only turn on `Siren Away` if the Away mode is set on the security system and then it will trigger it.

It's a simple way to make condition-less automations.

**Comment by Nastras** [comment]
Worked. Thanks for the quick reply. Amazing that the switches have only now appeared. Or I have overlooked these until now.

Thanks!
