### ISSUE TITLE
"No response" on arming

### ISSUE THREAD

**Issue by 0ldF0x** [MiguelRipoll23/homebridge-securitysystem#114]
Hi,
I get the "No response" error almost every time I set the security system to "Away". It works after few retries.
Please see [this video](https://imgur.com/hCgIbfQ)

**Plugin's configuration**
 {
                    "accessory": "security-system",
                    "name": "Bike security system",
                    "default_mode": "off",
                    "disabled_modes": ["night","home"],
                    "override_off": false,
                    "arm_seconds": 1,
                    "trigger_seconds": 1,
                    "siren_switch": true,
                    "save_state": false,
                    "webhook_url": "http://url.removed:port",
                    "webhook_current_home": "/removed",
                    "webhook_current_away": "/removed",
                    "webhook_current_night": "/removed",
                    "webhook_current_off": "/removed",
                    "webhook_current_triggered": "/removed"
                  }

I've already mentioned this problem in some other thread and I thought that the problem was in too long "trigger_seconds" interval. But it looks like this isn't the issue.

Any idea how to debut the issue?

**Comment by MiguelRipoll23** [comment]
Hey there!

Can you paste the log from the plugin here when it fails?

**Comment by MiguelRipoll23** [comment]
I cannot reproduce, there's probably an automation that's running trying to do an invalid action on the security system at the same time that the mode is set.

**Comment by 0ldF0x** [comment]
Actually nothing is logged when I get the "no response" error.
I've started homebridge with "-D" debug flag. 
When everything is ok (no "no response" message) I get those logs:

```
[4/26/2021, 9:36:54 PM] [Bike security system] Target mode (Away)
[4/26/2021, 9:36:54 PM] [Bike security system] Command option for target mode is not set.
[4/26/2021, 9:36:54 PM] [Bike security system] Webhook option for target mode is not set.
[4/26/2021, 9:36:55 PM] [Bike security system] Current mode (Away)
[4/26/2021, 9:36:55 PM] [Bike security system] Command option for current mode is not set.
[4/26/2021, 9:36:55 PM] [Bike security system] Webhook event (Sent)
```

Btw, I've disabled some debug logging with this command in "/etc/init.d/homebridge":
cmd="DEBUG=*,-engine.io-client:*,-HAP-NodeJS:*,-socket.io-parser*,-socket.io-client* /usr/bin/homebridge"

Is this logging still disabled if I run homebridge with -D flag ? Maybe this silenced some errors and that's why I don't get any error or something?

**Comment by MiguelRipoll23** [comment]
Looks okay to me, is there any warnings?

**Comment by MiguelRipoll23** [comment]
It could be that an automation is trying to turn on the `Siren` switch while arming but I'm unsure, one way to see what could be happening would be to separate the tiles (it's an accessory setting inside the Home app) and see which one is not responding.

**Comment by 0ldF0x** [comment]
Sorry for the late reply.
There are no warnings or automations related to security system. I've also tried to seperate the tiles and "No response" message is on the siren.
It looks like the command doesn't even reach the HomeBridge as there are no logs.

However I've noticed that the thing is much more responsive if I go to the "Rooms tab" and arm the security system directly from the room.
I think that the problem is because I've 8x "Camera-ffmpeg" cameras installed and added as favorite (on the 1st screen) and when I'm on the 1st "Home" tab it's constantly refreshing those cams and system is much more unresponsive because of that.

For now it looks like that everything is ok on your side. I'll try to remove some ffmpeg cameras and see if it helps :)

Thanks for the support.

**Comment by MiguelRipoll23** [comment]
That's weird, the `Siren` switch shouldn't even report `No response` unless it was on and needed to be turned off during arming. Maybe try to move it to a Child Bridge.

BTW, which plugin version are you using?

**Comment by 0ldF0x** [comment]
Well yes, it returned "No response" ([see attachment](https://imgur.com/9arYgjj)). But like I said, if I remove some of the ffmpeg cams away from the home screen, everything is more responsive.

What did you mean by "Child bridge"? Should I run another instance of homebridge or what?

I'm on v 3.9.0 and trying to update to the 4.3.1, but I'm getting some error :(

```
pi@xxxx:/usr/lib/node_modules $ sudo npm install -g --unsafe-perm homebridge-securitysystem
npm ERR! code ENOENT
npm ERR! syscall rename
npm ERR! path /usr/lib/node_modules/.staging/homebridge-securitysystem-3c709201/node_modules/accepts
npm ERR! dest /usr/lib/node_modules/.staging/accepts-1560f441
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, rename '/usr/lib/node_modules/.staging/homebridge-securitysystem-3c709201/node_modules/accepts' -> '/usr/lib/node_modules/.staging/accepts-1560f441'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-02T11_03_57_998Z-debug.log
```

**Comment by MiguelRipoll23** [comment]
It's feature from Homebridge,[check this out.](https://github.com/homebridge/homebridge/wiki/Child-Bridges)

Update npm to the latest version using the following command, looks like an issue there:

`sudo npm install -g npm i`

**Comment by 0ldF0x** [comment]
Hmm, I'm also getting error while trying to update npm using that command:
```
sudo npm install -g npm i
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: colors@1.3.3 (node_modules/npm/node_modules/colors):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ELOOP: too many symbolic links encountered, open '/usr/lib/node_modules/npm/node_modules/colors/package.json.3881415425'

npm ERR! code ELOOP
npm ERR! syscall open
npm ERR! path /usr/lib/node_modules/npm/node_modules/abbrev/package.json.4271761596
npm ERR! errno -40
npm ERR! ELOOP: too many symbolic links encountered, open '/usr/lib/node_modules/npm/node_modules/abbrev/package.json.4271761596'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-05-02T11_19_20_376Z-debug.log
```

Woow, thanks for info about child bridges, did't know about that feature. I'll definitely isolate those ffmpeg cameras and some other plugins to seperate child bridge.

**Comment by MiguelRipoll23** [comment]
That's an strange issue you got there with npm 😅

Maybe try upgrading to Node 12 (unless that's the version you're already currently at) to see if the issues disappear. That's my first time seeing that kind of error!

**Comment by 0ldF0x** [comment]
I'm on node v15.5.0. If I remember correctly you have to re-install everything (whole npm folder) after updating node?
I'll try to google that error...

**Comment by 0ldF0x** [comment]
Ok, I've installed the latest version of node and successfully updated to the latest version of security system.
I'll move some accessories to the child bridge.
Like I already said, I think that the problem was because I had 8xffmpeg cams on the home screen, which probably causes occasional "no response".
You can close this case. Will reopen it if I'll be able to reproduce the problem :)
Thanks for the support!

**Comment by MiguelRipoll23** [comment]
Was the problem solved?
