### ISSUE TITLE
Does not trigger HomeKit Automation when triggered

### ISSUE THREAD

**Issue by lukasmalkmus** [MiguelRipoll23/homebridge-securitysystem#116]
**Describe the bug**

I have created a very simple setup:
- The plugin is setup with "Off" and "Away" modes only, the global siren switch is enabled.
- One HomeKit automation triggers the siren if a motion sensor detects motion
- One HomeKit automation plays sound on my HomePod when the security system is triggered

Both automations work on their own. However, enabling the siren switch, does not set off the "when security system is triggered" automation. I get a notification that the alarm system was triggered and it shows as triggered in HomeKit, but the automation never fires. I can't see an issue with my setup, so I suspect, it must be the plugin 

**To Reproduce**

1. Setup plugin with "Off" and "Away" modes only and enable the global siren switch
2. Create a HomeKit automation which turn on the siren switch if a motion sensor detects motion and test it -> Test it, it should trigger the alarm system
3. Create a HomeKit automation which does something when the security system is triggered -> Test it, it should trigger whatever was configured
4. Turn on the siren switch which triggers the alarm system

**Expected behavior**

Step 4 correctly sets off the alarm system. It should also execute the automation described in step 3. But that never happens.

**Plugin's configuration**

```json
{
      "name": "Sicherheitssystem",
      "default_mode": "Off",
      "arm_seconds": 0,
      "trigger_seconds": 0,
      "reset_minutes": 5,
      "audio": false,
      "audio_language": "en-US",
      "save_state": true,
      "proxy_mode": false,
      "test_mode": false,
      "override_off": false,
      "night_trigger_delay": false,
      "reset_off_flow": false,
      "disabled_modes": [
          "Home",
          "Night"
      ],
      "siren_sensor": false,
      "siren_sensor_seconds": 5,
      "reset_sensor": false,
      "mode_switches": false,
      "mode_off_switch": false,
      "mode_away_extended_switch": false,
      "mode_pause_switch": false,
      "pause_minutes": 0,
      "arming_lock_switch": false,
      "siren_switch": true,
      "siren_mode_switches": false,
      "double_knock": false,
      "double_knock_seconds": 90,
      "audio_volume": "100",
      "audio_arming_looped": false,
      "audio_alert_looped": false,
      "accessory": "security-system"
  }
```

**Additional context**

None

**Comment by MiguelRipoll23** [comment]
Hey there,

Can you screenshot the automation? It's working for me correctly with your configuration.

**Comment by lukasmalkmus** [comment]
Triggering the alarm system when a motion sensor detects motion:

![IMG_8230](https://user-images.githubusercontent.com/9931588/117516014-27a5d000-af98-11eb-9a10-34aae102263f.PNG)

Reacting on the triggered alarm system:

![IMG_8231](https://user-images.githubusercontent.com/9931588/117516016-2a082a00-af98-11eb-8128-296e944b7561.PNG)
![IMG_8232](https://user-images.githubusercontent.com/9931588/117516018-2aa0c080-af98-11eb-87e4-0c8daacfba33.PNG)

Getting the notification upon testing the automation from the first screenshot:

![IMG_8233](https://user-images.githubusercontent.com/9931588/117516021-2b395700-af98-11eb-84d7-7bd301b7e454.PNG)

**Comment by MiguelRipoll23** [comment]
Which iOS version your HomeKit Hub is at?

Maybe move the security system to a child bridge, if the triggered notifications is working the automation should run, something’s wrong between HomeKit and Homebridge.

**Comment by lukasmalkmus** [comment]
I'm on latest OS on all devices. Will try with a sub bridge and report back.

**Comment by MiguelRipoll23** [comment]
Is the issue still happening?

**Comment by lukasmalkmus** [comment]
I wasn't able to resolve it unfortunately :/

**Comment by MiguelRipoll23** [comment]
Does the “Test This Automation” action from the Home app works? It could be related to your HomeKit Hub.

**Comment by lukasmalkmus** [comment]
Yes, this worked afaik. Will tear down my setup on the weekend and try a fresh installation.

**Comment by MiguelRipoll23** [comment]
Sorry for pinging again, does this issue continues? If so, what's your HomeKit Hub?

**Comment by lukasmalkmus** [comment]
I'm. so sorry, I wasn't able to do it yet. I'll do it by the end of this week! I have and Apple TV 4K and a HomePod mini as Home Hub.

**Comment by lukasmalkmus** [comment]
My fix came right after GitHub Bot closed this: I used an IKEA motion sensor previously. They got an update last week (well, the Gateway) and it seems to resolve some issues with HomeKit. No my alarm is triggered correctly!

**Comment by MiguelRipoll23** [comment]
Glad this is fixed, enjoy! 😃
