### ISSUE TITLE
Info button Home tab

### ISSUE THREAD

**Issue by serenacloos** [MiguelRipoll23/homebridge-securitysystem#117]
The info button on top menu in the home tab isn’t showing the status of the alarm when triggered. 
It does show correctly in the room where the alarm is placed.

**Comment by MiguelRipoll23** [comment]
Do you have more than one security system? This looks like a duplicate of #112 (HomeKit bug).

**Comment by serenacloos** [comment]
Yep, that must be the problem. I guess there’s no option to turn the alarm option for the Aqara hub off.

**Comment by MiguelRipoll23** [comment]
Sorry, it’s a Home app bug. Hopefully Apple improves the app this year and fixes these issues.
