### ISSUE TITLE
Set Different Arming and Trigger Delay Times

### ISSUE THREAD

**Issue by DaveEdwards97** [MiguelRipoll23/homebridge-securitysystem#119]
I just want to start by saying thank you for creating this awesome plugin to create a virtual HomeKit Security System. 

I would like to see if possible, different arming and trigger times. For example, when Home Arming and Night Arming, I may want to arm immediately, but for away, I may want 30 seconds to arm so I have time to leave my home.

Same with triggering the system using the individual Trigger Switches, I may want in Night Arm to trigger immediately or 10 seconds. But in Away Arm, I would want to trigger in 30 seconds so I have time to disarm the system without it triggering.

**Comment by MiguelRipoll23** [comment]
Hey there,

Thanks for the feedback :)

There’s an option at the moment to trigger without delay for the night mode within the advanced settings section (Trigger During Night Mode With Delay) which you can disable to trigger immediately.

I’ll add another for arming soon!

**Comment by DaveEdwards97** [comment]
Hi Miguel,

Thank you for your response. I didn't notice that option, so thank you for pointing it out :)

I would still like to see individual fields to set custom arming delays and trigger delays for all arm states please. I think these will be really useful in general to give more fine tuned flexibility.

Maybe it can be added to the Advanced section for advanced users to then set individual arming delays and trigger delays per arm state. So if an arm state has custom delays, it will override the primary delays in basic setup.

**Comment by MiguelRipoll23** [comment]
Noted, will add it that way as well.

**Comment by DaveEdwards97** [comment]
Cheers Miguel!

Looking forward to the implementation.

**Comment by MiguelRipoll23** [comment]
It's now available in the beta channel for testing:

`npm install -g homebridge-securitysystem@beta`

Thanks!

**Comment by DaveEdwards97** [comment]
Awesome work to get this implemented into the beta channel quickly!

I don't have a testing environment to hand yet, but I've reviewed the commit. (I'm quite new to GitHub, so learning as I go)

I see you've added **home_arm_seconds**, **night_arm_seconds**, **away_arm_seconds**, **home_trigger_seconds**, **night_trigger_seconds**, and **away_trigger_seconds** to the `config.schema.json` file. 

But I've noticed **night_trigger_seconds**, and **away_trigger_seconds** don't appear in `accessories.schema.json`. Is this intentional?

Also, while looking at the implementation of these individual overrides, I don't think the options **night_arm_delay** and **night_trigger_delay** make much sense anymore with the individual override fields in which people can set to whatever delay or no delay they want.

**Comment by MiguelRipoll23** [comment]
I'm planning to remove  the `accessories.schema.json` file (the accessory schema used for HOOBS) soon as the `config.schema.json` used for Homebridge is compatible as well.

The night delay options,  you're completely right. It makes sense to remove them in favor of the new individual options that have been added so I'll get them removed.

Welcome to GitHub ;)

**Comment by MiguelRipoll23** [comment]
Feature is now in the stable channel, enjoy!
