### ISSUE TITLE
Double knock for night-state

### ISSUE THREAD

**Issue by ACWAKKERMANS** [MiguelRipoll23/homebridge-securitysystem#122]
Love this plug-in!
Would you consider the double-knock feature for mode “Night” as you have it for mode “Away”?

**Comment by MiguelRipoll23** [comment]
Hey there,

Sure! Will add it as well.

**Comment by MiguelRipoll23** [comment]
It's now available in the beta channel for testing:

`npm install -g homebridge-securitysystem@beta`

Thanks!

**Comment by ACWAKKERMANS** [comment]
Thanks! So quick! Will install this later today or tomorrow AM and let you know.
Currently my PIR sensor triggers the alarm by setting siren to “ON”. All my actions (flicker lights, turn on outside lights, etc) than run of the siren being switched to “ON”. Is that the intended set-up?

Can I also confirm that with the double-knock being enabled, the siren will not switch on unless there is two attempts by any sensor/automation within specified time to switch on the siren?

just to ensure I understand it correctly!

**Comment by MiguelRipoll23** [comment]
That’s the intended setup and I confirm that using double-lock it will require the sensors to be triggered twice within the specified time. 

If you turn on the `Siren` switch it will result in a `No response` error, doing it again within the time window will then actually turn on the switch.

**Comment by ACWAKKERMANS** [comment]
Brilliant! That’s very clever!

**Comment by ACWAKKERMANS** [comment]
I have tested this extensively and found the "double-knock" feature to work very well.
Part of my alarm "eco-system" are external motion sensors, and they would give regular false alarms. This has now stopped. However, when triggering the same sensor again, or when triggering another sensor, within 15 seconds (the time-limit I set), the siren will switch to "ON".
Just this morning, I found two instances in the logs of "Siren (Knock)". Checking the cameras, there was a cat at one instance and nothing visible the second instance. Success!

Thank you very much for all your hard work, for your quick responses and improvements, and for your development of the package!

**Comment by MiguelRipoll23** [comment]
Appreciate the feedback, thank you 😊 

Yeah, due to HomeKit limitations it isn't possible to distinguish one sensor from another and if they get triggered one time at the same time it could lead to a false alarm.

Hopefully Apple adds more features to the security system accessory.
