### ISSUE TITLE
Unnecessary deprecated option warning appearing

### ISSUE THREAD

**Issue by Christian-CFP** [MiguelRipoll23/homebridge-securitysystem#126]
Setting 'Trigger During Night Mode With Delay' has been deprecated, please use `Night Trigger Seconds`.

What setting changes?

   {
            "mode_off_switch": true,
            "double_knock_seconds": 90,
            "double_knock": false,
            "siren_mode_switches": false,
            "reset_sensor": false,
            "reset_minutes": 10,
            "save_state": true,
            "test_mode": false,
            "default_mode": "Home",
            "audio_arming_looped": true,
            "audio_alert_looped": true,
            "audio_language": "de-DE",
            "reset_off_flow": false,
            "plugin_map": {
                "plugin_name": "homebridge-securitysystem",
                "index": 0
            },
            "siren_switch": true,
            "override_off": false,
            "proxy_mode": false,
            "night_trigger_delay": true,
            "audio": false,
            "siren_sensor_seconds": 5,
            "accessory": "security-system",
            "audio_volume": 100,
            "trigger_seconds": 30,
            "mode_pause_switch": true,
            "arming_lock_switch": true,
            "pause_minutes": 5,
            "mode_away_extended_switch": true,
            "mode_switches": true,
            "arm_seconds": 10,
            "name": "Security System",
            "siren_seconds": 15,
            "siren_sensor": true,
            "night_arming_delay": true
        },

**Comment by MiguelRipoll23** [comment]
Hey there!

Just remove the `night_trigger_delay` and `night_arming_delay` for the warning to go away, this a small bug due to default values being set (to avoid breaking behavior) to the deprecated options, my mistake. The warning could be annoying when modifying the configuration so a new patch release would be released to make it disappear.

Now you can set different arming and trigger time delays for each mode so it didn't make sense anymore to have those options around.

By the way, how has been the update experience so far? I've made the plugin more simple internally as I plan the next major step for the plugin.

Thanks for reporting this issue!

**Comment by Christian-CFP** [comment]
night_trigger_delay still reappears after deleting. 

So far the update works great (HOOBS).

**Comment by MiguelRipoll23** [comment]
Fix is now in the stable channel, thanks again for reporting!

**Comment by Christian-CFP** [comment]
Hey only for understanding. There is a general trigger_seconds and also the other ones for home, night etc. 

Is that general trigger_seconds not obsolete? And also the arm_seconds?

**Comment by MiguelRipoll23** [comment]
Actually the mode specific delays options just override the global `Arming Delay Seconds` & `Trigger Delay Seconds` if set, if they're left empty the global ones take effect again.

If set to zero, no delay would happen just like the global ones.

**Comment by MiguelRipoll23** [comment]
You can mix the mode specific delay options with the global ones as well, so for example if you want a custom delay for Night mode you can set it under the advanced options section and the global delay options will still work for the rest of the modes.

**Comment by Christian-CFP** [comment]
Ok. Thats nice. I was wondering why a global one when these modes are there. Thx for clarification.
