### ISSUE TITLE
Add sensor to provide sensor tripped alerts

### ISSUE THREAD

**Issue by Christian-CFP** [MiguelRipoll23/homebridge-securitysystem#128]
Hey. Like the Siren Sensor it would be nice to have a trigger sensor. So when the security system is triggered I will receive a sensor notification in HK. 

when my Kids trigger the System I can stop it before the siren kicks in. HK will not notify me when it is triggered only when the siren is active.

**Comment by MiguelRipoll23** [comment]
A way to notify the user that a sensor has tripped would be nice, right now the only thing you can do is to play some kind of sound but that doesn't work as well when not at home 😅

I'll work on this and release a beta the next weekend.

**Comment by Christian-CFP** [comment]
You are awesome!

**Comment by MiguelRipoll23** [comment]
It's now available in the beta channel for testing:

`npm install -g homebridge-securitysystem@beta`

Thanks!

**Comment by Christian-CFP** [comment]
Thank you! Works fine.
Is it possible to implement a timer in sec. to let the tripped sensor go off every xx sec.? So its harder to miss it ;) Like the Triggered Sensor. Or is this for both?

**Comment by MiguelRipoll23** [comment]
When I was implementing it I thought you would ask for that as well but I kept it basic at least for the first beta as I usually do some minor improvements to the plugin while releasing features 😃

I'll release another beta next weekend with an individual option to set the interval seconds too, no worries.

**Comment by Christian-CFP** [comment]
!!! You are really Awesome !!!
Great and quick support. Even on user wishes/ideas. Love it!

**Comment by MiguelRipoll23** [comment]
Implemented the option to set an interval for multiple notifications in beta 2, by the default it's five seconds.
Happy weekend!

**Comment by Christian-CFP** [comment]
Just installed the beta 2! 
Let me take a closer look Thank you!

**Comment by Christian-CFP** [comment]
Works great!

**Comment by MiguelRipoll23** [comment]
Awesome, published to the stable channel.
Thanks!
