### ISSUE TITLE
Security system jumps to "no response"

### ISSUE THREAD

**Issue by CooperCGN** [MiguelRipoll23/homebridge-securitysystem#13]
When "arm_seconds" is set to a longer duration e.g. 30 seconds the security system accessory shows "no response" on my devices (iOS 13.1.2 & iOS 13.2 beta) with the home app being open. Not sure, but is it maybe that the app is requesting an update but can't get it because the plug in is still in the "getting armed" loop?

**Comment by MiguelRipoll23** [comment]
Should be fixed now, please let me now if you encounter any problems with the notifications. I've tested it by myself and they're being received correctly using 300 for the "arm_seconds" option.

Thanks for the heads up.

**Comment by CooperCGN** [comment]
It is working now, thank you for the quick fix, only thing I recognized is that while it is in the arm_seconds phase and you set it to another mode or off it still turns on after arm_seconds.

**Comment by MiguelRipoll23** [comment]
I missed all these bugs due to having a short arming time on my config 😅

That bug is fixed now too, thanks again.

**Comment by CooperCGN** [comment]
Perfect, will try later, first is work. I am using the timer to get out of the house and then use the arming as a trigger to lock all doors, turn off lights, etc.
