### ISSUE TITLE
Separate "double-knock" values for different armed states

### ISSUE THREAD

**Issue by ACWAKKERMANS** [MiguelRipoll23/homebridge-securitysystem#136]
### What are you missing?

Hi again MiguelRipoll23,

Can't overstate how brilliant your security alarm is! Highly recommend anyone who asks!

To make it even better...
I was wondering if you'd consider allowing separate entries for the "double_knock_seconds" for the different states the alarm might be in. I would like to set my night-time double-knock to 15 seconds, but for day-time "Away", this is too long a period and doesn't filter enough false alarms. 11 Seconds seems more appropriate there in my testing.

_I should point out that the issue I have is caused by me using inappropriate sensors (PIR) for outdoor monitoring.
I want to catch people BEFORE they get into the house, and that was always going to be a challenge, though I feel I'm 95% there... The PIR's are a bit too sensitive during a bright sunny day. I've no issues at night or during over cast days. Making the PIR's "less sensitive" through a shorter double-knock-window seems to be the way to go._ 

I'm also wondering if you'd consider a way to by-pass the double-knock setting. For instance, it would be good if my indoor sensors would trigger the alarm upon first detecting movement, while the outdoor sensors require the double-knock...

**Comment by MiguelRipoll23** [comment]
Hey there,

I think that anything that prevents false alarms should be welcome regardless the type of sensor being used. I just one question, would you mind if the settings could only be added/changed using the JSON file instead of providing these settings using the settings UI? I'm trying to not "overload" the plugin settings but I also understand that the settings UI is preferred so be free to point this to me.

Regarding your question about trying to have different behavior depending of the sensor that tripped, I'm afraid this is not possible as the HomeKit protocol doesn't share any information about the source of the request.

(I think you are the user who replied me on Reddit some days ago, sorry had pretty intense week and couldn't answer!)

**Comment by ACWAKKERMANS** [comment]
Yes, it’s the same user.
Yes, JSON only settings are fine for me.

I wonder if you can do both my questions by approaching this from a different direction.

these settings could be tied to the different siren modes you already have.

The default “double-knock” feature as it is could be tied to the main siren, and by exposing the individual “siren mode” switches, the user can set a double-knock (or not) for the individual switches?

**Comment by MiguelRipoll23** [comment]
That could work, I need to think about it to see if that's the best option.

Basically every Siren switch calls the same logic and the source is indifferent to prevent bugs, so it's quite important to have one single route in the code to not break sensitive parts.

**Comment by ACWAKKERMANS** [comment]
I see.
You may well have better/handier solutions or decide it’s not worthwhile adding in as a feature.
Whatever you decide to do, I’m a fan!

My current work-around is to simply “disable” the PIRs exposed to the sun on sunny days using a dummy switch and rely on door/window sensors installed on gates, the remaining shaded PIRs and internal high frequency motion sensors instead

**Comment by MiguelRipoll23** [comment]
Hey there,

I was thinking about this as I understand the need to change configuration values depending on the mode set, I'm not sure if it helps your case due to the use of different sensors.

It occurred to me that we could use the command options to execute custom commands used to change configuration values as well, so there's no need to create both global and mode options:

![image](https://user-images.githubusercontent.com/3296866/125169974-f078b880-e1ac-11eb-992b-f160bc95b49d.png)
(Concept only)

I understand that if may be enough to solve your issue, you probably need another entry point that will trigger the security system with or without double knock although that's more complicated for testing and reliability.

**Comment by ACWAKKERMANS** [comment]
I’m really sorry. I’m not sure what you mean. I’m not a programmer you see :-(
Would you be able to explain your ideas in a different way? I’m happy to help test or do whatever it takes to try things out

**Comment by ACWAKKERMANS** [comment]
Just wanted to add that initially I had written that it would be good to have some sensors (like internal sensors) which don’t have to “double-knock”. However, I just realised that I could get the automation to SET the siren to ON, wait a second and then SET the siren to ON once more, simulating the double-knock…

This reduces my wish/request to only wanting to be able to have a setting for two different double-knock time-windows. One which I will use for at night or during overcast days at perhaps 15 seconds and a full sun-light one at maybe only 10 or 11 seconds.

**Comment by MiguelRipoll23** [comment]
Sorry for the delay, busy week.

My original idea of this implementation was way too advanced, I would create an option for every mode as proposed initially. More customization is always better, the only thing I need to research is how to handle the additional options visually to avoid filling the entire section with options 😃

I'm pinning this issue so it isn't closed by the state bot, this will probably be implement in August.

**Comment by ACWAKKERMANS** [comment]
You should never apologise for delays. This is your project of which I'm a freeloading, though grateful, user. Thank you, sincerely, for all your hard work!

**Comment by MiguelRipoll23** [comment]
I'm really bad at estimating, it's now available in the beta channel for testing:

`npm install -g homebridge-securitysystem@beta`

Thank you for your understanding 😊

**Comment by ACWAKKERMANS** [comment]
Great! Brilliant!
I have installed it this morning. Went fine.
I emptied the (Double-knock in) Seconds box and also entered nothing under "Home Double-Knock Seconds", 8 under "Away Double-Knock Seconds" and 15 under "Night Double-Knock Seconds". I'll be testing both today and tonight and report back tomorrow (hopefully).
Upon saving I checked the config where all looks good. Checking back into the UI settings I found that the empty (Double Knock in) Seconds box now had 90 seconds defaulted into it. I left it alone...

More for my benefit than yours, but I'm going to collate all my "knocks" in a spreadsheet for a week or so to see what the minimal time-window tends to be during hot sunny days and nights and use as many seconds as possible, but just below the calculated time-window, to ensure we maximise the chance of catching a person and minimise false alarms.

**Comment by ACWAKKERMANS** [comment]
I can confirm it works as intended. Thank you very much!
I now have three "settings":
1) For internal sensors (High Frequency Sensors + Door/Window sensors, I have Set Siren ON -> Wait 1 second -> Set Siren ON as part of the automation, therefore, one sensor trigger event will allow the sensor to bypass the double-knock
2) Night: 14 Seconds
3) Away: 8 Seconds (As my PIRs take 7 seconds to register "No Motion Detected", it'll either have to detect new motion again straight away or another sensor must have detected motion in that time. I'll need to gain experience over time as to what works best.

As a way of saying thanks, i'm intending to do a bit of a tutorial-style write-up explaining how I deployed your plug-in. It really does form the heart of my HomeKit security system.

**Comment by MiguelRipoll23** [comment]
That's awesome, I love seeing plug-in setups 😇
