### ISSUE TITLE
Changing the alarm mode causes Hombridge to restart

### ISSUE THREAD

**Issue by jowallis** [MiguelRipoll23/homebridge-securitysystem#137]
### Plugin version

5.1.1

### Homebridge version

1.3.4

### What happened?

When I change the alarm mode this causes an error that leads hombridge to restart.

### Relevant log output

```shell
Error: spawn ffplay ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
at onErrorNT (internal/child_process.js:465:16)
at processTicksAndRejections (internal/process/task_queues.js:80:21)l
```

**Comment by MiguelRipoll23** [comment]
Hey there,

That error is happening because you don't have ffmpeg installed, once you install it the plugin will be working correctly. As a workaround meanwhile you install it disable the audio feature.

**Comment by MiguelRipoll23** [comment]
Please install the latest release, it will inform now when you don't have ffmpeg installed instead of crashing Homebridge.
Apologies, thanks for the bug report!

**Comment by MiguelRipoll23** [comment]
Can you confirm if the issue is solved now?
