### ISSUE TITLE
Add ability to update state with webhook

### ISSUE THREAD

**Issue by funkyremi** [MiguelRipoll23/homebridge-securitysystem#14]
Hey, Awesome plugin, thanks for your work :-)
I would like to be able to change the displayed state of the security system in homekit when it changes from another source.
Is there any solution to expose a server with some endpoints triggered by an external service to change the state?
Example: I have a hardware button to enable/disable the alarm but the state is not reported to homekit. The only action available is a webhook triggered by an online service when it detect a state change on my alarm.
It would be a nice feature!

**Comment by MiguelRipoll23** [comment]
Right now you can report state changes to an external server. Are you suggesting to add the ability to change the state from it too?

**Comment by funkyremi** [comment]
I don't know if it's possible to start a nodejs server in the extention that listen to localhost:port/update-alarm-state/<armed|night|notarmed> and when the external service (like IFTTT) call that url, only the display state in homekit changes according to the real state of the alarm.
Tell me if it's not clear.

**Comment by MiguelRipoll23** [comment]
It’s clear now 🙂

There are a few issues that you should know: you have to open that port to the internet (must require secure authentication then and I’m not really an expert here) and your IP address could change and fail to update the state if it’s dynamic.

I’m not sure what would be the solution here other than using a service that lets you use a persistent connection and adding such functionality to connect to it.

**Comment by MiguelRipoll23** [comment]
Code refactored, option to disable the arm delay added! These changes are coming to a new release along with #18 pretty soon, hopefully by tomorrow if everything works fine.
