### ISSUE TITLE
A single automation per siren?

### ISSUE THREAD

**Issue by Jafalex** [MiguelRipoll23/homebridge-securitysystem#142]
### Plugin version

5.1.2

### Plugin configuration

{
            "name": "Whare Security",
            "default_mode": "Off",
            "arm_seconds": 0,
            "trigger_seconds": 0,
            "reset_minutes": 10,
            "save_state": false,
            "proxy_mode": false,
            "test_mode": false,
            "override_off": false,
            "reset_off_flow": false,
            "double_knock": false,
            "double_knock_seconds": 90,
            "double_knock_modes": [
                "Away"
            ],
            "tripped_sensor": false,
            "tripped_sensor_seconds": 5,
            "siren_sensor": false,
            "siren_sensor_seconds": 5,
            "reset_sensor": false,
            "mode_switches": false,
            "mode_off_switch": true,
            "mode_away_extended_switch": false,
            "mode_pause_switch": false,
            "pause_minutes": 0,
            "arming_lock_switch": false,
            "siren_switch": false,
            "siren_mode_switches": true,
            "audio": false,
            "audio_language": "en-US",
            "audio_volume": "100",
            "audio_arming_looped": false,
            "audio_alert_looped": false,
            "accessory": "security-system",
            "_bridge": {
                "username": "",
                "port": 46516
            }
        }

### Homebridge version

1.3.4

### What happened?

Hi,

Thanks for a great plugin. I've just installed it and set up all my door/window contact sensors around the house. I understand as per the wiki (question below) that I need to create an automation for my sensor that will turn the siren switch on. But do I have to create one automation for every sensor that would trip the siren switch? I'd end up with easily over 30 automations just for the security system. Am I missing something obvious here?

Thanks!

> I have some contact sensors. How do I use that to trigger the alarm? Create an automation that turns on the Siren switch

**Comment by Jafalex** [comment]
I found out that Eve allows for a lot more flexibility than Home when it comes to this topic. Thanks!

**Comment by MiguelRipoll23** [comment]
Hey there,

Yup! Eve is highly recommended here, it's a great app.
