### ISSUE TITLE
One Knock Triggering For Definitive Sensors

### ISSUE THREAD

**Issue by Chennyisafrag** [MiguelRipoll23/homebridge-securitysystem#145]
### What are you missing?

I recently turned on the double-knock feature since I was getting many false alarms with my Zigbee motion sensors, mostly from my Roomba. 
The feature is great, but I would like to make a feature request to implement a switch (in addition to double-knock) that triggers the alarm only on one knock, regardless of away/home/night modes. It would be great for door/contact sensors, and my lock as those do not trigger on a whim. 
Even though a burglar would trigger many sensors if they were to come, my Zigbee motion and contact sensors are not the most reliable, but my lock is. It would give me peace of mind if this were to be implemented. I hope I explained it well enough to understand.
Thanks for this amazing plugin!

**Comment by MiguelRipoll23** [comment]
Hey there,

Right now you will have to turn on the Siren switch twice by turning on the switch again, if my memory serves me right this can only be done using the Shortcuts app. I can see this feature being useful for contact sensors although it creates another entry point for a critical area that is triggering the security system meaning that it complicates testing.

I will see what I can do , this issue will be open for a while until I figurad it out.

Thanks!

**Comment by MiguelRipoll23** [comment]
This feature will be available soon, some important changes have been applied to the double-knock logic in order to reduce complexity during testing.

**Comment by MiguelRipoll23** [comment]
It's now available in the beta channel for testing:

`npm install -g homebridge-securitysystem@beta`

Thanks!

**Comment by Christian-CFP** [comment]
> It's now available in the beta channel for testing:
> 
> 
> 
> `npm install -g homebridge-securitysystem@beta`
> 
> 
> 
> See `Show Siren Override Switch` under advanced options.
> 
> 
> 
> Thanks!

Hi can you explain what the Siren Overwrite Switch does?

**Comment by MiguelRipoll23** [comment]
Sure.

This switch turns on byoassing any conditions set like double-knock or even if the current selected mode is Off.

For example, if you add a automation to turn it on when a door sensor is tripped and the current selected mode is away... even if double-knock is enabled it will trip the security system immediately and respect the delay you may have to trigger the security system.

The name is kinda confusing so I accept suggestions 😅

**Comment by Christian-CFP** [comment]
Ok. Got it. So it behaves like a "Panic Button". Ignoring every set state/config even Off. Not exactly but nearly and if you add a delay feature to that you could use it as a Panic Button too if you set the delay to 0.

**Comment by MiguelRipoll23** [comment]
It has a delay, I incorrectly said in the beta changelog that it could be used as a panic button but with the delay that's a little bit weird/useless.

A panic switch may be something interesting to have although I don't recommend it as Siri or even you using the Home aññ may turn it on accidentally.

**Comment by Christian-CFP** [comment]
I guess with Siri or HomeApp, EveApp etc. you can accidentally turn on the siren anyway 😅 that's all based on scenes or automations. And it doesn't matter if it is a button. Clicking on scenes or automations is easy as a button click. 😆

**Comment by MiguelRipoll23** [comment]
That’s totally fair 😆

Then I just not recommend using this new switch as a panic button as they probably have 5 seconds delay maximum and this new switch uses the mode delay set which can be higher.

**Comment by MiguelRipoll23** [comment]
Feature is now in the stable channel, enjoy!
