### ISSUE TITLE
Arming sensor

### ISSUE THREAD

**Issue by henrik-palm** [MiguelRipoll23/homebridge-securitysystem#155]
### What are you missing?

Hi Miguel

Awesome plugin!

I would love to trigger automations during the arming phase. To my knowledge it is not possible as it is. Could we add an option for an arming sensor, which is trigged when the system is arming?

I would use this for triggering an automation with warning beeps while the system is arming.

Hope this makes senes to you.

**Comment by MiguelRipoll23** [comment]
Hey there,

It's supported natively by HomeKit, use the Home app to create this automation:

An Accessory is Controlled > Security System > Arms

**Comment by henrik-palm** [comment]
Hi Miguel

Thanks for the quick response. 

Sorry. My issue description wasn't clear. It is during the arming delay that I would like an automation to warn about the system arming.

When the arming delay is running the state of the system is unarmed, so I don't see any way to trigger an automation during the delay. Unless a sensor is added and triggered during the delay. 

I hope this make sense.

**Comment by MiguelRipoll23** [comment]
Are you sure we are not talking about the same thing?

To trigger an automation when the security system is arming right when the delay starts (a mode is about to be set)
An Accessory is Controlled > Security System > Arms

To trigger an automation when the security system is about to trigger (a sensor has tripped the security system and will trigger)
Show Tripped Sensor (plugin settings)

**Comment by MiguelRipoll23** [comment]
My bad, you're completely right.

Enable the option "Show Mode Switches" under the switches section from the plugin settings.

When you set a mode, the switch corresponding to that mode will turn at the moment is arming.

That will help you to create an automation when that mode is being armed do whatever you need.

Sorry, had a headache!

**Comment by MiguelRipoll23** [comment]
Thanks! For the arming sound, are you using AirPlay or a connected speaker?

The former has an option to loop the arming sound until the security system is armed, the AirPlay one I’ll need to check if it’s possible to stop the audio using to automation a (one to detect arming, another one to detect that it’s armed and stop the audio).

**Comment by henrik-palm** [comment]
I am using a smart plug to run a Piezo buzzer. I can work with the two automation setup.

Thank you for the support and this great plugin.
