### ISSUE TITLE
Aqara Hub

### ISSUE THREAD

**Issue by recom273** [MiguelRipoll23/homebridge-securitysystem#16]
Sorry, this isn’t strictly an issue, but just putting it out there.

I used to use the aqara security system, but I moved my sensors from the hub to local server on which uses Homebridge via a raspbee. Regrettably I have lost the security function and the hub functions as a nightlight. 

Is there a way that anyone has found to appropriate the siren on the hub for use with your security center plugin.

I will buy a HEIMAN siren in time. What other options are there for an audible / visual warning?

**Comment by 0ldF0x** [comment]
I'm using Bosch SG200 siren. it works perfect.

**Comment by MiguelRipoll23** [comment]
If you have any AirPlay 2 speakers or HomeKit lights you can convert an automation to a Shortcuts one and do actions like these:

(Sound warning)
1. Set volume to 100%
2. Play alarm sound

(Visual warning, loop to blink)
1. Turn on lights to red
2. Wait 0.2s
3. Turn off lights

It requires iOS 13 though.

**Comment by recom273** [comment]
> If you have any AirPlay 2 speakers or HomeKit lights you can convert an automation to a Shortcuts one and do actions like these:
> 
> (Sound warning)
> 
> 1. Set volume to 100%
> 2. Play alarm sound
> 
> (Visual warning, loop to blink)
> 
> 1. Turn on lights to red
> 2. Wait 0.2s
> 3. Turn off lights
> 
> It requires iOS 13 though.

Ahh yes, could you explain how to convert an automation to shortcut. 

Have you seen the aqara security hub? When I activate the plugin security center, the aqara bridge chimes, but when the system is triggered there is no siren from the unit. I tried separating the tiles and there is just a LED light and security center switch.

**Comment by MiguelRipoll23** [comment]
I wish I could help but I don't know exactly how the Aqara security hub is exposed to HomeKit. Can you provide screenshots of its accessories and automations?
