### ISSUE TITLE
Unable to write log files

### ISSUE THREAD

**Issue by Sudo-Jason-rasp** [MiguelRipoll23/homebridge-securitysystem#163]
![image](https://user-images.githubusercontent.com/83789801/132325102-2b23f6a4-25aa-4d6a-a3ed-b233373578c0.jpeg)

**Comment by MiguelRipoll23** [comment]
Hey there,

Does the directory `/home/user/logs` exists? If so, are the directory permissions right for Homebridge plugins access this directory?

**Comment by Sudo-Jason-rasp** [comment]
I’m new to Raspberry Pi and so what command do I need to run to make the Directory.

**Comment by MiguelRipoll23** [comment]
```
cd /home/user
mkdir logs
```

This will do.

Keep in mind that `user` should be your username (the one that you use to log in to your Raspberry Pi), if your user is `user` then it's ready to be executed! 😄

**Comment by Sudo-Jason-rasp** [comment]
I'm running Homebrige with hoobs will this matter?

**Comment by MiguelRipoll23** [comment]
I don't think so, it should work unless there are security measures restricting writing on the filesystem.
