### ISSUE TITLE
Notification when alarms it triggered

### ISSUE THREAD

**Issue by malmentm** [MiguelRipoll23/homebridge-securitysystem#164]
### Plugin version

1

### Plugin configuration

xfdsdsfsd

### Homebridge version

1.0.5

### What's your question?

Hello! I know this might be a user error but I can't get the notifications when the alarms I triggered on my iPhone. What is the correct way to setup an automation that arms the security system when I leave the house and I still get notifications om my device?

**Comment by malmentm** [comment]
Embarrasing. I had notifications disabled for home app :/

**Comment by MiguelRipoll23** [comment]
No worries 😀
