### ISSUE TITLE
No Response from Siren switch when Security System is disarmed.

### ISSUE THREAD

**Issue by creinhart** [MiguelRipoll23/homebridge-securitysystem#17]
When the security system is Off and you hit the Siren Switch, I keep getting a "No Response" from the switch until I Arm the system. Maybe that's because the switch is just there for the purpose of the Armed states triggering automatons, but it's really nice to have a manual toggle even when the Security System is off.

**Comment by MiguelRipoll23** [comment]
This was intended behavior due to #6 (creating an automation without needing to add conditions) but it can be reverted if people in here would like to add a manual trigger button too.

**Comment by creinhart** [comment]
Manual toggle would be nice but not if it’ll undo the previous work you’ve done.

**Comment by MiguelRipoll23** [comment]
A new option could be added just to ignore the disarmed state and would work fine for both sides without having to revert it, I'll get this done soon.

**Comment by MiguelRipoll23** [comment]
A new version has been released that adds this option, sorry for the delay.
