### ISSUE TITLE
Switch to enable/disable Audio

### ISSUE THREAD

**Issue by macjl** [MiguelRipoll23/homebridge-securitysystem#176]
### What are you missing?

Hello,

Do you think it could be possible to have a switch to dynamicly enable or disable audio ?

My use case : be able to activate security system at night, when everyone is asleep in house, whithout waking up whole family !

**Comment by MiguelRipoll23** [comment]
It's now available in the beta channel for testing:

`npm install -g homebridge-securitysystem@beta`

It will stay in beta for longer than planned due to my life getting a little bit busier, will try to get to release it to the general public as soon as possible.

Thanks!

**Comment by MiguelRipoll23** [comment]
Feature is now in the stable channel, enjoy!

**Comment by macjl** [comment]
I’ve updated, change settings, an the switch is here. I’m not at home to try it, but will do it ASAP.

Thank You!!
