### ISSUE TITLE
Keypad?

### ISSUE THREAD

**Issue by Christian-CFP** [MiguelRipoll23/homebridge-securitysystem#178]
### Plugin version

6.1.0

### Plugin configuration

---

### Homebridge version

1.3.5

### What's your question?

Hi, I do not know if this was already a topic.
But is there a keypad (wireless) that I can use with the securitysystem and maybe homekit?

**Comment by MiguelRipoll23** [comment]
Hey there,

Unfortunately HomeKit doesn’t support this type of accessory, keep in mind that all smart home ecosystem will be merging under the new Matter protocol so it could be supported in the future. I’ll provide support whenever it’s possible as always.
