### ISSUE TITLE
Call cmd command or script via Webhooks

### ISSUE THREAD

**Issue by Nastras** [MiguelRipoll23/homebridge-securitysystem#18]
Hello @MiguelRipoll23 

is it possible to call a cmd command or script via the Webhooks function?

I have tried it but nothing happens when it is triggered, I don't get anything displayed in the journalctl above the Webhooks status. I only see that the status of the alarm system has changed.

Here is my config.json:

"plugins": [
"homebridge-securitysystem"
],

"accessories": [
{
"accessory": "Security system",
"name": "Alarmanlage Zuhause",
"default_mode": "off",
"siren_switch": true,
"override_off": true,
"save_state": true,
"server_port": xxxxx,
"server_code": xxxxx,
"webhook_off": "/bin/bash /var/homebridge-securitysystem/befehle/SirenenZuhauseON.sh",
"webhook_triggered": "/bin/bash /var/homebridge-securitysystem/befehle/SirenenZuhauseOFF.sh"
}
]
}

I guess it doesn't work without going on the internet so my question, it be possible that you add a cmd function similar to the Webhooks?

Thanks for your help!

Greeting nastras

**Comment by MiguelRipoll23** [comment]
Sure, I can add it.

It would require new options but that’s not an issue for me.

I’m also going to move some logic that happens when you change the state to a separate function so we can customize the behavior easily depending on the origin (HomeKit or the HTTP server).

I’d try to release a new version with all this by the next weekend or sooner 👍

**Comment by Nastras** [comment]
That sounds great! I am looking forward to the update .-)

Thanks a lot!

**Comment by MiguelRipoll23** [comment]
Feature implemented and tested, release is already available.

I'm gonna keep this issue open though just in case you would like to change anything of how it's implemented.

Happy weekend :)

**Comment by Nastras** [comment]
I have tested it and everything works great. There is nothing to complain about.-)
Many thanks for the fast and very good implementation !!!

ans also a nice weekend!

Best regards nastras
