### ISSUE TITLE
Add option to choose available security system states

### ISSUE THREAD

**Issue by ferdinand** [MiguelRipoll23/homebridge-securitysystem#19]
It would be nice to be able to choose which security system states are made available, e.g. only Away. I didn't find any clue in the HomeKit Accessory Protocol Specification docs on how to do this, but it seems to be possible. The [Aqara Hub](https://youtu.be/05Dxl638WS8?t=243) for example supports only Away and the [Lyric Security System](https://tidbits.com/2018/06/21/a-prairie-homekit-companion-the-honeywell-lyric-controller-with-homekit/) supports only Home and Away.

**Comment by MiguelRipoll23** [comment]
Sure, I'll check this out at the weekend.

I can't do changes as fast as I did before as I need some rest but I still want to continue working on my personal projects at least some time at the weekends. I'll release a new version this weekend or next if I can get it done.

**Comment by MiguelRipoll23** [comment]
I just released a new version that allows you to disable modes. Check the readme for the option `disabled_modes` 🚀

**Comment by Nastras** [comment]
@MiguelRipoll23 Hey cool new feature. Thanks to both of you.

I tried to hide my home mode, but I get an error when starting the instance.

![A8CE151B-C016-4D5F-A265-9C3CA3610846](https://user-images.githubusercontent.com/27686185/75120696-a497a300-568d-11ea-9210-5bf9543a53f8.jpeg)



Not sure if the config is correct either?

"disabled_modes": "home",

**Comment by MiguelRipoll23** [comment]
Use
`“disabled_modes”: [“home”] `
instead.

It has to be an array, I should clarify it better tomorrow :)

**Comment by MiguelRipoll23** [comment]
Also, once that’s changed you won’t see the effect right away due to how HomeKit works. Set it to any mode and next time you open the modes menu the correct modes would be displayed.

**Comment by Nastras** [comment]
Now it works 👍👌👍

Thank you and have a nice sunday evening!

**Comment by ferdinand** [comment]
Wow! Thanks a lot for your fantastic work! I've sent you a small donation via Paypal 🙂

**Comment by MiguelRipoll23** [comment]
Thank you so much! ❤️
