### ISSUE TITLE
server - delay parameter

### ISSUE THREAD

**Issue by Karrypto** [MiguelRipoll23/homebridge-securitysystem#190]
### Plugin version

6.2.0

### Plugin configuration

.
.   
"arm_seconds": 15,
"trigger_seconds": 20,
.
.

"http://localhost:port/away?code=1234&delay=true" 

### Homebridge version

1.3.8

### What happened?

Hi Miguel, can you please check the server control delay parameter? This doesn't seem to work. The system is armed immediately. 

"http://localhost:port/away?code=1234&delay=true" 

I guess the parameter is using the global value ("away_arm_seconds": 15) or do I have to set the delay value via the url parameter?

**Comment by MiguelRipoll23** [comment]
Hey there, it should use either the global or the mode one (this one will override the global one).

I'll check this out ASAP, hopefully by the weekend.

**Comment by MiguelRipoll23** [comment]
Hey @Karrypto, sorry for the delay and happy new year.

I can't reproduce the issue, can you check if _Away Arming Seconds_ is set to zero? The mode setting will always override the global one.

If everything looks right, please post your full plugin configuration and I'll try to check tomorrow.

**Comment by Karrypto** [comment]
Hi Miguel, happy new year!

That's weired..I have tried it several times with the away mode settings and the global value and with several homebridge service restarts. The values were simply ignored. Just after a complete server/raspberry restart it suddenly works now. Thanks.
