### ISSUE TITLE
HomeKit Status doesn‘t change

### ISSUE THREAD

**Issue by Maddin1684** [MiguelRipoll23/homebridge-securitysystem#195]
### Plugin version

6.2.0

### Plugin configuration

     {
            "name": "Alarmanlage",
            "default_mode": "Off",
            "arm_seconds": 0,
            "trigger_seconds": 0,
            "reset_minutes": 2,
            "save_state": false,
            "proxy_mode": false,
            "test_mode": false,
            "override_off": false,
            "reset_off_flow": false,
            "double_knock": false,
            "double_knock_seconds": 90,
            "disabled_modes": [
                "Home"
            ],
            "tripped_sensor": false,
            "tripped_sensor_seconds": 5,
            "siren_sensor": false,
            "siren_sensor_seconds": 5,
            "reset_sensor": false,
            "mode_switches": false,
            "mode_off_switch": false,
            "mode_away_extended_switch": false,
            "mode_pause_switch": false,
            "pause_minutes": 0,
            "arming_lock_switch": false,
            "arming_lock_switches": false,
            "siren_switch": true,
            "siren_override_switch": false,
            "siren_mode_switches": false,
            "audio_switch": false,
            "audio": false,
            "audio_language": "en-US",
            "audio_volume": "100",
            "audio_arming_looped": false,
            "audio_alert_looped": false,
            "accessory": "security-system"
        }
    ],
    "disabledPlugins": []
}

### Homebridge version

1.3.9

### What's your question?

Hello,
when I arm an alarm in HomeKit to „away“
or „night“ everything works fine, but the status at the bottom in HomeKit doen‘t change. 
There is always securitysystem „off“ set. 

Anyone ideas?

![EC52B0A6-E0C9-41DE-9C79-4D724DC9255E](https://user-images.githubusercontent.com/61165918/150073934-2e608aa4-379e-49f5-b563-6789d80c5dff.jpeg)
![855BF77F-7013-4385-A8E6-5551F47EA3DF](https://user-images.githubusercontent.com/61165918/150073937-5370e963-4347-47b9-841f-68ad8dc2624f.jpeg)

**Comment by MiguelRipoll23** [comment]
Hey there,

Do you have another security system either from a plugin or a real accessory?

The Home app area where accessories' status are shown doesn't display the status of security systems correctly when there are multiple ones.

**Comment by Maddin1684** [comment]
Hey!
that‘s it! thanks for your reply.
the security system from the aqara hub must also to be set to mode „on“, then everything is shown correctly.

many thanks for the hint :-)
