### ISSUE TITLE
Plugin Configuration missing when using HOOBS Homebridge

### ISSUE THREAD

**Issue by Jbb08** [MiguelRipoll23/homebridge-securitysystem#20]
Hi @MiguelRipoll23 I wanted to start by saying how I am so grateful of this plugin, its exactly what I need, so thank you for developing it :)

I use HOOBS 3.1.22 and 2.0.2 of your plugin and when I install plugins I am usually met with a way to config them, at the bare minimum its a box to add the traditional config.json information to mine, or if you are HOOBS certified plugin then its presented out really nicely so its simple for users to config the plugin. On your plugin, nothing is presented. It shows the plugin listed, but when I go to Configuration its nothing but a description :( (see harmony hub as an example of what it should look like as a basic minimum)

I have manually added the config to HOOBS advanced section (which effectively is my config.json) and its working so no issue there (despite the arm timer is 30sec and trigger is 20sec, however when the plugin starts both seem to be 30sec...)
In order for me to raise this with HOOBS I needed to have asked you about it, as it might be something on your end? I do not know.

But if you can shed any light on this that would be greatly appreciated.

Thanks again 
<img width="1397" alt="Screenshot 2020-03-20 at 16 56 24" src="https://user-images.githubusercontent.com/48804661/77188648-3c8e7e00-6ace-11ea-8a5c-cf050412906d.png">
<img width="1529" alt="Screenshot 2020-03-20 at 16 56 38" src="https://user-images.githubusercontent.com/48804661/77188662-3f896e80-6ace-11ea-9ac5-f83650c90a43.png">
<img width="1352" alt="Screenshot 2020-03-20 at 16 57 30" src="https://user-images.githubusercontent.com/48804661/77188666-40220500-6ace-11ea-9383-e9a960173f62.png">
<img width="1493" alt="Screenshot 2020-03-20 at 17 12 19" src="https://user-images.githubusercontent.com/48804661/77188669-40ba9b80-6ace-11ea-82db-98bd3f2e2e94.png">

Update *** HOOBS replied saying that the plugin developer needs to use the config.schema standard.
Any chance you can add the 2 files needed to have your plugin supported :)
https://github.com/hoobs-org/HOOBS/wiki/6.5-Developing-Plugins#hoobs-certification

I think its just a layout so that whenever someone using HOOBS to use your plugin it is super easy to install and configure :)

**Comment by MiguelRipoll23** [comment]
I’m gonna check this out and report back soon.

Thanks for the love! ❤️

**Comment by Jbb08** [comment]
> I’m gonna check this out and report back soon.
> 
> Thanks for the love! ❤️

Thanks Miguel, I am assuming that this error is related to the config issue...
Unable to determine plugin type (likely a HOOBS error)

But what about the 
homebridge.user.persistPath is not a function

<img width="1291" alt="Screenshot 2020-03-21 at 00 47 57" src="https://user-images.githubusercontent.com/48804661/77215726-b7c35480-6b0d-11ea-9951-9d20ca0b2670.png">

**Comment by MiguelRipoll23** [comment]
That's weird, seems like the way Homebridge works inside HOOBS is a little bit different. I'm working right now to add the files that are missing to add HOOBS compatibility and I'll investigate the issues that you found as well.

**Comment by MiguelRipoll23** [comment]
Unfortunately, I can't test the changes I did on Windows.

Would you mind installing this new beta version, please?

`npm i homebridge-securitysystem@2.1.0 `

Thanks!

**Comment by Jbb08** [comment]
> Unfortunately, I can't test the changes I did on Windows.
> 
> Would you mind installing this new beta version, please?
> 
> `npm i homebridge-securitysystem@2.1.0 `
> 
> Thanks!

Thanks so quick :) 
Installed the update to 2.1.0
It added the required certifying element of accessories.schema :)
See video below.

Feedback - 
The fields are great, however the values should match the actual values of the basic/server options (even though the actual printed value on the config file is right(see the advanced screen shot attached

) aka instead of Yes/No, would it not be True/False, as per your values?


However all is not well, my homebridge wont work at all now. Its stalling on - 
[Homebridge] [3/21/2020, 19:49:50] Error: The requested accessory 'SecuritySystem' was not registered by any plugin.
    at API.accessory (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:45:19)
    at Server._loadAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:258:48)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:78:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
[Homebridge] [3/21/2020, 19:49:50] Got SIGTERM, shutting down service...

See attached, might need to roll back mine to 2.0.2

[Archive.zip](https://github.com/MiguelRipoll23/homebridge-securitysystem/files/4363985/Archive.zip)

**Comment by MiguelRipoll23** [comment]
My bad, the command is missing the global parameter:

`npm i homebridge-securitysystem@2.1.0 -g`

**Comment by MiguelRipoll23** [comment]
Regarding your feedback, I can't find the option to modify the user text that appears when the type is a boolean.

Do you have any plugin with a similar configuration that appears to the user as true/false? My guess is that is that it can't be modified to have values more user-friendly instead but I'm not sure.

By the way, thanks for beta testing hopefully you can confirm to me that the state saving error that appeared to you (homebridge.user.persistPath) doesn't happen anymore when using HOOBS.

**Comment by Jbb08** [comment]
Thanks Miguel.
So I tried using npm i homebridge-securitysystem@2.1.0 -g
but it would not fix it, so I uninstalled the plugin.
used terminal to install 2.1.0
But then HOOBS does not show it as a registered plugin as its not installed through their UI.
So I removed it.
Installed 2.0.2, and tried upgrading to 2.1.0 using npm i homebridge-securitysystem@2.1.0 -g
But it still stays at 2.0.2?


Any ideas?
<img width="1669" alt="Screenshot 2020-03-21 at 21 20 28" src="https://user-images.githubusercontent.com/48804661/77236880-85bbfc00-6bba-11ea-8057-259623222d27.png">
<img width="1189" alt="Screenshot 2020-03-21 at 21 25 16" src="https://user-images.githubusercontent.com/48804661/77236882-88b6ec80-6bba-11ea-8d03-beecbb2637db.png">
<img width="1333" alt="Screenshot 2020-03-21 at 21 25 27" src="https://user-images.githubusercontent.com/48804661/77236883-89e81980-6bba-11ea-971c-4433e5955523.png">

PS very happy to beta test for you :) A lot of users have their Homebridge setup via HOOBS as its so simple

**Comment by MiguelRipoll23** [comment]
I see on your first screenshot that the g letter is missing at the end, you wrote it correctly before making the screenshot?

Try this instead, this should work:
`npm update homebridge-securitysystem@2.1.0 -g`

**Comment by Jbb08** [comment]
Hi Miguel the -g is there its wrapped to the start of the line unfortunately (a glitch in Hoobs)
Tried that new command above, Hoobs does not update the Plugin, so none of the CONFIG features are showing :(
rebooted my Raspberry PI 4 a few times, but nothing still stuck on 2.0.2

**Comment by MiguelRipoll23** [comment]
I just checked HOOBS documentation, if you aren't able to install a beta version from the interface these are the steps to manually install it.

```
cd ~/.hoobs/
npm install homebridge-securitysystem@2.1.0
sudo hoobs service restart
```

Hopefully it works now :)

**Comment by Jbb08** [comment]
Nope :(

nothing is working :(
you might need to push it from Beta version to live
I have tried all options you present but its not updating in HOOBS, I don't know why.
Despite NPM showing it is the beta 2.1.0

Now even the manual config setup on 2.0.2 isnt working lol

**Comment by MiguelRipoll23** [comment]
Moved package from beta to stable, check it out 🤔

**Comment by Jbb08** [comment]
Ok so installed fresh and it finally grabbed 2.1.0
However I am not sure if the install path that HOOBS calls from NPM includes -g
Because this error is back..

[Homebridge] [3/21/2020, 22:42:37] Error: The requested accessory 'SecuritySystem' was not registered by any plugin.
    at API.accessory (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:45:19)
    at Server._loadAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:258:48)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:78:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[Homebridge] [3/21/2020, 22:42:37] Got SIGTERM, shutting down service...

the CONFIG side, works perfectly, and you are right in relation to YES/NO vs TRUE/FALSE, all other certified plugins use YES/NO so you are correct :)

The Details part of the Plugin is also now not pulling any details? Could this be why the install path isn't working properly?
<img width="1390" alt="Screenshot 2020-03-21 at 22 46 28" src="https://user-images.githubusercontent.com/48804661/77238166-e13fb700-6bc5-11ea-9963-6da1384bebde.png">

**Comment by MiguelRipoll23** [comment]
I think I now what's happening, you have the version installed twice.

Try this `npm uninstall homebridge-securitysystem@2.1.0 -g` to uninstall the global package as HOOBS doesn't use it.

I'll see why the details aren't fetched meanwhile.

**Comment by Jbb08** [comment]
Ok so I have uninstalled as you have mentioned.
The Plugin is still on HOOBS Plugin list, and config there, error still appearing after homebridge restart, HOOBS restart and reboot device :(

**Comment by MiguelRipoll23** [comment]
`npm list -g`

Do you see the plugin on the list?

If you do, try `npm uninstall homebridge-securitysystem -g` without specifying the version.

**Comment by Jbb08** [comment]
Plugin is not listed there nope :)
I ran the uninstall without the version and it cleared 55 files oddly...
But still this error persists :(

[Homebridge] [3/21/2020, 23:04:54] Error: The requested accessory 'SecuritySystem' was not registered by any plugin.
    at API.accessory (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:45:19)
    at Server._loadAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:258:48)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:78:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[Homebridge] [3/21/2020, 23:04:54] Got SIGTERM, shutting down service...

**Comment by MiguelRipoll23** [comment]
That's good.

```
cd ~/.hoobs/
npm uninstall homebridge-securitysystem
```

And reinstall using the HOOBS interface.

If that didn't work you can try to whitelist the plugin using:

`nano ~/.hoobs/etc/config.json`

and adding "homebridge-securitysystem" to the plugins array.

**Comment by Jbb08** [comment]
Ok uninstalled.
Removed all traces from Config.json

Re-installed.
Checked the config.json, it has homebridge-securitysystem in the plugins array.


However the error is still there.
This error stops homebridge from starting at all.
It has something to do with HOOBS not registering your plugin, and I can only think that has something to do with the way the user interface installs it?
It doesn't pull your README or anything oddly?

**Comment by MiguelRipoll23** [comment]
```
cd ~/.hoobs/
npm list
```

Is the plugin there? Check if it appears more than one time too.

**Comment by Jbb08** [comment]
yes it is there, appears only once

+-- homebridge-securitysystem@2.1.0
| +-- express@4.17.1 deduped
| +-- node-fetch@2.6.0
| `-- node-persist@3.0.5
|   `-- mkdirp@0.5.3 deduped
+-- homebridge-webos-tv@1.6.4
| +-- lgtv2@1.4.1
| | +-- mkdirp@0.5.3 deduped
| | +-- persist-path@1.0.2 deduped
| | `-- websocket@1.0.31 deduped
| +-- mkdirp@0.5.3
| | `-- minimist@1.2.5 deduped
| +-- persist-path@1.0.2
| +-- tcp-ping@0.1.1
| `-- wake_on_lan@0.0.4
+-- lodash@4.17.15

**Comment by MiguelRipoll23** [comment]
> It has something to do with HOOBS not registering your plugin, and I can only think that has something to do with the way the user interface installs it?

Actually the way the user interface installs it is the correct one, that's why I'm trying to uninstall the manual installations that we did to see if we fix it.

Can you attach your config.file to investigate this further? (be sure to remove sensitive information)

> ~/.hoobs/etc/config.json

**Comment by Jbb08** [comment]
ok that's good to know.
The reason I thought that is the HOOBS UI doesn't show your plugin like any other, the README isn't pulled, however it does have NPM link and DETAILS link which points to your README oddly.

So I think we literally only have 1 official plugin installed and all traces of it are gone.

another thing I noticed, in the log I see this - 

Notice - [Homebridge] [3/21/2020, 23:17:51] Registering accessory "homebridge-securitysystem.Security system" has a space between Security and system, is that correct?
As the Config accessory name is SecuritySystem
And further down to the actual error it has - 
[Homebridge] [3/21/2020, 23:17:52] Error: The requested accessory 'SecuritySystem' was not registered by any plugin.

LOG - 
[Homebridge] [3/21/2020, 23:17:50] Loaded plugin: "homebridge-alexa"
[Homebridge] [3/21/2020, 23:17:50] Registering platform "homebridge-alexa.Alexa"
[Homebridge] [3/21/2020, 23:17:50] Loaded plugin: "homebridge-dummy-garage"
[Homebridge] [3/21/2020, 23:17:50] Registering accessory "homebridge-dummy-garage.DummyGarage"
[Homebridge] [3/21/2020, 23:17:50] Loaded plugin: "homebridge-dummy-lock"
[Homebridge] [3/21/2020, 23:17:50] Registering accessory "homebridge-dummy-lock.DummyLock"
[Homebridge] [3/21/2020, 23:17:51] Loaded plugin: "homebridge-harmonyhub-plugin"
[Homebridge] [3/21/2020, 23:17:51] Registering platform "homebridge-harmonyhub-plugin.HarmonyHub"
[Homebridge] [3/21/2020, 23:17:51] Loaded plugin: "homebridge-securitysystem"
[Homebridge] [3/21/2020, 23:17:51] Registering accessory "homebridge-securitysystem.Security system"
[Homebridge] [3/21/2020, 23:17:51] Loaded plugin: "homebridge-webos-tv"
[Homebridge] [3/21/2020, 23:17:51] Registering accessory "homebridge-webos-tv.webostv"
[Homebridge] [3/21/2020, 23:17:52] Loaded plugin: "hue"
[Homebridge] [3/21/2020, 23:17:52] Registering platform "homebridge-hue.Hue"
[Homebridge] [3/21/2020, 23:17:52] Loading 3 platforms...
[Homebridge] [3/21/2020, 23:17:52] [homebridge-harmonyhub-plugin] Initializing HarmonyHub platform...
[Homebridge] [3/21/2020, 23:17:52] [Alexa] Initializing Alexa platform...
[Homebridge] [3/21/2020, 23:17:52] [Alexa] homebridge-alexa v0.4.56, node v12.16.1, homebridge v0.4.50
[Homebridge] [3/21/2020, 23:17:52] [Alexa] Initializing platform accessory "Alexa".
[Homebridge] [3/21/2020, 23:17:52] [Hue] Initializing Hue platform...
[Homebridge] [3/21/2020, 23:17:52] [Hue] config.json: warning: plugin_map: ignoring unknown key
[Homebridge] [3/21/2020, 23:17:52] [Hue] homebrige-hue v0.11.46, node v12.16.1, homebridge v0.4.50
[Homebridge] [3/21/2020, 23:17:52] [Hue] warning: not using recommended node version v7.0.0 LTS
[Homebridge] [3/21/2020, 23:17:52] [Hue] warning: not using recommended homebridge version v0.4.22
[Homebridge] [3/21/2020, 23:17:52] Loading 4 accessories...
[Homebridge] [3/21/2020, 23:17:52] [LG OLED TV] Initializing webostv accessory...
[Homebridge] [3/21/2020, 23:17:52] [Garage] Initializing DummyGarage accessory...
[Homebridge] [3/21/2020, 23:17:52] [Front Door] Initializing DummyLock accessory...
[Homebridge] [3/21/2020, 23:17:52] Error: The requested accessory 'SecuritySystem' was not registered by any plugin.
    at API.accessory (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:45:19)
    at Server._loadAccessories (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:258:48)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:78:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[Homebridge] [3/21/2020, 23:17:52] Got SIGTERM, shutting down service...

config.json attached with sensitive details ## out
[config.json.zip](https://github.com/MiguelRipoll23/homebridge-securitysystem/files/4364452/config.json.zip)

**Comment by MiguelRipoll23** [comment]
`Notice - [Homebridge] [3/21/2020, 23:17:51] Registering accessory "homebridge-securitysystem.Security system" has a space between Security and system, is that correct?`

It's correct.

I think I just found the issue and it's the plugin_alias defined on the accessories schema file, try uninstalling and installing the latest version I just released (v2.1.1) :)

**Comment by Jbb08** [comment]
Thanks for all you hard work Miguel,

Were not quite there, so your fix, did solve all issues, except its introduced a new one.
Fixed - 
Install works, no error, persist seems to work.

However, when the plugin is installed, you are presented with the config screen, where you click Add Accessory, that will normally open the configuration screen with all the options, instead it seems to do nothing.
However upon checking the config.json, each time that add accessory button is pressed a default accessory is added to the config.json, (I had 5) 

So the button is not working...
I manually removed 4 of the 5 of mine, and filled it out manually,
However my configuration is not showing against the plugin UI like normal.
<img width="1571" alt="Screenshot 2020-03-22 at 00 24 13" src="https://user-images.githubusercontent.com/48804661/77239512-92991980-6bd3-11ea-8052-8559894660ac.png">

**Comment by Jbb08** [comment]
Ok a HOOBS restart has it all back. SORRY
So I think its all fixed Miguel, check your Paypal account :)

<img width="1621" alt="Screenshot 2020-03-22 at 00 30 53" src="https://user-images.githubusercontent.com/48804661/77239596-692cbd80-6bd4-11ea-85fb-fd87dea42c33.png">

**Comment by MiguelRipoll23** [comment]
Glad we fixed it, thanks for betatesting and the donation! 😃

**Comment by Jbb08** [comment]
Thank you so much, to have a talented developer so active and ready to support and actually make immediate changes is such a great thing, you deserve more donations!

I can also confirm your change has fixed the display of your plugin, now all I can suggest you do is submit it for review by HOOBS to become a certified plugin (first in gets the only spot)

Thanks again, much appreciated.

<img width="1305" alt="Screenshot 2020-03-22 at 00 38 56" src="https://user-images.githubusercontent.com/48804661/77239715-caa15c00-6bd5-11ea-87f7-659637238191.png">

**Comment by Jbb08** [comment]
Miguel you can close this issue now if you like :)

**Comment by MiguelRipoll23** [comment]
Thanks, I just created a HOOBS label to track these issues much better 👍

**Comment by Jbb08** [comment]
> Thanks, I just created a HOOBS label to track these issues much better 👍

Great Idea :)
I am putting together a DIY Homekit Security Centre following this awesome Youtuber's Automation advice.
Just working out if the conditioning in EVE app can use this Plugin as one of the conditions, or should I also enable the Siren dummy switch too?
https://shanewhatley.com/2019/11/10/diy-homekit-security-alarm-system/

**Comment by MiguelRipoll23** [comment]
It definitely can! The siren switch is completely optional.

You will see some custom characteristics available on the Eve app to trigger the security system or do an action depending on which mode is selected.

The Eve app is 100% recommended for this plugin, it’s a very powerful app.

**Comment by Jbb08** [comment]
Hey @MiguelRipoll23 I am back :)
It seems updating to 2.3.0 has lost HOOBS configuration.
Manually changing config to accessory - security-system seems to not link to the configuration in the interface again...
Fix one or two things for this to come back :(
<img width="1382" alt="Screenshot 2020-04-18 at 22 46 43" src="https://user-images.githubusercontent.com/48804661/79672064-9a45e100-81c6-11ea-8f44-e95701aa8121.png">

**Comment by MiguelRipoll23** [comment]
Sorry! This is probably the breaking change coming from the 2.2.1 version. Can you try to reinstall the plugin or update the ~/.hoobs/etc/config.json file?

Change "Security system" to "security-system" as the plugin alias has been changed. This was done to improve the readability on the configuration as the name option had the same value.

**Comment by Jbb08** [comment]
Hi no worries.
So I removed the plugin, then re-installed it.
The accessory configuration showed, I filled it in and saved it.
However HOOBS would not start homebridge.


[Homebridge] [4/18/2020, 23:10:52] Error: The requested accessory "Security system" was not registered by any plugin.
    at API.accessory (/home/hoobs/.hoobs/lib/bridge/api.js:68:19)
    at Server._loadAccessories (/home/hoobs/.hoobs/lib/bridge/server.js:268:48)
    at Server.run (/home/hoobs/.hoobs/lib/bridge/server.js:97:14)
    at module.exports (/home/hoobs/.hoobs/lib/bridge/cli.js:74:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/lib/bridge/bin/homebridge:27:59)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
[Homebridge] [4/18/2020, 23:10:52] Got SIGTERM, shutting down Homebridge...

I knew straight away it is because the plugin did not correct its accessory name Security system to security-system

I went to the config.json (Advanced) and changed it. It fixed the plugin and it works, however the accessory config screen in the plugin is gone... as per my screen shot above.

I think your alias is not mapping or something, as HOOBS can't link the config and the plugin oddly...

**Comment by MiguelRipoll23** [comment]
I just released a new version to the stable channel, can you verify if it works now? Unfortunately I can't test it on Windows 😢

**Comment by Jbb08** [comment]
Updated thank you :)
2.4.1 installed now, however the Add Accessory Button does not open up the configuration screen.
However each press of the button does nothing, but it does keep adding an empty config to the main config.json.
I have had this in the past as mentioned above in this thread, so I rebooted the Raspberry Pi4 and viola it works like it should again.
Not sure why that happens but, perhaps HOOBS users need to do a full reboot after installing your plugin, then they can configure the config (even though the normal process would be to configure it before saving the Config during installation)

**Comment by MiguelRipoll23** [comment]
That's great!

Schema configuration changes on HOOBS are way more difficult due to how it handles changes, fortunately that was the only breaking change needed. I had to improve some areas from the plugin this last two weeks so adding features would be even easier :)
