### ISSUE TITLE
audio problem

### ISSUE THREAD

**Issue by clint80** [MiguelRipoll23/homebridge-securitysystem#200]
### Plugin version

6.2.1

### Plugin configuration

 {
            "name": "André Gide",
            "default_mode": "Off",
            "arm_seconds": 0,
            "trigger_seconds": 0,
            "reset_minutes": 10,
            "save_state": false,
            "proxy_mode": false,
            "test_mode": false,
            "log_directory": "/homebridge/node_modules/homebridge-securitysystem/journal",
            "override_off": true,
            "reset_off_flow": false,
            "double_knock": false,
            "double_knock_seconds": 90,
            "double_knock_modes": [
                "Away"
            ],
            "tripped_sensor": false,
            "tripped_sensor_seconds": 5,
            "siren_sensor": false,
            "siren_sensor_seconds": 5,
            "reset_sensor": false,
            "mode_switches": true,
            "mode_off_switch": false,
            "mode_away_extended_switch": false,
            "mode_pause_switch": false,
            "pause_minutes": 0,
            "arming_lock_switch": true,
            "arming_lock_switches": false,
            "siren_switch": true,
            "siren_override_switch": false,
            "siren_mode_switches": false,
            "audio_switch": true,
            "audio": true,
            "audio_language": "en-US",
            "audio_path": "/homebridge/node_modules/homebridge-securitysystem/src/sounds/fr-FR",
            "audio_volume": "100",
            "audio_arming_looped": false,
            "audio_alert_looped": false,
            "accessory": "security-system"
        },
        {

### Homebridge version

1.4.0

### What's your question?

Hello
I read all the requests and I did not find the solution.
I have a Raspberry PI4 4GB with SSD 256 g
I installed portainer and create a battery with Homebridge's docker-compose
In SSH on Raspberry by throwing the command (ffplay -loglevel error -nodisp -i /homebridge/node_modules/homebridge-securitysystem/src/sounds/en-fr/en-us/current-night.mp3 -autoexit -volume 100), the sound is ok
When I open the Homebridge terminal I must launch the command (SDL_AudioDriver = "ALSA" AudiodeV = "HW: 0,0") then (FFPlay -Loglevel Error -Nodisp -I / Homebridge / Node_Modules / Homebridge-SecuritySystem / SRC / SOUNDS / FR-EN / EN-US / CURRENT-NIGHT.MP3 -Autoexit -Volume 100), the sound is OK
I reopen the terminal and launches the command (ffplay -loglevel error -nodisp -i /homebridge/node_modules/homebridge-securitysystem/src/sounds/en-fr/en-us/current-night.mp3 -autoexit -volume 100), No sound, I have to retape (SDL_AudioDriver = "ALSA" AudiodeV = "HW: 0.0") and then the command (FFPlay ....) to hear the sound
In Homebridge Debug I have the order (Ffplay that appears) but no sound.

[1/29/2022, 3:42:59 PM] [André Gide] Target mode (Night)
[1/29/2022, 3:42:59 PM] [André Gide] Command option for target mode is not set.
[1/29/2022, 3:42:59 PM] [André Gide] Webhook base URL option is not set.
[1/29/2022, 3:42:59 PM] [André Gide] Current mode (Night)
[1/29/2022, 3:42:59 PM] [André Gide] Command option for current mode is not set.
[1/29/2022, 3:42:59 PM] [André Gide] Webhook base URL option is not set.
[1/29/2022, 3:42:59 PM] [André Gide] ffplay -loglevel error -nodisp -i /homebridge/node_modules/homebridge-securitysystem/src/sounds/fr-FR/en-US/current-night.mp3 -autoexit -volume 100
[1/29/2022, 3:43:04 PM] [André Gide] Target mode (Off)
[1/29/2022, 3:43:04 PM] [André Gide] Command option for target mode is not set.
[1/29/2022, 3:43:04 PM] [André Gide] Webhook base URL option is not set.
[1/29/2022, 3:43:04 PM] [André Gide] Current mode (Off)
[1/29/2022, 3:43:04 PM] [André Gide] Command option for current mode is not set.
[1/29/2022, 3:43:04 PM] [André Gide] Webhook base URL option is not set.
[1/29/2022, 3:43:04 PM] [André Gide] ffplay -loglevel error -nodisp -i /homebridge/node_modules/homebridge-securitysystem/src/sounds/fr-FR/en-US/current-off.mp3 -autoexit -volume 100

a big thank you for your plugin that works really well

while waiting for your reply

**Comment by MiguelRipoll23** [comment]
Hey there,

If you write the command that sets the audio driver and audio device inside your ~/.bashrc does the plugin play the sound afterwards?

It should execute the command when the plugin spawns a terminal and then execute the ffplay command.

Sorry for not being much of help, audio on Linux is quite complicated. Hope it works.

**Comment by clint80** [comment]
bonjour et merci de me répondre
j'ai ecrit les 2 lignes de commande a la fin du fichier ~/.bashrc mais ca ne change rien .
j'ai essayé la commande ( SDL_AUDIODRIVER="alsa" AUDIODEV="hw:0,0" ffplay -loglevel error -nodisp -i /homebridge/node_modules/homebridge-secur
itysystem/src/sounds/fr-FR/current-night.mp3 -autoexit -volume 100 ) dans le terminal de homebridge et cela fonctionne . Pouvez-vous l'écrire directement dans le programme pour qu'il se lance avec les mises en marche de l'alarme 
merci

**Comment by clint80** [comment]
sorry i forgot to translate it
hello and thank you for answering me
I wrote the 2 command lines at the end of the ~/.bashrc file but it doesn't change anything.
I tried the command ( SDL_AUDIODRIVER="alsa" AUDIODEV="hw:0,0" ffplay -loglevel error -nodisp -i /homebridge/node_modules/homebridge-secur
itysystem/src/sounds/fr-FR/current-night .mp3 -autoexit -volume 100) in homebridge terminal and it works. Ask you to write it directly in the program so that it launches with the starting of the alarm
thank you

**Comment by MiguelRipoll23** [comment]
I agree, let’s move this to a feature request.
Will add it as soon as I can.

**Comment by clint80** [comment]
Hello
thank you for considering my request
I will wait for the change
thank you again for your program and your answers to the problems encountered during its operation

**Comment by MiguelRipoll23** [comment]
It's now available in the beta channel for testing:

`npm install -g homebridge-securitysystem@beta`

Thanks!

**Comment by clint80** [comment]
Hello
install beta version but still no sound when activating the alarm
thank you for all your efforts

**Comment by MiguelRipoll23** [comment]
Can you check the plugin settings, see if a new option to configure the audio appears and save?
