### ISSUE TITLE
System turns off after triggering Siren Night

### ISSUE THREAD

**Issue by AlexandreBERGIA** [MiguelRipoll23/homebridge-securitysystem#203]
### Plugin version

6.2.1

### Plugin configuration

{
    "name": "Security System",
    "default_mode": "Away",
    "arm_seconds": 0,
    "trigger_seconds": 0,
    "reset_minutes": 10,
    "save_state": true,
    "proxy_mode": false,
    "test_mode": false,
    "override_off": false,
    "reset_off_flow": true,
    "double_knock": false,
    "double_knock_seconds": 90,
    "double_knock_modes": [
        "Away"
    ],
    "tripped_sensor": false,
    "tripped_sensor_seconds": 5,
    "siren_sensor": false,
    "siren_sensor_seconds": 5,
    "reset_sensor": false,
    "mode_switches": true,
    "mode_off_switch": true,
    "mode_away_extended_switch": false,
    "mode_pause_switch": false,
    "pause_minutes": 0,
    "arming_lock_switch": false,
    "arming_lock_switches": false,
    "siren_switch": false,
    "siren_override_switch": false,
    "siren_mode_switches": true,
    "audio_switch": false,
    "audio": false,
    "audio_language": "en-US",
    "audio_volume": "100",
    "audio_arming_looped": false,
    "audio_alert_looped": false,
    "_bridge": {
        "username": "0E:66:F8:9B:CA:B6",
        "port": 43443
    },
    "accessory": "security-system"
}

### Homebridge version

1.4.0

### What happened?

I have been using that awesome plugin for a while and now I'm creating more advanced automation from HomeApp.

In my case, I have a motion sensor in the house and I want to have the security system triggering only during nighttime or when I'm away. I enabled the Siren Mode Switches and added one automation that activates the siren away and night when that sensor triggers.
The trigger works fine as the system goes to alarm mode upon triggering the sensor at night, though the system goes to off status after the sensor stops.

Interestingly after the system is off, I see the following values on the status switches
- System: Off
- Mode Off: On
- Mode Night: On <-- interesting!
- All the other modes: Off

I'll try to download the code on my raspberry and fix the issue but since I see many updates on that plugin you may be faster than me since you already know the code. Let's see who is faster!

### Relevant log output

```shell
[15/02/2022, 03:01:26] [Security System] Siren (On)
[15/02/2022, 03:01:26] [Security System] Current mode (Triggered)
[15/02/2022, 03:03:25] [Security System] Siren (Off)
[15/02/2022, 03:03:25] [Security System] Target mode (Off)
[15/02/2022, 03:03:25] [Security System] Siren (Off)
[15/02/2022, 03:03:25] [Security System] Target mode (Off)
[15/02/2022, 03:03:25] [Security System] Current mode (Off)
```

**Comment by AlexandreBERGIA** [comment]
Hi Miguel,
I completely missed the exact two minutes between the trigger and turn off that was in the logs. That matches the turn off settings from the automation that was set to 2 min.
My intention was to turn the alarm on and stop if after a while. I was expecting the system to go back to the previous state and continue monitoring (ready to turn on again).

Any particular reason to turn off the system upon turning off the alarm?

**Comment by MiguelRipoll23** [comment]
Yes, if the siren goes off I thought it would be better to switch the security system to off mode rather than reverting to the armed mode to prevent firing it off again.

> My intention was to turn the alarm on and stop if after a while

Doesn't the `Reset Delay Minutes` option fit this use case? If you set that option to two minutes, when the security system triggers it will revert back to armed mode after two minutes.

**Comment by MiguelRipoll23** [comment]
Thanks for the feedback, I tried to keep it short to fit all the options.

I can't reproduce your issue, it could be HomeKit failing to update the status.
Could you try to reproduce this issue with the latest beta on debug? You should see "Mode Away Switch (On) after the security system resets.
