### ISSUE TITLE
IFTTT 

### ISSUE THREAD

**Issue by Alecarrington23** [MiguelRipoll23/homebridge-securitysystem#204]
### Plugin version

6.2.1

### Plugin configuration

Does it work with WeBeHome (With or without API) or via IFTTT on command? 

### Homebridge version

6.2.1

### What's your question?

Does it work with WeBeHome (With or without API) or via IFTTT on command?

**Comment by MiguelRipoll23** [comment]
Hey there,

The API exposed by the plugin can't be used from outside your network unless you do port forwarding and keep synchronizing your current IP address (you may have a dynamic one which is common).

There's no compatibility to any external service beyond webhooks as this is a completely homemade plugin.
