### ISSUE TITLE
Method, body request and pattern

### ISSUE THREAD

**Issue by GevaudanBeast** [MiguelRipoll23/homebridge-securitysystem#211]
### What are you missing?

Hello,
For webhook, it's possible to add method (PUT, GET, POST) and body request with regex ?
Thank for your time.

**Comment by MiguelRipoll23** [comment]
Hey there,

The webhooks feature is intended to be basic, what you're trying to archive can be be done using the commands feature. Check the command options and execute a cURL command depending on the event.

If there's anything that I can do to improve your use case be free to suggest an improvement in this area.

**Comment by GevaudanBeast** [comment]
Hello,
Indeed, I had not thought of this possibility with cURL.
I will try, but it should work.
Is it possible to deactivate certain modes such as "home" for example (I don't need to)?
Anyway, thank you for this advice!

**Comment by GevaudanBeast** [comment]
So I tested the solution with cURL, indeed, it works very well, however, in my case, a status return would be practical, because ultimately, the homebridge plugin is not necessarily the source triggering the arming of the alarm.

**Comment by MiguelRipoll23** [comment]
Yes, you can disable modes if you want.
It's part of the plugin settings.

Because the commands are executed during an event, all you have to do is pass an string like "target_home" or "current_home" as part of parameter or argument to obtain the status on your other side 😉

**Comment by GevaudanBeast** [comment]
Thank you for that answer.
I am currently using a "push" feature of my home automation to maintain the alarm state, however, in the event of a backup of either (homebridge or my home automation) the plugin does not would only update when an arming or disarming action is performed. In addition, the target url to know the status on my home automation server returns data in json which a priori would not be interpretable by the plugin (type {"on":true} or {"on":false}).
As it is, it works, but if there's an error, there's no going back.

**Comment by MiguelRipoll23** [comment]
If I understood correctly, you want the plugin to work with the platform and viceversa, right? Interoperability being handled at plugin level isn't the best idea, way too many platforms and accessories to work with. I think this will rather be addressed by the Matter protocol that will arrive this year.

**Comment by GevaudanBeast** [comment]
@MiguelRipoll23 Ok, thanks!
