### ISSUE TITLE
Triggered audio does not stop

### ISSUE THREAD

**Issue by micahvdm** [MiguelRipoll23/homebridge-securitysystem#221]
### Plugin version

6.3.0

### Plugin configuration

"name": "Security System",
            "default_mode": "Off",
            "arm_seconds": 0,
            "trigger_seconds": 5,
            "reset_minutes": 1,
            "save_state": false,
            "proxy_mode": false,
            "test_mode": false,
            "override_off": false,
            "reset_off_flow": true,
            "double_knock": false,
            "double_knock_seconds": 90,
            "double_knock_modes": [
                "Away"
            ],
            "disabled_modes": [
                "Home"
            ],
            "tripped_sensor": true,
            "tripped_sensor_seconds": 5,
            "siren_sensor": true,
            "siren_sensor_seconds": 5,
            "reset_sensor": false,
            "mode_switches": true,
            "mode_off_switch": false,
            "mode_away_extended_switch": true,
            "mode_pause_switch": false,
            "pause_minutes": 0,
            "arming_lock_switch": false,
            "arming_lock_switches": false,
            "siren_switch": true,
            "siren_override_switch": true,
            "siren_mode_switches": true,
            "audio_switch": false,
            "audio": true,
            "audio_language": "en-US",
            "audio_configuration": "SDL_AUDIODRIVER=\"alsa\" AUDIODEV=\"hw:0,0\"",
            "audio_volume": "85",
            "audio_arming_looped": false,
            "audio_alert_looped": false,
            "_bridge": {
                "username": "0E:23:95:E7:32:9E",
                "port": 43564
            },
            "accessory": "security-system"

### Homebridge version

1.4.0

### What happened?

Set an automation to trigger siren when motion is detected. The audio triggered plays through ffmpeg, but it doesn't deactivate when turning off the alarm or the siren switch. The only way to stop it is to restart the Homebridge server.
Is there something I'm missing in the setup or is it a bug? There are no issues in the HB logs...

**Comment by MiguelRipoll23** [comment]
Hey there,

Could you provide the log output while Homebridge is in debug mode?

**Comment by micahvdm** [comment]
I will need to put homebridge back in debug to get a log. I do remember that the ffplay had the argument “-loop -l” to it and that was all. This was different to the other audio ffplay commands…will pull a log soonest and upload here.

**Comment by MiguelRipoll23** [comment]
Thank you, the loop argument is necessary to continue playing the alarm sound but it should stop when the mode is changed though!

**Comment by MiguelRipoll23** [comment]
I'm sorry, this a bug introduced in [v6.3.0](https://github.com/MiguelRipoll23/homebridge-securitysystem/releases/tag/v6.3.0).
A patch will be released soon fixing this issue, it's already available in the beta channel.

**Comment by micahvdm** [comment]
The beta update fixed it! thanks!
