### ISSUE TITLE
Feature request : new webhook and command

### ISSUE THREAD

**Issue by macjl** [MiguelRipoll23/homebridge-securitysystem#23]
Hello,

Could you add a 'command' and a 'webhook' that activate just when the sensor is triggered, without waiting the 'trigger_seconds' delay ends? The actual 'command_triggered' and 'webhook_triggered' are waiting for this delay to launch.

In my home, I will use it to play a smooth sound that will inform that the alarm have been triggered, and the person who entered have some seconds to deactivate it before real big siren sound!

**Comment by MiguelRipoll23** [comment]
That's pretty good use case!

I'm going to check out this tonight to see how I can implement it.

Thanks 👍

**Comment by MiguelRipoll23** [comment]
I just released a new beta version with this feature implemented, use the options `command_alert` and `webhook_alert` to use it.

`npm i homebridge-securitysystem@2.4.0`

I'll release this to the general public tomorrow, don't close this issue yet 😃

**Comment by MiguelRipoll23** [comment]
New stable version just released with the feature implemented.

**Comment by macjl** [comment]
Hello,

I've tested all of that today, and all working fine. Thank you!
I'll come back soon with an other improvement idea !
