### ISSUE TITLE
State of homebridge-securitysystem plugin

### ISSUE THREAD

**Issue by MiguelRipoll23** [MiguelRipoll23/homebridge-securitysystem#233]
Hey everyone,

Unfortunately I'm announcing that due to changes in my life I won't longer be maintaining this plugin. As an user myself, I know it's frustrating to see that a project has been abandoned but sometimes there's no third option.

I will accept incoming pull requests (as soon as possible) and if someone is interested to fork the project and continue maintaining the plugin I will add a notice that links to it.

Thanks for your support and help.
-Miguel

**Comment by ElphaX** [comment]
Thanks for all your hard work and effort for the community. Happy to take over, handle requests, and future updates if it makes it easier for you mate 😊 Feel free to transfer, or add me into this one 👍🏼

**Comment by MiguelRipoll23** [comment]
@ElphaX thanks for the help! I've been thinking the best way to do this:

1. Create a fork from this repository (you)
2. Publish a new package under other name or similar (you)
3. Add a note here indicating that this repository and package is not maintained anymore with a link that goes to the new maintained repository (me)

In my opinion this is the best way to indicate a new owner and prevents any malicious intents that have been happening in the npm ecosystem, is right for you?

**Comment by ElphaX** [comment]
Sounds good, ill message you. 👍🏽
