### ISSUE TITLE
Iphone notifications do not appear when alarm is set to "away"

### ISSUE THREAD

**Issue by splashibiza** [MiguelRipoll23/homebridge-securitysystem#24]
Iphone notifications do not appear informing when alarm is set to "away"

**Comment by MiguelRipoll23** [comment]
I’d need a few more re details on this to investigate further.

Are you setting the mode to “Away” manually or using an automation?

Using the Home app or other one?

Thank you.

**Comment by splashibiza** [comment]
I apologize it does work correctly , I do not receive notifications when
armed manually from Home app but do receive notifications when armed from a
switch

Congratulations on the project it is great and will enable lots of us to
make a home alarm with little cost.

Can I ask you about your setup? do you have any ideas of a homekit enabled
siren?

I have thought of wiring a 12v transformer and this siren
https://www.amazon.es/gp/product/B00CIOXU5S/ref=ox_sc_act_title_2?smid=A1WFLQU9C623A6&psc=1
to my raspberry pi relay HAT

For motions sensors I have Philips HUE motion indoor sensors in mind

By the way I guess you speak Spanish like me but probably better to write
in English so more people can read us!

**Comment by MiguelRipoll23** [comment]
Sí, hablo Español 😃

When you change the security system's mode, **only other devices you own will receive the notification** so the device that did the change won't receive anything. This is how Apple implemented it and can't be changed unfortunately. When arming from a switch it works differently so the notification is sent to the same device. 

> Congratulations on the project it is great and will enable lots of us to
> make a home alarm with little cost.

Thanks, that was the goal :)

> Can I ask you about your setup? do you have any ideas of a homekit enabled
> siren?

My setup is way too simple, I'm just using Eve Motion sensor but I do have some ideas that I can share to you:

- Use a HomeKit Secure Video camera with person detection as a trigger (not sure if possible).
- Put NFC tags at the entrance to arm/disarm the security system easily and securely. (*)
- Use an AirPlay 2 speaker like HomePod as a siren so you can customize the sound it makes, the volume... etc. (*) (**)

\* Using the Shorcuts app to create an advanced automation.
\** They are a little bit expensive 👎 

Using a real siren like the one you told me it's a great alternative.

**Comment by malmentm** [comment]
What's the correct way to add an automation that automatically arms when I leave the house and get the notifications working?

**Comment by MiguelRipoll23** [comment]
Hey @malmentm,

Enable the `Show Mode Switches` option and add an automation to turn on the switch corresponding to the mode that that you would like to set.
