### ISSUE TITLE
Status of Security System in status bar on favorit/overview page in Apple Home app is always OFF.

### ISSUE THREAD

**Issue by JayJay-Master** [MiguelRipoll23/homebridge-securitysystem#243]
### Plugin version

6.4.0 (2022-06-12)

### Plugin configuration

`        {
            "name": "Security System",
            "default_mode": "Off",
            "arm_seconds": 10,
            "trigger_seconds": 0,
            "reset_minutes": 10,
            "save_state": true,
            "proxy_mode": false,
            "test_mode": false,
            "override_off": false,
            "reset_off_flow": false,
            "double_knock": false,
            "double_knock_seconds": 90,
            "double_knock_modes": [
                "Away"
            ],
            "tripped_sensor": false,
            "tripped_sensor_seconds": 5,
            "siren_sensor": true,
            "siren_sensor_seconds": 30,
            "reset_sensor": false,
            "mode_switches": true,
            "mode_off_switch": true,
            "mode_away_extended_switch": false,
            "mode_pause_switch": true,
            "pause_minutes": 5,
            "arming_lock_switch": false,
            "arming_lock_switches": false,
            "siren_switch": true,
            "siren_override_switch": false,
            "siren_mode_switches": false,
            "audio_switch": false,
            "audio": false,
            "audio_language": "en-US",
            "audio_configuration": "SDL_AUDIODRIVER=\"alsa\" AUDIODEV=\"hw:0,0\"",
            "audio_volume": "100",
            "audio_arming_looped": false,
            "audio_alert_looped": false,
            "_bridge": {
                "username": "0E:E3:5F:F9:DB:6E",
                "port": 41528
            },
            "accessory": "security-system"
        },
`

### Homebridge version

1.4.1

### What happened?

On the Favorites or Overview page in the Apple Home app, the status of the security system in the status bar is always OFF, even though the status is AWAY. In the status bar of the room to which the security system is assigned, the correct status AWAY is displayed, so only the overview page is not synced properly.

The icon of the security system on the overview page shows the right state.

In the previous installed version state in overview page was correct.

**Comment by MiguelRipoll23** [comment]
Hello,

Please see #112 or #195.

**Comment by JayJay-Master** [comment]
Hi, 
#195 helps. Thank you.
