### ISSUE TITLE
Why audio settings are gone ?

### ISSUE THREAD

**Issue by macjl** [MiguelRipoll23/homebridge-securitysystem#244]
### Plugin version

6.4.0

### Plugin configuration

{
            "name": "Alarme",
            "default_mode": "Off",
            "arm_seconds": 60,
            "trigger_seconds": 60,
            "reset_minutes": 1,
            "save_state": true,
            "proxy_mode": false,
            "test_mode": false,
            "night_arm_seconds": 0,
            "override_off": false,
            "reset_off_flow": false,
            "double_knock": false,
            "double_knock_seconds": 90,
            "double_knock_modes": [
                "Away"
            ],
            "disabled_modes": [
                "Home"
            ],
            "tripped_sensor": false,
            "tripped_sensor_seconds": 5,
            "siren_sensor": false,
            "siren_sensor_seconds": 5,
            "reset_sensor": false,
            "mode_switches": true,
            "mode_off_switch": true,
            "mode_away_extended_switch": false,
            "mode_pause_switch": false,
            "pause_minutes": 0,
            "arming_lock_switch": true,
            "arming_lock_switches": false,
            "siren_switch": false,
            "siren_override_switch": false,
            "siren_mode_switches": true,
            "audio_switch": true,
            "audio": true,
            "audio_language": "en-US",
            "audio_path": "/homebridge/node_modules/homebridge-securitysystem/sounds",
            "audio_volume": "100",
            "audio_arming_looped": true,
            "audio_alert_looped": true,
            "server_port": 9090,
            "server_code": xxxx,
            "webhook_url": "https://api.telegram.org",
            "webhook_current_warning": "/xxx:xxx:xxx/sendMessage?chat_id=-35047930&text=Alarme%20declenche.",
            "webhook_current_triggered": "/xxx:xxx’xxx/sendMessage?chat_id=-35047930&text=Alarme%20sonne.",
            "accessory": "security-system"
        },

### Homebridge version

1.5.0

### What's your question?

Hello,

Why did audio settings disappeared in v6.4 ?
I’m not able to use audio anymore, because I don’t know how to pass env variables through homebridge-ui.

**Comment by MiguelRipoll23** [comment]
Hey there @macjl,

Are you talking about the `Audio Configuration` option that allowed to add environment variables, right?

The changes that added that option caused a serious bug during audio playback so I had to revert it. I want to find other way to allow environment variables to be passed as soon as I can.

**Comment by macjl** [comment]
Hello Miguel,

That it.
Instead of environment variables, I think there should be an ffplay option that will select the correct audio interface. With that, the bug will be gone, as you will be able to use the same method to call ffplay, without using env variable. 
I will try to search for it tomorrow.

**Comment by macjl** [comment]
Hello,

I did not find a way to pass alsa config directly to ffplay without env variables.
But I found that you can pass env variables to the process without using shell.

For example :
```
  // Process
  var ffplayEnv = process.env;
  ffplayEnv.SDL_AUDIODRIVER='alsa';
  ffplayEnv.AUDIODEV='hw:CARD=Device';
  this.audioProcess = spawn('ffplay', commandArguments, { env: ffplayEnv });
```

Does it help to bring back the audio extra settings ?

**Comment by MiguelRipoll23** [comment]
The option was using shell but when the process was killed to stop the audio only the shell was being killed not the child process (ffplay) that is playing the audio.

I'm pretty sure there's probably a way to be able to kill both the shell and the child process but I need time to look at it.

I don't recommend reverting to a previous version unless you see that the audio is able to stop successfully and the processes are killed correctly.

**Comment by macjl** [comment]
I’ve made a PR for this. it seems that the processes are killed properly with this method. Tell me if you think it can be merged.

**Comment by MiguelRipoll23** [comment]
Feature is now in the stable channel, enjoy!
