### ISSUE TITLE
iOS 16 - Labels for Switches broken 

### ISSUE THREAD

**Issue by addisonjames** [MiguelRipoll23/homebridge-securitysystem#285]
### Plugin version

6.5.1

### Plugin configuration

Basic. Armed Home mode disabled. 

### Homebridge version

1.5.0

### What happened?

When opening up "Security System" in Home.app, all the switches are now labeled "Security System" - they no longer have their individual labels, I cannot tell what each switch does. I spoke to the developer and he suggested ungrouping and regrouping, but that did not fix. Anyone else having this issue?

**Comment by robertdoleson** [comment]
I am also having this issue. Fresh install. 

As a workaround, I triggered each switch and named them in the Home app.

**Comment by benrunger** [comment]
I'm also having this issue after upgrading to iOS 16. All the mode switches are labeled "Security System" whereas before upgrading they were distinguishable ("Mode Off", "Mode Away", etc.)

**Comment by MiguelRipoll23** [comment]
I’m aware of this issue.

While I’m not quite sure if there is a fix that be done in the plugin to show them correctly as apparently Apple has updated the way it handles accessories created by a plugin I will try to investigate the issue this weekend.

If you have experienced the same issue with other plugins please let me know.

Thank you.

**Comment by MiguelRipoll23** [comment]
Looks like this a HomeKit bug or intended behavior on Apple’s side.

homebridge/homebridge#3210

**Comment by addisonjames** [comment]
@MiguelRipoll23 Thanks for that link- it explains an easy fix: "If you edit the accessory and clear the default name, the suggested name (in grey text) is the correct accessory name for that sub accessory."

**Comment by benrunger** [comment]
@addisonjames Thank you for the suggestion! I was able to separate into separate files, clear the "Security System" name to reveal the proper name in gray text, and rename to that accordingly.

**Comment by jsiegenthaler** [comment]
Hi @MiguelRipoll23 I read in other forums that Apple changed the behavior of the accessory name in iOS 16. Apple expects a ConfiguredName to exist and be populated for each accessory. Try setting both Name and ConfiguredName to the same values when the accessory is created. This might fix it for you.

**Comment by MiguelRipoll23** [comment]
@jsiegenthaler as of right now the HomeKit services defined by Homebridge don’t contain the ComfiguredName characteristic that you mention,  I’ve to research this a little bit more as maybe it’s possible somehow.

Thanks for the information!

**Comment by jsiegenthaler** [comment]
@MiguelRipoll23 Interesting. Read this: https://discord.com/channels/432663330281226270/432672072859385856
The last few posts from 10.11.2022 discuss the name vs Configured Name issues

**Comment by MiguelRipoll23** [comment]
Hello @jsiegenthaler,

The `ConfiguredNam `characteristic has been added on the beta channel, although during my testing the only way I could use the accessory names provided by the plugin was by skipping the accessory setup.

I added the following note to the README:

> During accessory setup, when asked the name of the accessories tap the close button on the upper right to exit setup and use the accessory names provided by the plugin.

Not a fan of the way it works right now, very unfriendly for new users 😢 

Thanks for the help!

**Comment by DaveEdwards97** [comment]
Hi @MiguelRipoll23,

Please can you provide configured names for the mode switches too. 

Also, I'm not sure if this has been mentioned, and if a fix can be done, but upon a restart of Homebridge, the configured name if set within the Apple Home app is lost and replaced by the current default configured names set by the plugin.

**Comment by MiguelRipoll23** [comment]
@DaveEdwards97 when the name is set using the Home app it won’t be saved by the plugin unfortunately. It should reset to the one that is set in the plugin configuration (not the default one).

Allowing Home app changes requires way too much work right now and unfortunately and I can’t work on that at the moment.

If you need name settings for the switches please open a feature request in the new issue page and I can work on it as soon as I can 🙂
