### ISSUE TITLE
SecuritySystem.playAudio- Error when Audio is enabled

### ISSUE THREAD

**Issue by robertdoleson** [MiguelRipoll23/homebridge-securitysystem#286]
I have been attempting getting audio to work but I'm running into this error. It appears every time the security state is changed and causes homebridge to crash. 

[9/13/2022, 10:35:52 AM] TypeError: Cannot read properties of undefined (reading 'forEach')
    at SecuritySystem.playAudio (/homebridge/node_modules/homebridge-securitysystem/src/index.js:1508:31)
[9/13/2022, 10:35:52 AM] Got SIGTERM, shutting down Homebridge...

The forEach command looks like it's trying to index the audio files but fails. I have attempted to set a custom audio path to work around this issue with no luck. This is a fresh docker/portainer instance.

**Comment by MiguelRipoll23** [comment]
Hey there,

Please add the following to your plugin configuration:
audio_extra_variables: [],

or create an item inside the “Audio Extra Variables” category, set any text to the key and value textbox.

It will be solved soon, this is just a workaround.

Thank you.

**Comment by robertdoleson** [comment]
Great, that did it. Thanks for the quick response.

**Comment by MiguelRipoll23** [comment]
Fix is now in the stable channel, thanks for reporting.
