### ISSUE TITLE
Add your plug-in to homebridge/verified

### ISSUE THREAD

**Issue by macjl** [MiguelRipoll23/homebridge-securitysystem#29]
Hello,

For your great plug-in have even more users, you could subscribe to :
https://github.com/homebridge/verified

I think it would be good for a plug-in that is based on security to have such a validation of homebridge team.

**Comment by MiguelRipoll23** [comment]
Plugin is already verified, I didn't add the badge yet 🙂

homebridge/verified#36

Next on my list:
- Use 2FA on npm
- Use signed commits
