### ISSUE TITLE
Is it possible to change the serial number of each security system?

### ISSUE THREAD

**Issue by Edelheid** [MiguelRipoll23/homebridge-securitysystem#290]
### Plugin version

6.5.1

### Plugin configuration

n/a

### Homebridge version

1.5.0

### What's your question?

Hi,

Currently, the serial number defaults to "S3CUR1TYSYST3M" for everything. Is there a way to apply a unique serial number for each of them via the config for example?

**Comment by MiguelRipoll23** [comment]
Hey there,

Currently, it's not possible.

May I ask what's the use case? It is resolving any bug you're experiencing?

**Comment by Edelheid** [comment]
It's something I noticed when browsing the Controller app while trying to troubleshoot a problem elsewhere. Supposedly it's good for accessories to have unique serial numbers according to it. Here's what it says:

"Each Accessory should have a unique serial number. Regrettably, many Homebridge plugins and some HomeKit Accessory manufacturers use the same serial number for all Accessories. As a result, Controller cannot tell these Accessories apart, which cause issues with custom icons, HomeKit Codes, and Backups.

For Homebridge plugins, you might be able to change the serial number in the plugin's settings. Unfortunately, for genuine HomeKit accessories, you can't change this."

**Comment by MiguelRipoll23** [comment]
Oh, I see.

Would you mind if for all accessories that are exposed by the plugin a random serial number is set?

The serial number would be static but unique given the accessory internal name.

**Comment by Edelheid** [comment]
I wouldn't mind that at all! It's already good enough that they will each have a unique serial number through that change.

**Comment by MiguelRipoll23** [comment]
It's now available in the beta channel for testing:

`npm install -g homebridge-securitysystem@beta`

An option named "Serial Number" / "serial_number"  has been added to allow multiple security system accessories.

Thanks!

**Comment by Edelheid** [comment]
Thank you so much! I've updated to 6.6.0 and saw the new "serial number" entry (using homebridge image).

Not sure if changing the serial number was going to affect my automations I tried changing one serial number first and then restarted. (I have 5 separate alarms and I changed 1 the serial number for one of them.)

Upon restarting, the said alarm had its name changed to "S3CUR1TYSYST3M" and in turn the serial number changed to "Default-SerialNumber", so it seems like the serial number was attributed to the name of the accessory and a placeholder was taken in as the serial number. Even weirder, another of my alarms (that I didn't change the serial number for) had the same thing happen to it despite me not touching it. So overall 2 out of 5 alarms was in that strange situation. I checked the config file and noticed that the alarm I didn't touch didn't have a serial number line, but the rest did. I never found out why.

A reset of all accessory cached appears to have fixed the problem. I modified the serial numbers of the rest of my alarms and this time they seem to apply without needing to reset the cache again. Strange, but I'm glad it works so far. Thank you again!

**Comment by magobaol** [comment]
I've updated just yesterday and I'm in a similar situation, even though I haven't touched the configuration of any of the alarms I have. The name "S3CUR1TYSYST3M" started to pop-up on my devices, but not all of them.
For example, my wife's phone and my MacBook show it, but my iPhone don't.

The functionality doesn't seem to be affected, though.

**Comment by MiguelRipoll23** [comment]
Bug found, I will fix it today.

Workaround for now is to set a serial number to all security systems to keep the correct name.

Sorry!

**Comment by Edelheid** [comment]
That explains it! When all the serial numbers started working I did apply serial numbers to all of my alarms. Good to know this has been replicated. Thank you for confirming magobaol and MiguelRipoll23.

**Comment by MiguelRipoll23** [comment]
Fix is now live, updating to 6.6.1 should fix it without any configuration or cache changes.
