### ISSUE TITLE
automation condition issue

### ISSUE THREAD

**Issue by Karrypto** [MiguelRipoll23/homebridge-securitysystem#3]
Hi Miguel, I tried to create a rule: door open with condition “away” and siren on (via Eve App) and also a simple automation “siren” on = “Eve Siren” on. Unfortunately without success, nothing happens. As soon as I use a condition like “away” the rule will not be executed and your siren switch will not be activated. With a simple rule like door open = siren on it works but not with the condition.

**Comment by MiguelRipoll23** [comment]
I had the exact issue with a friend with the Eve Door. I got no issues when using the Eve Motion at my home so I'm don't know exactly why the this door sensor is being ignored. Can you try to use other HomeKit app and verify if the issue persists?

I'd appreciate it so much.

**Comment by MiguelRipoll23** [comment]
@Karrypto I'm using a virtual contact sensor coded with Homebridge and it seems to works fine but it looks like it doesn't with real ones. Can you try to reproduce with the exact settings below and the plugin's latest update?

**Triggers**
Contact = No

**Conditions**
Security System State = Away Arm

**Scenes**
Siren Power -> On

**Comment by Karrypto** [comment]
I tested the rule again with the last update and it works now. Thanks !

I also noticed that I can't control the security system states via geofencing.
It would be great to arm the security system when leaving home and disarm when arriving home.
But starting from iOS 10, location based automations cannot change the status of security devices and iOS asks the user to manually confirm before running the automation. Maybe you need to create virtual switches for the individual states (arm away, arm stay...) to bypass the Homekit limitation.

**Comment by MiguelRipoll23** [comment]
Glad to know it's resolved now,

I'm one of the few people that geofencing works 99% of the time but that 1% of false positives can be quite annoying for a security system as notifications are a must.

I'm waiting for remote controls to be supported on iOS to see if more features can be added without the need to create more virtual switches and making it quite hacky on the user side, hopefully the way it would be supported make this avoidable and we can add more features that I've in mind plus yours.
