### ISSUE TITLE
Webhook and command triggering when cancelling arming + delay parameter in url not used

### ISSUE THREAD

**Issue by macjl** [MiguelRipoll23/homebridge-securitysystem#30]
**Describe the bug**
When Arming the security system with a delay, if you cancel the activation, the 'off' command is not called

**To Reproduce**
1. Arm the security system with a delay
2. Cancel by setting the security system state to off
3. The 'off' command is not called

###################
**Describe the bug**
Moreover, when the Characteristic 'Security System Arm Delay' is off, calling the server URL with 'delay=true' has no effect.

**To Reproduce**
1. Set  'Security System Arm Delay' Characteristic to OFF in Eve
2. Call the URL to activate a mode with delay=true : 
    curl http://localhost:1234/away?delay=true
3. The mode is immediately set to away, without waiting the delay.

**Comment by MiguelRipoll23** [comment]
Nice find 😲

Both fixed in latest beta:

`npm install -g homebridge-securitysystem@beta`

**Comment by macjl** [comment]
All resolved in Beta! Thanks!

**Comment by MiguelRipoll23** [comment]
New stable update released with fixes added, thanks!
