### ISSUE TITLE
Remember alarm state when homebridge reboots 

### ISSUE THREAD

**Issue by TristanBrotherton** [MiguelRipoll23/homebridge-securitysystem#308]
It would be great if the alarm state (mode) could be restored when homebridge reboots. Occasionally home ridge needs to be rebooted automatically, to free resources. When it does I lose the state of my alarm and it can be disabled.

**Comment by MiguelRipoll23** [comment]
Hello @TristanBrotherton, use the **Save Data Using System Storage** option for this.
