### ISSUE TITLE
Create an automation using the arming event as trigger

### ISSUE THREAD

**Issue by splashibiza** [MiguelRipoll23/homebridge-securitysystem#31]
Hi Miguel 
Is there any way you could add the alarm status "conectando" i guess in English it will be an "arming" option in Homekit?

I have a 10 second arm delay and would like to be able to trigger a buzzer the moment the alarm is arming ( I do this with a calling a small script via Cmdtriggerswitch  pluggin , the scrip generates 4 long beeps 4 short beeps and 1 long beeb )
At the moment I can only make the beeps start working once the alarm is "conectado" "armed" wich is not correct 

This idea is to try and copy the way a "normal" alarm works beeping during the arming period for you to know you must get out of your house quick or you will trigger the alarm

As my phone will not work with NFC tags I have  created some smart buttons thanks to rpi pluggin that are connected to wall switches near my front door ( to be able to activate / deactivate ) the alarm.

I have a script that makes a short double beep that activates when the alarm is disconnected to copy what a "normal" alarm would do

Does anyone know how to make the notifications received on your iphone when the alarm is triggered sound with a personalized continuous sound? ( this should only happen with notifications from the alarm , other notifications should remain the same ) 

![image](https://user-images.githubusercontent.com/53734931/80569921-28596d00-89fa-11ea-99fb-d9c41bc9e228.png)
![image](https://user-images.githubusercontent.com/53734931/80569940-30191180-89fa-11ea-972f-14b164f950bf.png)

**Comment by MiguelRipoll23** [comment]
This isn't possible with HomeKit as there's no trigger for the arming event but this plugins supports executing commands based on the arming and armed events like this:

```
  {
    "name": "Security system",
    "default_mode": "Home",
    "arm_seconds": 5,
    "trigger_seconds": 15,
    "siren_switch": true,
    "command_target_home": "echo beep beep beep beep", <-- Arming [Home]
    "command_current_home": "echo beeeeeeeep",  <-- Armed [Home]
    "command_triggered": "echo siren",  <-- Triggered
    "command_off": "echo off",  <-- Off
    "accessory": "security-system"
  }
```

If you need extra help I will be able to help you this weekend 🙂

**Comment by splashibiza** [comment]
Thank you! that is just what I needed!

**Comment by MiguelRipoll23** [comment]
If there’s anything that you’re missing for what you’re trying to accomplish be free to continue this issue, feature requests are well received here 🙂
