### ISSUE TITLE
Unable to set state through automation

### ISSUE THREAD

**Issue by samwhu30** [MiguelRipoll23/homebridge-securitysystem#315]
Apple doesn't let you set 'When I leave set security system to away'

Previously however, I have fixed this by setting up a dummy switch and when that turns on the the security system is changed.

With this plug in the automation doesn't change the state. Is there something else I need to configure for this or is it a bug?

**Comment by MiguelRipoll23** [comment]
Are you using the `Show Mode Switches `? These switches are provided by the plugin and they should work. If they don't, could you provide your logs in debug mode?

**Comment by samwhu30** [comment]
Ah I see! I was trying to get the actual ‘security system’ to change which I have done on Aqara devices before. Only thing is now I have 6 ‘security system buttons’ 😂 I’ve read the other issue and that looks like it can’t be fixed though.

Thanks for replying so quickly!
