### ISSUE TITLE
arming_lock_switches for "Off" setting

### ISSUE THREAD

**Issue by mgoeppl** [MiguelRipoll23/homebridge-securitysystem#319]
Hi,

it would be great if I could set the arming_lock_switches setting for the "Off" setting, thus not allowing a disarmament of the system. Is this possible? Or did I not see the proper setting for a switch that does this?

Thanks!

**Comment by MiguelRipoll23** [comment]
Hello,

I’m not sure which setting you refer to, could you give please the correct name or the text from the UI.

Thank you and happy holidays.

**Comment by mgoeppl** [comment]
Hi,

I meant the "Set Arming Lock Mode Switches (beta)" setting. It does not provide a switch allowing me to lock the "Off" setting in Home. I would like to use the feature to disable the "Off" setting in home, thus preventing the complete disarmament of the security system. 

Another possibility would be a switch to "lock" the system in its current state. Is this possible?

**Comment by MiguelRipoll23** [comment]
While it would be possible I’m worried about Apple heavily discouraging the use of accessory errors to cancel an action made by the Home app by making breaking changes in future iOS versions.

Right now the plugin makes use of HomeKi-controlled errors either to cancel or revert an action but these may be problematic someday. The setting that you mention will have the beta tag removed and a warning indicating the above said to avoid possible issues.

**Comment by MiguelRipoll23** [comment]
Currently no more features are planned, leaving this issue open to see if others find it useful.
