### ISSUE TITLE
Updated documentation?

### ISSUE THREAD

**Issue by rvaneeuwijk** [MiguelRipoll23/homebridge-securitysystem#327]
### Plugin version

6.6.2

### Plugin configuration

   "accessories": [
        {
            "name": "Home Security Mode Switch",
            "arm_seconds": 0,
            "trigger_seconds": 30,
            "reset_minutes": 10,
            "home_arm_seconds": "null",
            "night_arm_seconds": "null",
            "away_arm_seconds": "30",
            "home_trigger_seconds": "null",
            "night_trigger_seconds": "null",
            "away_trigger_seconds": "null",
            "away_extended_trigger_seconds": "null",
            "double_knock_seconds": 90,
            "home_double_knock_seconds": "null",
            "away_double_knock_seconds": "null",
            "night_double_knock_seconds": "null",
            "disabled_modes": [
                "Night"
            ],
            "tripped_sensor_seconds": 5,
            "siren_sensor_seconds": 5,
            "pause_minutes": 0,
            "siren_switch": true,
            "audio_volume": 100,
            "accessory": "security-system",
            "plugin_map": {
                "plugin_name": "homebridge-securitysystem"
            }
        },

### Homebridge version

1.5.0

### What's your question?

Can you update the documentation on the configuration options? I am trying to configure it via HOOBS and am running into several issues (more switches than I think I asked for in the configuration, trigger delay not working). Before I report these as issues - I want to be respectful of your time -, I want to make sure that I have configured the plugin correctly. Currently that is hard to determine as there are many more fields in the configuration than in the accompanying documentation. Example: The documentation on HOOBS mentions a field called "trigger_seconds". The actual configuration GUI doesn't show this field, but it does show several fields with similar names: "Trigger Delay Seconds", "Home Trigger Seconds", "Night Trigger Seconds", and "Away Trigger Seconds". Which one should I use to delay the sounding of the alarm by 30 seconds after the system is triggered? This is just one of multiple examples of missing/inconsistent documentation. Thank you in advance!

**Comment by MiguelRipoll23** [comment]
Hey there!

The documentation from the HOOBS's README is outdated and unfortunately as far as I know I don't have control over it to update it, the prefer method to understand all the possible options is the configuration GUI.

In order to delay the sounding of the alarm by 30 seconds you need to the the following:

1. Set `Trigger Delay Seconds` to 30
2. Create an automation that turns on the `Siren` switch using a motion or door sensor
3. Create another automation that runs when the `Security System` accessory triggers that does whatever you need to do when the security system is triggered (turn on all lights for example)

Maybe the reason that you think the delay isn't working is due to you using the `Siren` switch for your automation, this switch is only used to trip the security system (sorry, not the best name).

Hopefully that's the case, happy new year :)

**Comment by Olivierbkk** [comment]
Hi, I see in a commit that you changed the name of siren switches to trip switches. If I install the latest update will it cancel all my automation in the home app related to these switches or the name change will not affect anything?

**Comment by MiguelRipoll23** [comment]
The internal name is still the original so there should be no affection at all, it's considered a major version due to a breaking change for the people using the server functionality.

Right now that change is part of the beta channel, it will reach the stable channel soon.

**Comment by rvaneeuwijk** [comment]
Hi Miguel,

Thanks for your quick reply. And happy New Year to you too.

Regarding documentation generally: It's not just that the documentation on HOOBS seems outdated. The documentation that I have been able to find elsewhere (e.g. here in GitHub) seems outdated too. Many fields that are not defined.

Anyway, I believe that I am triggering the security system accessory in the way you specify: sensor switches on a Siren Switch which triggers the Security System accessory. This is my set-up:

**Configuration File**
Please refer to my original message in this thread to see the configuration file for the Home Security Mode Switch (my name for your Security System accessory). I have specified away_arm_seconds = 30 and this works as expected. I have also specified trigger_seconds = 30, which doesn't work as expected. Finally, I have specified siren_switch = true. I would expect that this leads to a single siren_switch in the Apple Home app, but I end up with three. As they all have the same name, I have identified which of these is the siren_switch for the home mode, away mode, and any mode through trial and error. See attached screenshot of the Apple Home app screen for my implementation of the Home Security Mode Switch. Note: I also have a second instance for my Garage, which shows in the screenshot, but I am not working on that one right now, so please ignore.

**Automations**
I have automations that switch the Security Alert Switch (my name for your siren_switch) on when certain security events (e.g. a door unlocking) occur when the security system is armed (away and/or home). For testing purposes, I have disabled all of them except the automation on the front door. See attached screenshot of this automation.

Next, I have an automation that sets the Security Alert On scene (this sounds an alert sound through my HomePod Minis) when the Security Alert switch is switched on. See attached screenshot. 

Finally, I have an automation that sets the Security Alert Off scene (this stops the alert sound) and the Security Alarm On scene (this sounds an alarm sound through my HomePod Minis) when the Home Security Mode Switch is triggered, which I expect to happen 30 seconds after the Security Alert switch is switched on given the trigger_delay is set to 30 seconds. See attached screenshot. 

I have reviewed all my other automations to make sure that they don't switch on the Security Alert switch.

**Operation**
I attach a screen recording that shows how the security system operates when triggered. As you can see, there is no 30 second delay between the Home Security Alert switch switching on and the Home Security Mode switch being triggered. In fact, it looks like the latter triggers slightly before the former switches on. This makes no logical sense and I assume it has to do with communication delays in HomeKit.

**Question**
So my questions to you are:

1. Given the configuration file, would you expect there to be a 30 second delay between the siren_switch switching on and the security_system accessory being triggered?
2. Given the configuration file, how many switches (in addition to the security_system accessory) would you expect to appear in Apple Home?
3. Are my automations triggering the security_system accessory in the way that your plugin expects?
4. Any idea what might be causing the unexpected behaviour? Any suggestions on how to identify the root cause of the unexpected behaviour?

Thanks,

Remco

https://user-images.githubusercontent.com/121703987/210609649-434b63bb-ea26-4d4a-b6cf-347d86e9e872.mov

<img width="1066" alt="Home App Security System Setup" src="https://user-images.githubusercontent.com/121703987/210609677-69025781-6b43-4f31-b661-ecc89bd896b6.png">
<img width="741" alt="Automation to switch Siren on" src="https://user-images.githubusercontent.com/121703987/210609679-be4280ff-bf42-467c-8f5a-4a5fa718bb9b.png">
<img width="716" alt="Automation when Security System is triggered" src="https://user-images.githubusercontent.com/121703987/210609680-75c3c6c6-3ee1-4817-9f60-0ce3400d8ae1.png">
<img width="728" alt="Automation when Siren is switched on" src="https://user-images.githubusercontent.com/121703987/210609683-76771fad-d52b-4709-8239-78be90c00cda.png">

**Comment by MiguelRipoll23** [comment]
Oh, I see the problem now after debugging with your configuration.

>  The documentation that I have been able to find elsewhere (e.g. here in GitHub) seems outdated too.

Check the `config.schema.json` file in the repository root directory to find all the possible options with the description and possible values. It's used to display the settings UI for both Homebridge and HOOBS.

> Given the configuration file, would you expect there to be a 30 second delay between the siren_switch switching on and the security_system accessory being triggered?

The `Security Alert Switch` should turn on instantly and the `Home Security Mode Switch` state should change to `Triggered` after 30 seconds, however the settings `home_trigger_seconds` and `away_trigger_seconds` override the global `trigger_seconds`.

As I see from your configuren they are set to "null" instead of null without the double quotes, this is a bug that will be solved in the next stable update! 😵‍💫 

Set them to null (without the double quotes) to fix the issue.

> Given the configuration file, how many switches (in addition to the security_system accessory) would you expect to appear in Apple Home?

The siren mode switches are shown by default, as your configuration specifies that the global siren switch should be displayed as well and the night mode is disabled you should see 3 switches (global, home and away). In order to disable the mode ones you should untick `Show Mode Switches` or add the setting `siren_mode_switches` with the value `false` on your configuration file.

> Are my automations triggering the security_system accessory in the way that your plugin expects?

Yup, they look good.
I misunderstood initially due to this wild bug.

> Any idea what might be causing the unexpected behaviour? Any suggestions on how to identify the root cause of the unexpected behaviour?

I will add better handling for invalid option values in the next update so you should see a warning in your log.

Thanks for the bug report!

**Comment by MiguelRipoll23** [comment]
Fix is now in the stable channel, thanks for reporting.

**Comment by rvaneeuwijk** [comment]
Thanks Miguel. Really appreciate the quick reply and action. Update of my findings:

- Setting siren_mode_switches to false in the config file works: I only have one siren switch now.
- Changing home_trigger_seconds = "null" and away_trigger_seconds = "null" to home_trigger_seconds = null and away_trigger_seconds = null doesn't work via HOOBS at least. When I make the change and hit save, these two lines first disappear. But when I go back into the configuration, the two lines are back with value "null". 
- Documentation: Thanks for pointing out the config.schema.json file. Doesn't have definitions for all fields either, though. But not a big issue as the cause of the problem at hand is not a misunderstanding of the config fields.
- Not sure what to do with your "fix is now in the stable channel". I am just a simple HOOBS fellow as I am new to this whole homebridge magic. Is there a way to get this fix installed via HOOBS?

**Comment by MiguelRipoll23** [comment]
I mean that once HOOBS notifies you that an update is available you should be able to update and fix the issues you're experiencing.

Instead of using null set it to 30, that will finally do as a workaround 😄

**Comment by rvaneeuwijk** [comment]
Installed version 7.0.0 via HOOBS now and made sure to set trigger_seconds, home_trigger_seconds, and away_trigger_seconds all to 30. But when I trip the security system in Apple Home, there is still no delay between the trip switching on and the security system accessory being triggered.

One change I did see after installing 7.0.0 is that the siren_switch is now called "Trip" rather than "Security System". Good change! Thanks.

**Comment by MiguelRipoll23** [comment]
Try a full restart just in case, sometimes configuration gets cached. If that doesn't work please paste your current configuration here.

Thanks!

**Comment by rvaneeuwijk** [comment]
Cleared the cache and restarted HOOBS. Still no trigger delay, I am afraid. But then I decided to delete the second instance of the security system (for my garage) and give it another try. And now I do get the trigger delay! So, problem solved, at least for now. I will first get the security system working as I want for my home. Once that's done, I will add the garage again and see what happens. Thank you for your help so far!
