### ISSUE TITLE
HTTP POST requests

### ISSUE THREAD

**Issue by Edsonytic** [MiguelRipoll23/homebridge-securitysystem#33]
Hello

I have a device which can start making sounds if it receives an JSON-encoded http POST request with the appropriate command.

As far as I can tell your plugin only makes GET requests, therefore I would like to suggest adding the possibility of making POST calls.

If there is anything I can do to help achieve this please do tell.

**Comment by MiguelRipoll23** [comment]
Have tou tried the command options:

`command_triggered`
`command_current_home`
`command_current_night`
`command_current_away`
`command_off`

With something like this?

```
curl -H “Accept: application/json” -H “Content-type: application/json” -X POST -d ‘{“something”: true}’ http://localhost/path
```

That should do the trick 🙂

**Comment by Edsonytic** [comment]
Thank you for the suggestion, it did end up working but with a different syntax.

`curl -d '{\"key\":\"content\"}' -H \"Content-Type: application/json\" -X POST http://device`

**Comment by MiguelRipoll23** [comment]
That’s great.

If you prefer to use the webhooks feature anyways, keep this issue open and describe as much as you can of your use case.

An example of the request needed would be quite helpful too!

Thank you.
