### ISSUE TITLE
Trip switches not working any more with the latest version

### ISSUE THREAD

**Issue by Olivierbkk** [MiguelRipoll23/homebridge-securitysystem#344]
### Plugin version

7.0.0

### Plugin configuration

    "accessories": [
        {
            "name": "Security System",
            "serial_number": "S3CUR1TYSYST3M",
            "default_mode": "Off",
            "arm_seconds": 0,
            "trigger_seconds": 0,
            "reset_minutes": 10,
            "save_state": true,
            "proxy_mode": false,
            "test_mode": false,
            "override_off": false,
            "reset_off_flow": true,
            "double_knock": false,
            "double_knock_seconds": 90,
            "double_knock_modes": [
                "Away"
            ],
            "disabled_modes": [
                "Home"
            ],
            "tripped_sensor": false,
            "tripped_sensor_seconds": 3,
            "siren_sensor": false,
            "siren_sensor_seconds": 2,
            "reset_sensor": false,
            "mode_switches": false,
            "mode_off_switch": false,
            "mode_away_extended_switch": false,
            "mode_pause_switch": false,
            "pause_minutes": 0,
            "arming_lock_switch": false,
            "arming_lock_switches": false,
            "siren_switch": false,
            "siren_override_switch": false,
            "siren_mode_switches": true,
            "audio_switch": false,
            "audio": false,
            "audio_language": "en-US",
            "audio_volume": "100",
            "audio_arming_looped": false,
            "audio_alert_looped": false,
            "accessory": "security-system"
        },

### Homebridge version

1.6.0

### What happened?

After updating I had to redo the automations linked to the `trip` switches (which were `siren` switches before).

Now the `trip away` and `trip night` switches show `no response` and are not triggered by automations any more, they can still be tripped manually and the alarms are triggered accordingly though.

I also noticed that the security system is automaticly set to `off` when the trip switches are turned off, I do not remember it was the case before.
![Screen Shot 2023-01-07 at 14 51 54](https://user-images.githubusercontent.com/113991249/211140216-3c8f22a2-030c-4f54-9da3-a04773d9e442.png)

**Comment by Olivierbkk** [comment]
tried removing the mode trop switches and using the global trip switch and it's the same problem
came back to using only the mode trip switches and still the same

**Comment by Olivierbkk** [comment]
ok after I changed the serial number and redone all automations it works again

**Comment by Olivierbkk** [comment]
it works but the trip switches are still showing no response

![image](https://user-images.githubusercontent.com/113991249/211143007-613ec6f7-cfd9-43fc-a2a6-968ee97d2b0c.png)

**Comment by MiguelRipoll23** [comment]
Hi @Olivierbkk,

Sorry you had to redo all your automations.

I can't reproduce the issue you are facing with your configuration, can you do the following in order to determine the issue?

- On the Home app, ungroup all the accessories from the security system using the option provided in settings.
- Paste the log coming from the plugin in here while triggering any of your automations, if the log doesn't provide enough messages try running Homebridge in debug mode.

Thanks!

**Comment by Olivierbkk** [comment]
hello Miguel,

see attached log in debug mode (I have deleted everything else not related here)

sorry I forgot to ungroup the trip switches in the home app but it does not make a difference in terms of showing "no response", I hope it's OK

in the log, I triggered a few times the away and night trip switches with the serurity system turned off, then set the security system to night and manually tripped the night trip switch.

Note that it seems to be all working fine, the alarm is properly triggered by automations, the only thing is that the trip switches show "no response"

hope this helps...

[homebridge.log.txt](https://github.com/MiguelRipoll23/homebridge-securitysystem/files/10367763/homebridge.log.txt)

**Comment by MiguelRipoll23** [comment]
Seeing the logs, it looks like your automation turns on the trip mode switches no matter which mode is set. That's fine but will result in a no response error that can be ignored.

In order to avoid this no response error you can add as a condition if the mode required is set.
