### ISSUE TITLE
Name of Siren Switch (Trip)

### ISSUE THREAD

**Issue by rvaneeuwijk** [MiguelRipoll23/homebridge-securitysystem#345]
Hi. Me again. I have two instances of the security system: Home and Garage. I want one Siren Switch, which you have recently renamed Trip, for each security system. To distinguish between the two Siren Switches, I have renamed them (Home Security Trigger, Garage Security Trigger). However, these names keep on getting overwritten every time the bridge is restarted, so that I end up with two Siren Switched called "Trip" again. Is there a way to have the names I want persist? Or at least give the Siren Switch a unique name based on the name of the Security System? Thanks, Remco

**Comment by MiguelRipoll23** [comment]
Hi @rvaneeuwijk,

I was unaware of this behavior, it looks like I get notified when the name is changed and I do have to save it to disk.

I will add this in the next release, unfortunately there's no workaround for it meanwhile. If it's causing trouble you can revert back to the previous version.

Thanks!

**Comment by MiguelRipoll23** [comment]
Update plugin to the new version available, a new section called "Accessory Names" has been added to the plugin settings.
Thanks for the feedback.
