### ISSUE TITLE
Second Security System accessory overrides settings on first security system

### ISSUE THREAD

**Issue by rvaneeuwijk** [MiguelRipoll23/homebridge-securitysystem#346]
### Plugin version

7.0.0

### Plugin configuration

{
    "accessories": [
        {
            "name": "Home Security Mode",
            "arm_seconds": 0,
            "trigger_seconds": 30,
            "reset_minutes": 10,
            "home_arm_seconds": "null",
            "night_arm_seconds": "null",
            "away_arm_seconds": 30,
            "away_extended_trigger_seconds": "null",
            "double_knock_seconds": 90,
            "home_double_knock_seconds": "null",
            "away_double_knock_seconds": "null",
            "night_double_knock_seconds": "null",
            "disabled_modes": [
                "Night"
            ],
            "tripped_sensor_seconds": 5,
            "siren_sensor_seconds": 5,
            "pause_minutes": 0,
            "siren_mode_switches": false,
            "siren_switch": true,
            "audio_volume": 100,
            "accessory": "security-system",
            "plugin_map": {
                "plugin_name": "homebridge-securitysystem"
            },
            "home_trigger_seconds": 30,
            "night_trigger_seconds": "null",
            "away_trigger_seconds": 30
        },
        {
            "name": "Garage Security Mode",
            "arm_seconds": 0,
            "trigger_seconds": 30,
            "reset_minutes": 10,
            "home_arm_seconds": "null",
            "night_arm_seconds": "null",
            "away_arm_seconds": 0,
            "home_trigger_seconds": "null",
            "night_trigger_seconds": "null",
            "away_trigger_seconds": 30,
            "away_extended_trigger_seconds": "null",
            "double_knock_seconds": 90,
            "home_double_knock_seconds": "null",
            "away_double_knock_seconds": "null",
            "night_double_knock_seconds": "null",
            "disabled_modes": [
                "Home",
                "Night"
            ],
            "tripped_sensor_seconds": 5,
            "siren_sensor_seconds": 5,
            "pause_minutes": 0,
            "siren_mode_switches": false,
            "siren_switch": true,
            "audio_volume": 100,
            "accessory": "security-system",
            "plugin_map": {
                "plugin_name": "homebridge-securitysystem"
            }
        }
    ]
}

### Homebridge version

1.5.0

### What happened?

All was working fine when my configuration file contained only the first security system accessory, called "Home Security Mode". Specifically, the 30 second delay on arming the away mode was working. I then added the second security system accessory, called "Garage Security Mode", with a 0 second delay on arming. But then the 30 second delay on arming the away mode for "Home Security Mode" disappeared. I have fixed it temporarily by also specifying a 30 second arming delay for "Garage Security Mode", which indeed leads to a 30 second arming delay on both instances of the security system accessory. So it appears to me that the away_arming_seconds setting from the last instance in the config file is used to determine the away_arming_seconds setting for ALL instances in the config file. This may very well apply to other parameters as well: I only tested the away_arming_seconds setting.

### Relevant log output

```bash
Not relevant, I think.
```

**Comment by MiguelRipoll23** [comment]
Some people have experienced similar issues and tried to recreate the second accessory, can you try that maybe? If that doesn't work, check if child bridges is an option if you are using Homebridge.

**Comment by MiguelRipoll23** [comment]
Nevermind, I'm reproducing the same issue.
Will try to investigate although it seems more related with Homebridge itself.

**Comment by MiguelRipoll23** [comment]
If you are using Homebridge I recommend you to use a child bridge to isolate one instance of the other. This plugin exposes an accessory  instead of a platform so all the sub-accessories exposed by the plugin will follow during location changes. Sorry, that's the only workaround possible to prevent this from happening.

**Comment by rvaneeuwijk** [comment]
I have recently installed a second version of the plug-in on a separate bridge and plan to test soon whether this solves the issue as expected. Thanks!
