### ISSUE TITLE
Home name resets

### ISSUE THREAD

**Issue by Christian-CFP** [MiguelRipoll23/homebridge-securitysystem#363]
### Plugin version

7.1.0

### Plugin configuration

"name": "Sicherheitssystem",

### Homebridge version

1.5.0 and 1.6.0

### What happened?

Since 7.1.0 the name in home changes constantly back to ‚Security System‘ after reboot, eventough it is set to ‚Sicherheitssystem‘ (german) in the config.

Renaming in home stays just until reboot Homebridge/Hoobs.

**Comment by MiguelRipoll23** [comment]
Hey there,
Under the **Accessory Names** section from the plugin settings, set your preferred name to the security system. This is intended behavior due to iOS 16 changes.

**Comment by Christian-CFP** [comment]
Jup that's what I did since the beginning. It's still 'Sicherheitssystem' even there.

**Comment by Christian-CFP** [comment]
I don't know where the home app gets this name from because everywhere it is set to 'Sicherheitssystem'. Nowhere it says 'Security System'. Hidden in the code maybe?

**Comment by MiguelRipoll23** [comment]
I can't reproduce the issue, do you see the same behavior using Homebridge web UI? If you go to the Accessories tab you should see the security system accessory with the correct name and if you click the gear icon that appears on hover the characteristic Configured Name should appear with the name set as well.

**Comment by Christian-CFP** [comment]
Here after reboot:

gear icon
![Bildschirmfoto 2023-03-01 um 19 47 26](https://user-images.githubusercontent.com/39855486/222236438-9c716448-920d-4cd3-8b47-02d5d2f406cc.jpg)

settings
![Bildschirmfoto 2023-03-01 um 19 47 54](https://user-images.githubusercontent.com/39855486/222236506-0a7cc195-cc73-4460-95a2-df8d054ec0cb.jpg)

homekit
![IMG_CFA15872D92E-1](https://user-images.githubusercontent.com/39855486/222236609-99cda0fa-8104-4de3-8692-902b4368db05.jpeg)

**Comment by Christian-CFP** [comment]
And config
![Bildschirmfoto 2023-03-01 um 19 56 11](https://user-images.githubusercontent.com/39855486/222237622-14c754b5-ed63-4226-9eae-feb3ac314ea4.jpg)

**Comment by Christian-CFP** [comment]
PS: I am on the "new" homekit architecture since 16.2 (i guess) now on iOS 16.4 beta 2.

**Comment by MiguelRipoll23** [comment]
Oh, I see that you're using HOOBS. Maybe the name it's getting saved somewhere in a cache file?

You can also try to uninstall and reinstall the security system plugin to HOOBS as it should save the new name in the HomeKit and HOOBS database.

**Comment by Christian-CFP** [comment]
Maybe... Thats the last thing I will gonna do because I have so many automation based on the security system... Everything will be erased after reinstalling etc.

**Comment by Christian-CFP** [comment]
I now have removed it from home and reinstalled it. I made sure it never had the name "Security System" just "Sicherheitssystem" and still the same. It renamed itself to "Security System". No caching issue.

**Comment by Christian-CFP** [comment]
It renames itself just in Apple Home. In HOOBS/Homebridge it stays at the original name.

**Comment by MiguelRipoll23** [comment]
A new version will be published tomorrow that logs the options received and the services initialization (when the name is set), it will help a lot to understand what is happening.

I will notify you here once the new version is published.

**Comment by MiguelRipoll23** [comment]
I just published the version (**v7.2.0**) right now as I wanted to try some new things I'm working on. When the plugin starts it will print the config (original plugin configuration) and the options (plugin transformed configuration), we should be looking for the `security_system_name` and `securitySystemName` keys which should have the expected value. Also the name of the security system service will be printed as well `Security system service (expected name here)`.

**Comment by Christian-CFP** [comment]
21:36:07HOME BridgeSicherheitssystemConfig {"accessory":"security-system","name":"Sicherheitssystem","mode_off_switch":true,"siren_mode_switches":false,"reset_sensor":false,"reset_minutes":10,"save_state":true,"test_mode":false,"default_mode":"Home","audio_language":"de-DE","audio":false,"audio_arming_looped":false,"audio_alert_looped":false,"audio_volume":100,"reset_off_flow":false,"siren_switch":true,"override_off":false,"proxy_mode":false,"siren_sensor_seconds":10,"mode_pause_switch":true,"arming_lock_switch":true,"pause_minutes":10,"mode_away_extended_switch":true,"mode_switches":true,"siren_seconds":15,"siren_sensor":true,"home_arm_seconds":"0","night_arm_seconds":"0","away_arm_seconds":"0","home_trigger_seconds":"0","night_trigger_seconds":"30","away_trigger_seconds":"30","trigger_seconds":30,"night_trigger_delay":true,"double_knock":false,"double_knock_seconds":90,"arm_seconds":0,"tripped_sensor":true,"tripped_sensor_seconds":5,"away_extended_trigger_seconds":"0","arming_lock_switches":true,"home_double_knock_seconds":"null","away_double_knock_seconds":"null","night_double_knock_seconds":"null","audio_switch":false}
21:36:07HOME BridgeSicherheitssystemOptions {"name":"Sicherheitssystem","serialNumber":"S3CUR1TYSYST3M","defaultMode":"home","armSeconds":0,"triggerSeconds":30,"pauseMinutes":10,"resetMinutes":10,"saveState":true,"proxyMode":false,"testMode":false,"securitySystemName":**"Security System"**,"tripSwitchName":"Trip","tripHomeSwitchName":"Trip Home","tripAwaySwitchName":"Trip Away","tripNightSwitchName":"Trip Night","tripOverrideSwitchName":"Trip Override","logDirectory":null,"overrideOff":false,"resetOffFlow":false,"disabledModes":[],"homeArmSeconds":"0","awayArmSeconds":"0","nightArmSeconds":"0","homeTriggerSeconds":"0","awayTriggerSeconds":"30","nightTriggerSeconds":"30","awayExtendedTriggerSeconds":"0","armingLockSwitch":true,"armingLockSwitches":true,"tripSwitch":true,"tripOverrideSwitch":false,"tripModeSwitches":false,"trippedMotionSensor":true,"trippedMotionSensorSeconds":5,"triggeredMotionSensor":true,"triggeredMotionSensorSeconds":10,"resetSensor":false,"modeSwitches":true,"modeOffSwitch":true,"modePauseSwitch":true,"modeAwayExtendedSwitch":true,"doubleKnock":false,"doubleKnockSeconds":90,"doubleKnockModes":["Away"],"homeDoubleKnockSeconds":"null","awayDoubleKnockSeconds":"null","nightDoubleKnockSeconds":"null","audioSwitch":false,"serverCode":null,"audio":false,"audioLanguage":"de-DE","audioVolume":100,"audioArmingLooped":false,"audioAlertLooped":false,"audioExtraVariables":[],"nightTriggerDelay":true,"resetOff":false,"trippedSensor":false,"trippedSensorSeconds":5,"hideModeOffSwitch":false,"showModePauseSwitch":false}

**Comment by MiguelRipoll23** [comment]
It looks like you don't have the config key `security_system_name` set so the default value is `Security System`, is the option `Security System Name` under the `Accessory Names` set to `Sicherheitssystem` in your plugin configuration?

I see that you have the `name` key set to `Sicherheitssystem` but that's just a mandatory field that Homebridge requires but is completely ignored by the plugin.

**Comment by Christian-CFP** [comment]
This is my config. Do I miss something?

"accessory": "security-system",
"name": "Sicherheitssystem",
"mode_off_switch": true,
"siren_mode_switches": false,
"reset_sensor": false,
"reset_minutes": 10,
"save_state": true,
"test_mode": false,
"default_mode": "Home",
"audio_language": "de-DE",
"audio": false,
"audio_arming_looped": false,
"audio_alert_looped": false,
"audio_volume": 100,
"reset_off_flow": false,
"siren_switch": true,
"override_off": false,
"proxy_mode": false,
"siren_sensor_seconds": 10,
"mode_pause_switch": true,
"arming_lock_switch": true,
"pause_minutes": 10,
"mode_away_extended_switch": true,
"mode_switches": true,
"siren_seconds": 15,
"siren_sensor": true,
"home_arm_seconds": "0",
"night_arm_seconds": "0",
"away_arm_seconds": "0",
"home_trigger_seconds": "0",
"night_trigger_seconds": "30",
"away_trigger_seconds": "30",
"trigger_seconds": 30,
"night_trigger_delay": true,
"double_knock": false,
"double_knock_seconds": 90,
"arm_seconds": 0,
"tripped_sensor": true,
"tripped_sensor_seconds": 5,
"away_extended_trigger_seconds": "0",
"arming_lock_switches": true,
"home_double_knock_seconds": "null",
"away_double_knock_seconds": "null",
"night_double_knock_seconds": "null",
"audio_switch": false,
"plugin_map": {
                  "plugin_name": "homebridge-securitysystem"
}

**Comment by Christian-CFP** [comment]
Ok, I added this

"security_system_name": "Sicherheitssystem",

and it seems to work.

**Comment by MiguelRipoll23** [comment]
I was about to say that, glad is fixed now :)

It's easier to see using UI on Homebridge but maybe HOOBS does it differently:

![image](https://user-images.githubusercontent.com/3296866/229375869-d7acabfc-b537-4b22-960a-83eb6740d8c6.png)

**Comment by Christian-CFP** [comment]
Oh, it does in HOOBS but this may be the "name" value not the "security_system_name".

![Bildschirmfoto 2023-04-02 um 21 56 43](https://user-images.githubusercontent.com/39855486/229375977-f6186ad1-4201-4554-af25-01550c8a6bf5.jpg)

**Comment by MiguelRipoll23** [comment]
That's correct, it should appear right after the `Enable Test Mode` option but unsure if it's displayed ordered.

**Comment by Christian-CFP** [comment]
No, under the Testmode its not...

![Bildschirmfoto 2023-04-02 um 22 00 53](https://user-images.githubusercontent.com/39855486/229376127-b6966cea-cef8-403d-a1de-b3d5e1466617.jpg)

**Comment by MiguelRipoll23** [comment]
That's weird, I see that no sections appear as well.
HOOBS clearly works differently with the plugin configuration UI.

**Comment by Christian-CFP** [comment]
Yeah, I dont like the HOOBS UI. I work with the config itself ;)

**Comment by Christian-CFP** [comment]
The config in the log still shows up on 7.2.1

**Comment by MiguelRipoll23** [comment]
Some extra logging was removed but config and options will remain as they’re quite helpful to understand issues.
