### ISSUE TITLE
Add German as audio language

### ISSUE THREAD

**Issue by Christian-CFP** [MiguelRipoll23/homebridge-securitysystem#37]
Hi, in 2.9.0 how can I play the audio files and whos gonna play it? The pi via audio jack or e.g. external speakers like the HomePod etc.?

BTW.
in the General options "show_pause_switch" is wrong, should be "show_mode_pause_switch".

**Comment by MiguelRipoll23** [comment]
Hello,

Enable the `Play Audio` option. (After executing the grey trxt below to install ffmpeg) and the woulds would be played on your device speakers (anything connected to your jack).

This is is the non-HomeKit method to play sounds and the sounds can be changed by replacing the sounds inside the plugin directory (`/usr/local/lib/node_modules/homebridge-securitysystem`).

Thanks for informing me about the issue with the option `show_mode_pause_switch`, will fix this ASAP!

**Comment by Christian-CFP** [comment]
Ok, got it!
Is there a voice app in wich you have created those voice sounds?
If so maybe I can help with german phrases to create those too?

**Comment by MiguelRipoll23** [comment]
I’ve used a small application that makes use of the Google Text-to-Speech technology, it requires a billing account as it’s a pay to use service but there’s a free quota.

It’s more of a developer tool than a application to end-users, you can help me out by translating these phrases to German and I can generate the sounds and include them on the plugin as there’s multi-language support:

- Arming security system to Home mode
- Arming security system to Away mode
- Arming security system to Night mode
- Security system armed to Home mode
- Security system armed to Away mode
- Security system armed to Night mode
- Heads up! Security system’s countdown has started
- Alarm triggered
- Security system disarmed.

If you have a special request you can also write me your custom phrases as well 😀

**Comment by Christian-CFP** [comment]
> * Arming security system to Home mode
Zuhause-Modus des Sicherheitssystems wird aktiviert

> * Arming security system to Away mode
Abwesenheitsmodus des Sicherheitssystems wird aktiviert

> * Arming security system to Night mode
Nachtmodus des Sicherheitssystems wird aktiviert

> * Security system armed to Home mode
Sicherheitssystem befindet sich im Zuhause-Modus

> * Security system armed to Away mode
Sicherheitssystem befindet sich im Abwesenheitsmodus

> * Security system armed to Night mode
Sicherheitssystem befindet sich im Nachtmodus

> * Heads up! Security system’s countdown has started
Achtung! Der Countdown des Sicherheitssystems hat begonnen

> * Alarm triggered
Alarm wurde ausgelöst

> * Security system disarmed
Sicherheitssystem entschärft

**Comment by MiguelRipoll23** [comment]
New beta update published with the changes requested added, you can now try these changes executing the following command on your terminal:

`npm install -g homebridge-securitysystem@beta`

If you're a HOOBS user, please wait until the beta phrase has ended. Remember that you can leave the beta program anytime using the command below:

`npm install -g homebridge-securitysystem@latest`

Thanks!

**Comment by Christian-CFP** [comment]
After I hear the files... I changed some phrases. I love english phrases they are so short and on point. In german you have to fill in (with "das" or "wurde"), so that it sounds "german correct" ;) here the changes.

> * Security system armed to Home mode
Das Sicherheitssystem befindet sich im Zuhause-Modus

> * Security system armed to Away mode
Das Sicherheitssystem befindet sich im Abwesenheitsmodus

> * Security system armed to Night mode
Das Sicherheitssystem befindet sich im Nachtmodus

> * Alarm triggered
Der Alarm wurde ausgelöst

> * Security system disarmed
Das Sicherheitssystem wurde entschärft

**Comment by MiguelRipoll23** [comment]
Don’t worry about it.

When I was generating the sounds I was surprised by how long the phrases were, I thought that they would be spoken faster 😅

BTW, is the `Heads up! Security system...` phrase missing intended?

Also, be free to replace
`Security system` by `Alarm` if that makes it shorter but still correct!

**Comment by Christian-CFP** [comment]
Heads up!... was correct ;)

German is a very difficult language with different meanings, I know english too but much more easy than german :D

Security system = Sicherheitssystem (in this case it is quite correct and equals to the spelling in the Home app)
"Security system" could also be "Alarmanlage" = Alarm unit (kind of)

I tried to make the phrases as short as I could but still keeping the correctness.

BTW:
e.g. only for demo:

EN: Arming security system to Away mode
Total correct DE meaning of the EN: Der Abwesenheitsmodus des Sicherheitssystems ist gerade dabei aktiviert zu werden

Arming =  ist gerade dabei aktiviert zu werden (is about to be activated)
Arming in German if you don't know the english meaning means more like "Get your weapon" or "Armament".

**Comment by Christian-CFP** [comment]
Is it possible to send the audio to an airplay 2 speaker instead of just playing it through the audio jack?

**Comment by Christian-CFP** [comment]
In addition to that...
I'm playing a beeping sound when the alarm goes off until the siren kicks in.
It would be awesome if you can handle this as well directly in the plugin.
Beeping sound in loop as long as the ""trigger_seconds": xx" is set to.

**Comment by MiguelRipoll23** [comment]
> Is it possible to send the audio to an airplay 2 speaker instead of just playing it through the audio jack?

That's a really good question, I think it's possible but it requires the mode switches option enabled and the entire flow made using HomeKit automation. The sounds would be imported to the iTunes library so they could be played by a HomeKit action. I'll investigate this and come back with a answer as soon as I got the precise details.

Also, I just released a new beta version with the translations updated, be free to suggest more changes if you need so as I completely understand that translations are sometimes difficult to get right and fit their context.

**Comment by MiguelRipoll23** [comment]
> I'm playing a beeping sound when the alarm goes off until the siren kicks in.
It would be awesome if you can handle this as well directly in the plugin.

You mean a beeping sound when the security system's countdown has started, right?

**Comment by Christian-CFP** [comment]
Thats how I am currently using it right now. With automations based on the mode switches.

My thinking here is (if possible) just send the audio directly to a speaker without using homekit automations.

> You mean a beeping sound when the security system's countdown has started, right?

That's right!

**Comment by MiguelRipoll23** [comment]
> My thinking here is (if possible) just send the audio directly to a speaker without using homekit automations.

At this moment, unfortunately we can't communicate to AirPlay 2 clients as the protocol is completely private and no one yet has successfully created a library to make use of it. Hopefully this changes in the future.

> That's right!
> Instead of the Text "... Countdown has started"

I could add an option to play the alert sound in loop then, I've seen other user like you doing the exact thing. Do you mind creating another issue for this? I sometimes have suggestions from Reddit as well and I keep feature requests organized this way, it has also advantages for you as you get notified as soon as I start work on it.

Thanks 😊

**Comment by MiguelRipoll23** [comment]
New stable update just released with the feature requested added, you can now update the plugin using the Homebridge / HOOBS UI. If you were part of the beta program you can now leave it using the following command:

`npm install -g homebridge-securitysystem@latest`

Thanks!
