### ISSUE TITLE
How to use the "trigger during off mode"

### ISSUE THREAD

**Issue by Olivierbkk** [MiguelRipoll23/homebridge-securitysystem#373]
### Plugin version

zzz

### Plugin configuration

zzz

### Homebridge version

zzz

### What's your question?

I can't find explanations anywhere, I have tried to enable it and don't see any difference with when it's disabled

thanks

**Comment by MiguelRipoll23** [comment]
Hello,

If you enable the `Show Trip Switch` option it will show a global trip switch which would be able to trigger the security system when the mode `Off` is set if that option that you refer to is enabled.

**Comment by Olivierbkk** [comment]
Thanks, that can be useful to implement a "panic button" which I had in the old alarm system.
