### ISSUE TITLE
Beeping alert sound during countdown

### ISSUE THREAD

**Issue by Christian-CFP** [MiguelRipoll23/homebridge-securitysystem#38]
I'm playing a beeping sound when the alarm goes off until the siren kicks in.
It would be awesome if you can handle this as well directly in the plugin.
Beeping sound in loop as long as the ""trigger_seconds": xx" is set to.

_Originally posted by @Christian-CFP in https://github.com/MiguelRipoll23/homebridge-securitysystem/issues/37#issuecomment-640043987_

**Comment by MiguelRipoll23** [comment]
New beta update published with the feature requested added, you can now try these changes executing the following command on your terminal:

`npm install -g homebridge-securitysystem@beta`

If you're a HOOBS user, please wait until the beta phrase has ended. Remember that you can leave the beta program anytime using the command below:

`npm install -g homebridge-securitysystem@latest`

Thanks!

**Comment by MiguelRipoll23** [comment]
New stable update just released with the feature requested added, you can now update the plugin using the Homebridge / HOOBS UI. If you were part of the beta program you can now leave it using the following command:

`npm install -g homebridge-securitysystem@latest`

Thanks!
