### ISSUE TITLE
Noonlight integration

### ISSUE THREAD

**Issue by johnnygeezz** [MiguelRipoll23/homebridge-securitysystem#39]
I was recently looking at information on HomeAssistant and found this blog post below that you may find useful for new ideas. In particular, see the part about integrating with Noonlight via an IFTTT webhook. This could be game changing functionality. 

https://dfederm.com/setting-up-a-security-system-with-home-assistant/

https://www.noonlight.com/

**Comment by johnnygeezz** [comment]
Some more info on Noonlight. 

https://community.smartthings.com/t/release-professional-smart-home-monitoring-for-security-and-smoke-alarms-with-noonlight/134573

**Comment by MiguelRipoll23** [comment]
Thanks for creating an issue here.

We can do this the exact way it was described on the HomeAssistant blog post by using IFTTT. I had another way to implement it on my mind but it ends up being harder to configure as an user 🙃

Are you okay with this? Keep in mind that IFTTT probably prioritizes these kind of requests so they wouldn’t be delayed.

**Comment by johnnygeezz** [comment]
Cool. Let’s go!

**Comment by MiguelRipoll23** [comment]
That's awesome.

What you need to do it's kinda similar, it looks quite long and complex on paper but it's actually easier:

### IFTTT
1. [Connect Noonlight to your IFTTT account.](https://ifttt.com/safetrek)
2. [Connect Webhooks yo your IFTTT account.](https://ifttt.com/maker_webhooks)
3. [Go to the Webhook settings](https://ifttt.com/maker_webhooks/settings) and copy the part after `https://maker.ifttt.com/use/`. This is your **private key**, you will use it on the plugin's configuration.
4. [Go to the IFFTT creation page.](https://ifttt.com/create)
5. Click on the `+This` , write `Webhooks` on the `Search services...` text box. and select it.
6. Click on the `Receive a web request` card.
7. Write `alarm_triggered` as event name.
8. Click on the `+That`, write `Noonlight` on the `Search services...` text box. and select it.
9. There should be an option to create an alarm there, click it.
10. Click finish once everything is set up.

### homebridge-securitysystem

- Go to the settings UI (the one from Homebridge)
- Expand the `Webhooks (Optional)` category and find the `webhook_triggered` option.
- Write this on it:

> https://maker.ifttt.com/trigger/alarm_triggered/with/key/PRIVATE_KEY_HERE

**Comment by MiguelRipoll23** [comment]
Previous comment edited with some corrections.

**Comment by johnnygeezz** [comment]
I’ll put this together tomorrow.

**Comment by johnnygeezz** [comment]
Ok, I have it configured, but what should I expect when testing it? A fire truck showing up at my door or can it be canceled?

**Comment by MiguelRipoll23** [comment]
I think this is configured on IFTTT, by default the police is called.

Use the Noonlight app to cancel it.

**Comment by johnnygeezz** [comment]
Tried it out. Worked perfectly. Using Noonlight free basic account. 

Alarm triggered. Text message from Noonlight within 5 seconds. Call from them within 10 seconds.

**Comment by johnnygeezz** [comment]
Couple thoughts on the Noonlight:

1- it would be nice to be able to enable/disable with a checkbox the use of the webhook from the Homebridge UI. That way you can leave your set up alone if you’re trying out automations or just don’t want it to call out to Noonlight while your testing things. 

2- an interesting automation could be to have Siri activate the Siren and call out to Noonlight. In the case of a fall or other sudden emergency “on-demand” event. “Hey Siri, sound the Siren!”

3- another interesting automation could be to have my First Alert OneLink smoke detector (uses HomeKit now) to trigger the Siren to call out to Noonlight in the event of a fire. My current automation turns on the lights all over the house. This would make for a more complete implementation. 

Thoughts?

**Comment by MiguelRipoll23** [comment]
> 1- it would be nice to be able to enable/disable with a checkbox the use of the webhook from the Homebridge UI or Home app somehow. That way you can leave your set up alone if you’re trying out automations or just don’t want it to call out to Noonlight while your testing things. Kind of like an override.

You can disable the Noonlight call action temporarily by going to IFTTT and pressing on the `Connected` switch, this is far better due to two reasons:
- It doesn't require you to restart Homebridge during testing.
- Webhook use cases are way too broad.

> 2- an interesting automation could be to have Siri activate the Siren and call out to Noonlight. In the case of a fall or other sudden emergency “on-demand” event. “Hey Siri, sound the Siren!”

Enable the `Trigger During Off Mode` option and say `Hey Siri, turn on Siren`, if you want a custom phrase you can use create a Shortcut that turns on the Siren and then you name it `Sound the siren`, that should work.

> 3- another interesting automation could be to have my First Alert OneLink smoke detector (uses HomeKit now) to trigger the Siren to call out to Noonlight in the event of a fire. My current automation turns on the lights all over the house. This would make for a more complete implementation.

Unfortunately, HomeKit doesn't allow me to know the origin of the device that has made an action on my plugin to do this, hopefully this changes in the future.

**Comment by johnnygeezz** [comment]
Good answers to my use cases for 1 and 2. 

For the 3rd one about the smoke detectors, couldnt I just include, IF smoke detected,  “Turn on Siren Switch” as a step in my automation along with “Turn on Lights”? I think I could program that in the Eve app. 

Are you saying this wouldn’t work to active the trigger event for the webhook?

**Comment by MiguelRipoll23** [comment]
Sorry, I misunderstood what you were saying.

You’re correct, I thought you meant calling a different emergency service. By default it calls the police but the fire department can be called as well but I can’t tell if it was your smoke sensor the one  that triggered the alarm due to HomeKit limitations.

**Comment by johnnygeezz** [comment]
Right. This sounds great!

**Comment by MiguelRipoll23** [comment]
Both are cloud based.

You don’t need IFTTT installed but having Noonlight installed on your phone may be useful to update home or person details and cancelling an alarm.

**Comment by johnnygeezz** [comment]
Great thanks for the clarification. Probably good to have the IFTTT installed as well so that you can temporarily 'Disconnect' the service if you're trying new automations, etc. as mentioned earlier. I just wanted to make sure that if my phone is 100% shutdown, that this will still work.

**Comment by cirrusflyer** [comment]
Is this still working in 2024?
