### ISSUE TITLE
Homebridge security plug in not responsive after ios 16.4 upgrade. (with 2 apple hubs)

### ISSUE THREAD

**Issue by Onno21** [MiguelRipoll23/homebridge-securitysystem#409]
### Plugin version

7.2.1

### Plugin configuration

I have a homekit setup with 1 apple TV and 1 homepod. Both work as hubs I presume. After the 16.4 infrastructure update it seems that the security plug in has an issue with two hubs. (I have a second home with the same setup and the same issue).

If I cut the electricity on the homepod, the security plugin is responsive again. (so back to one hub)

If I turn on the homepod again, initially the system remains working but after let’s say 10 hours the system becomes irresponsive again. I have repeated this sequence for about 3 days with the same result.

### Homebridge version

4.2.8

### What happened?

see above

**Comment by MiguelRipoll23** [comment]
Hey there,

I'm running some tests using the new architecture to investigate this issue meanwhile I got some questions that can be helpful:

- Do all accessories provided by the plugin show up as "No response"?

- Using the security system accessory, can you change its mode during the "No response" status?

Keeping in mind that the plugin only uses the "No response" error to cancel an attempt to trip the security system during an invalid mode (for example turning on the "Trip Home" switch during "Away" mode), do you have any automations that could result in this error? If so, could you please provide the log from the plug-in?

Thanks for the donation!

**Comment by Onno21** [comment]
Hello Miguel,I only have two tiles in my HomeKit set up.  One is the status: home/away/night/etc.. and the other one is the alarm signal. Both are not working.No I can not change the status when they are inresponsiveI am not sure I understand your last question. I do have an automation that turns the home mode into night mode at a certain time at night to make sure I can trigger certain sensors based on the fact we are home but a sleep. That used to work fine until the iOS upgrade. The trigger for the non response seems to be that I added a HomePod to the system (in my primary home) that automatically acts as a hub. (I did this after the iOS upgrade). In my other home I have two Apple tv’s ((two hubs)  and then suddenly the security plugin started to be irresponsible. Therefore I assumed the two issues (between the two homes) are related.The two homes have different security plug-in’s. One runs on synology and the other one on hoobs.I hope this helps and please do not hesitate to ask me more questions.Kind regardsOnnoOp 6 apr. 2023 om 12:04 heeft Miguel Ripoll ***@***.***> het volgende geschreven:﻿
Hey there,
I'm running some tests using the new architecture to investigate this issue meanwhile I got some questions that can be helpful:


Do all accessories provided by the plugin show up as "No response"?


Using the security system accessory, can you change its mode during the "No response" status?


Keeping in mind that the plugin only uses the "No response" error to cancel an attempt to trip the security system during an invalid mode (for example turning on the "Trip Home" switch during "Away" mode), do you have any automations that could result in this error? If so, could you please provide the log from the plug-in?
Thanks for the donation!

**Comment by MiguelRipoll23** [comment]
Thanks for the answers, @Onno21.

The plugin has the ability to send a `No response` error as I mentioned earlier but with the information you provided me this isn't the case as the plugin would continue to be responsive anyways. Can you try to set a different serial number to each security system just in case? You can change it inside the plugin settings although it shouldn't be a problem. I'm using HomePod as my HomeKit Hub myself I can't reproduce the problem unfortunately.

Can you try to add another plugin to Homebridge to see if it's also unresponsive?

**Comment by Onno21** [comment]
Hello Miguel,Thanks for trying. I am spending a long weekend in Paris. I will try your suggestions next week.Have a good Easter weekendOnnoOp 7 apr. 2023 om 14:05 heeft Miguel Ripoll ***@***.***> het volgende geschreven:﻿
Thanks for the answers, @Onno21.
The plugin has the ability to send a No response error as I mentioned earlier but with the information you provided me this isn't the case as the plugin would continue to be responsive anyways. Can you try to set a different serial number to each security system just in case? You can change it inside the plugin settings although it shouldn't be a problem. I'm using HomePod as my HomeKit Hub myself I can't reproduce the problem unfortunately.
Can you try to add another plugin to Homebridge to see if it's also unresponsive?

**Comment by rvaneeuwijk** [comment]
Hi guys,

@Onno21: I have a similar set up with a combination of Apple TVs and HomePod Minis as hubs, all running OS 16.4, and the security system accessory is working fine. So I suspect your issue may be something different.

@MiguelRipoll23: You mention that you can set the serial number for the security system. I would like to do that as I am running two instances of your plugin. I am using HOOBS and I haven't been able to find a way to set the serial number. How/where can I do that? Thanks!

**Comment by MiguelRipoll23** [comment]
@rvaneeuwijk A new version (v7.3.0) has been published with improved HOOBS compatibility for the plugin configuration, hopefully that will show the missing configuration options that don't appear in the user interface that are now unknown to HOOBS users.

If you don't see the changes right away after updating https://github.com/hoobs-org/HOOBS/issues/1777#issuecomment-1019572544

**Comment by Onno21** [comment]
Hello Miguel,Small update from my side on my unresponsive issue.Over the last week I have done some trial and error and so far I have found the following:- I have an apple TV and since recently a homepod. The apple TV is wired, the homepod is wireless.- I have a router with three WIFI repeaters. All wired and in a mesh network- At night I automatically switch your homebridge security system to “night” and at the same time I turn-off two wireless repeaters to save energy. (this does not effect my homekit infrastructure since all hubs are wired)- Despite the fact that the homepod is close to the baserouter and connected to the wifi of the router, something in the WIFI mesh is getting unstable and effects my homepod and it also effects the responsiveness of the homebridge security.- When I switch the electricity of the homepod on and off the homebridge security system is working again.- If I run the system without the homepod, everything continues workingI have not been able to test the issue in my other home.I let you know when I find out more.Kind regards,OnnoVerstuurd vanaf mijn iPadOp 11 apr. 2023 om 12:08 heeft Miguel Ripoll ***@***.***> het volgende geschreven:﻿
@rvaneeuwijk A new version (v7.3.0) has been published with improved HOOBS compatibility for the plugin configuration, hopefully that will show the missing configuration options that don't appear in the user interface that are now unknown to HOOBS users.
If you don't see the changes right away after updating hoobs-org/HOOBS#1777 (comment)

**Comment by Onno21** [comment]
Hello Miguel,

I did some more testing. It seems slightly different.

I used to have only a appleTV as homekit hub. To improve the reliability, every night I automatically switched off the Apple TV for 5 minutes (kind of refresh, which I forgot about).

After the upgrade to IOS 16.4, I bought a HomePod which automatically starts to act as a second hub. (More a coincidence that the HomePod came so close to the upgrade, which made me link it to my unresponsive issue)

I believe there is an interference between me switching off the appleTV, therefore the HomePod being the only hub for 5 minutes overnight, and your security plug in becoming irresponsive.

Last night I turned of the automatic off-switch for the Apple TV and I did not have an issue with my security plug-in anymore

It also would explain, to a certain extent, that switching the HomePod off/on in the morning did solve my unresponsiveness issue too.

I will continue to monitor the situation, but wanted to let you know.

Kind regards,

Onno

**Comment by MiguelRipoll23** [comment]
Hey there,

Yeah, unfortunately looks like the automatic Home Hubs selection doesn't work very well, I see a lot of people reporting issues with their Apple TV and HomePod over Reddit. Apple should let the user use their prefered Home Hub.
