### ISSUE TITLE
Name field in config not working properly 

### ISSUE THREAD

**Issue by rvaneeuwijk** [MiguelRipoll23/homebridge-securitysystem#410]
### Plugin version

7.2.1

### Plugin configuration

{
    "accessories": [
        {
            "name": "Garage Security Mode",
            "arm_seconds": 30,
            "home_arm_seconds": "null",
            "night_arm_seconds": "null",
            "away_arm_seconds": 30,
            "trigger_seconds": 30,
            "home_trigger_seconds": "null",
            "night_trigger_seconds": "null",
            "away_trigger_seconds": 30,
            "reset_minutes": 10,
            "away_extended_trigger_seconds": "null",
            "double_knock_seconds": 90,
            "home_double_knock_seconds": "null",
            "away_double_knock_seconds": "null",
            "night_double_knock_seconds": "null",
            "disabled_modes": [
                "Home",
                "Night"
            ],
            "tripped_sensor_seconds": 5,
            "siren_sensor_seconds": 5,
            "pause_minutes": 0,
            "siren_mode_switches": false,
            "siren_switch": true,
            "audio_volume": 100,
            "accessory": "security-system",
            "plugin_map": {
                "plugin_name": "homebridge-securitysystem"
            }
        }
    ]
}

### Homebridge version

1.6.0

### What happened?

Regardless of the name I give to the plugin in the configuration file (e.g. "Home Security Mode" in my configuration ), the security system switch always appears with the name "Security System" in the Apple Home App. As I am running two instances of your plugin (one for a different zone in my home), that is a bit frustrating as I rely on the name to identify which is which (not only in manual use, but also when using your plugin accessories in other apps).

### Relevant log output

```bash
Not applicable
```

**Comment by MiguelRipoll23** [comment]
Please see [reply](https://github.com/MiguelRipoll23/homebridge-securitysystem/issues/363#issuecomment-1493425594), unfortunately HOOBS is not displaying the full plugin configuration.

The name field you have used to set a name to the security system is an internal Homebridge name actually and not used by the plugin.

**Comment by rvaneeuwijk** [comment]
Thanks! That did the trick. I think it would really help if you pulled all of these bits of info together in the documentation. Happy to draft it for you with your support.
