### ISSUE TITLE
Expand configured names to all switches

### ISSUE THREAD

**Issue by DaveEdwards97** [MiguelRipoll23/homebridge-securitysystem#419]
### What are you missing?

Please can you provide configured names fields like the trip switches for the mode switches, and any other switch which the plugin can expose too.

**Comment by MiguelRipoll23** [comment]
Hello,
Sure, I will add options to configure the name of the mode switches for now I'm quite busy lately.

**Comment by DaveEdwards97** [comment]
Thank you for the quick update @MiguelRipoll23 especially as you're busy. It's very much appreciated.

If you do have a spare moment in the near future, please can you also add the configured name option to the "Mode Away Extended" switch too, it will be very much appreciated in my setup (and possibly others).

Would it be good to also raise another issue on the further expansion of the configured name option to any other remaining switches and sensors exposed by the plugin ready for when you can get round to the rest?

**Comment by MiguelRipoll23** [comment]
Sure, the next update will add support to these ones:

- mode_away_extended_switch
- mode_pause_switch
- audio_switch

I will work on it soon, no need to raise another issue.

**Comment by MiguelRipoll23** [comment]
@DaveEdwards97 a new update has been published with additional configured name options for the mode extended away switch, mode pause and audio switches.
