### ISSUE TITLE
I can’t set modes manually

### ISSUE THREAD

**Issue by salemsayed** [MiguelRipoll23/homebridge-securitysystem#420]
### Plugin version

7.3.0

### Plugin configuration

{
    "name": "Outdoor Security System",
    "serial_number": "SYSTEM",
    "default_mode": "Off",
    "arm_seconds": 0,
    "trigger_seconds": 0,
    "reset_minutes": 10,
    "save_state": false,
    "proxy_mode": false,
    "test_mode": false,
    "trip_switch_name": "Trip",
    "trip_home_switch_name": "Trip Home",
    "trip_away_switch_name": "Trip Away",
    "trip_night_switch_name": "Trip Night",
    "trip_override_switch_name": "Trip Override",
    "override_off": false,
    "reset_off_flow": false,
    "double_knock": false,
    "double_knock_seconds": 90,
    "double_knock_modes": [
        "Night"
    ],
    "disabled_modes": [
        "Home",
        "Away"
    ],
    "tripped_sensor": true,
    "tripped_sensor_seconds": 5,
    "siren_sensor": false,
    "siren_sensor_seconds": 5,
    "reset_sensor": false,
    "mode_switches": true,
    "mode_off_switch": true,
    "mode_away_extended_switch": false,
    "mode_pause_switch": false,
    "pause_minutes": 0,
    "arming_lock_switch": false,
    "arming_lock_switches": false,
    "siren_switch": false,
    "siren_override_switch": false,
    "siren_mode_switches": true,
    "audio_switch": false,
    "audio": false,
    "audio_language": "en-US",
    "audio_volume": "100",
    "audio_arming_looped": false,
    "audio_alert_looped": false,
    "accessory": "security-system"
}

### Homebridge version

1.6.0

### What's your question?

Hi,

I’m unable to manually change the modes through Homekit, I can set an automation to arm the system to Night mode but I’m unable to do it manually unless I turn on the Mode Switches. 

Here is an image of the accessory in Home.app. I tried enabling all 3 modes but also I can’t see the mode switches in the accessory at all.
![image](https://user-images.githubusercontent.com/283208/232352149-9f055c95-a33a-4f53-b61a-90a7d624518a.jpeg)

**Comment by MiguelRipoll23** [comment]
Hello,

I can reproduce the issue although I'm unsure of what's happening. HomeKit isn't sending a mode change to the plugin, maybe it's changing its behaviour when only one mode is available and sending a different command, I will try to investigate it when I have more time.

**Comment by salemsayed** [comment]
Thank you, appreciated. Lmk if you need me to collect any logs or smth
