### ISSUE TITLE
ffmpeg / Alarm Sound problem

### ISSUE THREAD

**Issue by mfischcgn** [MiguelRipoll23/homebridge-securitysystem#44]
Hi there.
If I want to use the audio options for the Alarm, I get this error message:

Error: spawn ffplay ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

I tried to install ffmpeg. It seemed that it is installed, but the error persists.
Maybe someone could help me getting this working. Thanks in advance!

(I use docker with a Homebridge image on a Synology NAS)

**Comment by mfischcgn** [comment]
Finally i got ffmpeg installed directly to docker, now i still got errors, but different. Any suggestions? Thanks:
Audio failed
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5181:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
No more combinations to try, audio open failed
Failed to open file '/homebridge/node_modules/homebridge-securitysystem/sounds/de-DE/current-home.mp3' or configure filtergraph

**Comment by MiguelRipoll23** [comment]
Hey there,

Can you confirm me if this path exists?

> /homebridge/node_modules/homebridge-securitysystem

Thank you.

**Comment by mfischcgn** [comment]
Yes, this path exists. Everything is working except the audio. if i do a manual "ffplay" on the homebridge console, it gives me following error:

/homebridge/node_modules/homebridge-securitysystem/sounds/de-DE # ffplay current-alert.mp3 
ffplay version 4.3 Copyright (c) 2003-2020 the FFmpeg developers
  built with gcc 9.3.0 (Alpine 9.3.0)
  configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --enable-libssh --disable-stripping --disable-static --disable-librtmp --enable-vaapi --enable-vdpau --enable-libopus --enable-libaom --disable-debug
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
error: XDG_RUNTIME_DIR not set in the environment.
The path /dev/dri/ cannot be opened or is not available
The path /dev/dri/ cannot be opened or is not available
Could not initialize SDL - No available video device
(Did you set the DISPLAY variable?)


-------


(I don't have a /dev/dri/ folder on my syno)

**Comment by MiguelRipoll23** [comment]
Try to execute this instead:

> ffplay -nodisp  current-alert.mp3

**Comment by mfischcgn** [comment]
Wow you're quick :-) Thanks. It's a bit different but still errors....:
/homebridge/node_modules/homebridge-securitysystem/sounds/de-DE # ffplay -nodisp current-alert.mp3
ffplay version 4.3 Copyright (c) 2003-2020 the FFmpeg developers
  built with gcc 9.3.0 (Alpine 9.3.0)
  configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-libdav1d --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --enable-libssh --disable-stripping --disable-static --disable-librtmp --enable-vaapi --enable-vdpau --enable-libopus --enable-libaom --disable-debug
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mp3 @ 0x7f659a7d2140] Estimating duration from bitrate, this may be inaccurate
Input #0, mp3, from 'current-alert.mp3':
  Duration: 00:00:04.03, start: 0.000000, bitrate: 32 kb/s
    Stream #0:0: Audio: mp3, 24000 Hz, mono, fltp, 32 kb/s
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5181:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
SDL_OpenAudio (1 channels, 24000 Hz): ALSA: Couldn't open audio device: No such file or directory
No more combinations to try, audio open failed
Failed to open file 'current-alert.mp3' or configure filtergraph
    nan    :  0.000 fd=   0 aq=    0KB vq=    0KB sq=    0B f=0/0

**Comment by MiguelRipoll23** [comment]
Can you add this to your `docker run` arguments

> --group-add $(getent group audio | cut -d: -f3)

and check if audio works?

**Comment by mfischcgn** [comment]
I have to idea where to exactly add this argument. Try to find out...

**Comment by MiguelRipoll23** [comment]
Are you using [oznu/docker-homebridge](https://github.com/oznu/docker-homebridge), right? You should execute the following command on your host terminal, edit the /path/to/config part first though:

```
docker run \
  --net=host \
  --name=homebridge \
  --group-add $(getent group audio | cut -d: -f3 )
  --device /dev/snd
  -e PUID=<UID> -e PGID=<GID> \
  -e TZ=<timezone> \
  -e HOMEBRIDGE_CONFIG_UI=1 \
  -e HOMEBRIDGE_CONFIG_UI_PORT=8080 \
  -v </path/to/config>:/homebridge \
  oznu/homebridge
```

**Comment by mfischcgn** [comment]
Yes, that's right, i use the /oznu/docker-homebridge.
The problem is that i don't know here to find the .config?
Is it the config of the Synology or a config of the docker or of the homebridge and where do i find it?

(Excuse me... it's a long time ago i did a little programming ,-)) )

**Comment by mfischcgn** [comment]
![Bildschirmfoto 2020-06-28 um 14 14 43](https://user-images.githubusercontent.com/54134099/85947266-e4c3a680-b949-11ea-93d2-07905bc7d86c.png)
 
Is this the right place for docker run ?

**Comment by MiguelRipoll23** [comment]
Yup, that's it!

I'm unsure about how to mount the host audio device to the container, does the following works?

**Comment by MiguelRipoll23** [comment]
Looks like it's not supported by the Synology Docker UI but — there's something else we can do.

1. Go the the Synology Docker UI
2. Click the `Image` option from the sidebar.
3. Click the `Launch` option.
4. Check the `Execute container using high privilege` checkbox.
4. Continue as normal.

Now all the devices should be mounted to the the container (including the audio one).

**Comment by mfischcgn** [comment]
Ops, i managed to destroy my homebridge image somehow. Will reinstall it and come back to it afterwards.

Do you yourself use your plugin with a Rhaspberry Pi? Is it easier to manage the audio ?

**Comment by MiguelRipoll23** [comment]
It's easier to more closer that you are to the "native" software. In this case, it looks like Docker is limiting the devices that can see from your host system due to its security features.

It shouldn't be an issue to you if the`Execute container using high privilege` works as expected 🙂

**Comment by mfischcgn** [comment]
I tried with the high privilege, but unfortunately it's still the same error :-(

**Comment by MiguelRipoll23** [comment]
Can you SSH to your Homebridge container, add yourself to the `audio` group and check again?

> whoami

(This will say your username)

> adduser <username_here> audio

Also, is there any directories on the path below?

> /dev && ls -l

**Comment by mfischcgn** [comment]
woami says root..hmmmm...
![Bildschirmfoto 2020-06-28 um 15 36 41](https://user-images.githubusercontent.com/54134099/85949137-450c1580-b955-11ea-9ddc-3750d7e19a22.png)
![Bildschirmfoto 2020-06-28 um 15 37 01](https://user-images.githubusercontent.com/54134099/85949139-476e6f80-b955-11ea-8484-959a9f68f124.png)

**Comment by MiguelRipoll23** [comment]
Execute this instead:

> adduser root audio

I don't see a `snd` file inside /dev but looks like the privileged option worked fine.

I think

**Comment by mfischcgn** [comment]
still the same... 

maybe this helps? :
![Bildschirmfoto 2020-06-28 um 15 49 13](https://user-images.githubusercontent.com/54134099/85949445-23ac2900-b957-11ea-8222-4392ddc9ff28.png)
![Bildschirmfoto 2020-06-28 um 15 50 38](https://user-images.githubusercontent.com/54134099/85949446-2575ec80-b957-11ea-9c15-722585d83dd0.png)

**Comment by MiguelRipoll23** [comment]
That’s quite helpful, thank you.

Can you open any of the files inside the `/dev` directory or you get a “Permission denied” message?

Open it like this:

```
cat timer
```

**Comment by mfischcgn** [comment]
If i do it, just nothing happens
![Bildschirmfoto 2020-06-28 um 16 24 25](https://user-images.githubusercontent.com/54134099/85950229-de3e2a80-b95b-11ea-8d8e-421e20ac82c7.png)

**Comment by mfischcgn** [comment]
I found the solution i think!
When i use it like this is works:

ffplay current-alert.mp3 -nodisp (-volume 100)

I think it's because the Synology has no Display Ports, so -nodisp seems to help
Would be great to make it possible to chose a volume in your plugin.

(Screenshot-> I used "-loop 100" and  "-volume 100" just for testing reasons)
![Bildschirmfoto 2020-06-28 um 16 53 41](https://user-images.githubusercontent.com/54134099/85950939-1cd5e400-b960-11ea-955f-5bf841219b43.png)

**Comment by MiguelRipoll23** [comment]
That's awesome!

The -nodisp option is added by the plugin, does it work using it?

Right now I'm checking something from work so I may be a little bit busy to answer immediately so apologies for if I kept you waiting to solve this issue.

**Comment by mfischcgn** [comment]
No problem. It's great that you're responsive.
Hmm, that's crazy, right, i've just seen it's already in there. 

So, what i can clearly say by now is, that if i go into there Terminal and write:

ffplay current-alert.mp3
It will play nothing and give the error message
"Could not initialize SDL - No available video device
(Did you set the DISPLAY variable?)"

if i do:

ffplay current-alert.mp3 -nodisp
I get the sound and no error message.

**Comment by mfischcgn** [comment]
and then, if i want to turn the SecuritySystem on in Homekit  (with play audio active), Homebridge gives me the same error like before (of course, because nothing changed yet):
![Bildschirmfoto 2020-06-28 um 17 24 10](https://user-images.githubusercontent.com/54134099/85951582-442eb000-b964-11ea-92e8-f09d6b9597ac.png)

**Comment by MiguelRipoll23** [comment]
Does doing this help?

```
chmod 777 /dev/snd
chmod 777 /dev/snd/*
```

BTW, audio is working manually but is this from inside the Homebridge container or outside?

**Comment by mfischcgn** [comment]
Thanks, it's a little better with less errors.
(I do everything directly in the Terminal of Homebdrige UI, so i guess its inside
![Bildschirmfoto 2020-06-28 um 17 32 45](https://user-images.githubusercontent.com/54134099/85951769-94f2d880-b965-11ea-8f16-b3671e7002af.png)
)

**Comment by mfischcgn** [comment]
This is how it looks in debug mode:
![Bildschirmfoto 2020-06-28 um 18 10 05](https://user-images.githubusercontent.com/54134099/85952588-aab6cc80-b96a-11ea-9c68-159c5d574856.png)

**Comment by MiguelRipoll23** [comment]
Can you `ls -l` inside /dev/snd and post an screenshot?

Looks like it’s getting “Permission denied” when accessing the sound device so I want to confirm how the permissions are now set after the chmod command was executed. 

P.S. I’m fully available now.

**Comment by mfischcgn** [comment]
Yes, no problem.

P.S. Great! :-)
![Bildschirmfoto 2020-06-28 um 19 18 22](https://user-images.githubusercontent.com/54134099/85953929-28330a80-b974-11ea-9611-ae04e9a02d8c.png)

**Comment by MiguelRipoll23** [comment]
I got one more, let’s see if it finally works:

```
chmod -R a+rw /dev/{audio,dsp,midi,mixer,snd}
```

**Comment by mfischcgn** [comment]
I see that i don't have audio dsp etc.
but I have
audio4, dsp3, mixer3 + snd (without "3")
no midi
tried to chmod both, but gives me errors, see screenshot
![Bildschirmfoto 2020-06-28 um 19 40 42](https://user-images.githubusercontent.com/54134099/85954385-464e3a00-b977-11ea-9795-13fb620fa817.png)

try to chmod one by one now

**Comment by mfischcgn** [comment]
didn't work either :-(

**Comment by MiguelRipoll23** [comment]
If this doesn’t work I’m about to ran out of ideas 🙃

```
chmod -R a+rw /dev/{audio4,dsp3,mixer3,snd}

```

and check if the plugin is able to play sounds.

**Comment by mfischcgn** [comment]
unfortunately not. but thanks for helping anyway. Maybe I'll try with a Rhaspberry

**Comment by MiguelRipoll23** [comment]
Sorry, I have closed accidentally this issue.

Reopening as investigation of this bug is ongoing.

**Comment by macjl** [comment]
Hello,

I'm facing exactly the same problem. I've search, and found that the default Alsa card was not good to play sounds. FYI, I'm running this plugin in a computer under Linux with multiple sound devices (HDMI, Webcam, Audio USB card, Line out...)

So, for me, the solution would be to use this ffmpeg command instead of ffplay, to select the right Alsa audio card : 
`ffmpeg -i /opt/node/lib/node_modules/homebridge-securitysystem/sounds/en-US/current-night.mp3 -f alsa default:CARD=Device`

You can find all audio cards with command : 
`ffplay -sinks alsa`

@MiguelRipoll23, do you think it's possible to provide an option to override the audio sound card?
 As it should work on Linux, and other OS, I think all the output device should be a parameter.
For example : 
`"audio_output" : "-f alsa default:CARD=Device"`
and command : 
`ffmpeg -i <audio_file> <audio_output>`

But you should keep using 'ffplay' for default configuration, because you won't know what output device to use depending on OS.

**Comment by MiguelRipoll23** [comment]
@macjl sure, thanks for your help!

> the solution would be to use this ffmpeg command instead of ffplay

It doesn't work using ffplay? I thought they shared options.

> ffplay -i /opt/node/lib/node_modules/homebridge-securitysystem/sounds/en-US/current-night.mp3 -f alsa default:CARD=Device -nodisp -autoexit

**Comment by macjl** [comment]
Did not manage to use it with ffplay : 
```
root@7ba4363ab910:/opt# ffplay -i /opt/node/lib/node_modules/homebridge-securitysystem/sounds/en-US/current-night.mp3 -f alsa default:CARD=Device -nodisp -autoexit
ffplay version 4.1.6-1~deb10u1 Copyright (c) 2003-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Argument 'default:CARD=Device' provided as input filename, but '/opt/node/lib/node_modules/homebridge-securitysystem/sounds/en-US/current-night.mp3' was already specified.
```

**Comment by MiguelRipoll23** [comment]
I messed up the order, I think the following should work:

> ffplay -nodisp -autoexit -f alsa default:CARD=Device /opt/node/lib/node_modules/homebridge-securitysystem/sounds/en-US/current-night.mp3

I'll fix this issue in a new beta tonight.

**Comment by macjl** [comment]
Not better for me : 
```
root@minii5:/opt/node/lib/node_modules/homebridge-securitysystem/sounds/en-US# ffplay -nodisp -autoexit -f alsa default:CARD=Device target-night.mp3 
ffplay version 4.1.6-1~deb10u1 Copyright (c) 2003-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Argument 'target-night.mp3' provided as input filename, but 'default:CARD=Device' was already specified.
```

**Comment by MiguelRipoll23** [comment]
Can you install the latest beta using `sudo npm install -g --unsafe-perm homebridge-securitysystem@beta`, use the `audio_arguments` option either by using the config file or the Homebridge UI and see if it works?

Example:
`audio_arguments: "-f alsa default:CARD=Device"`

Thanks!

**Comment by raixer** [comment]
Can you explain how to add the audio_path parameter in the config or Homebridge UI?

**Comment by macjl** [comment]
Hello. Thank you for this beta, but not working for me : 
```[7/14/2020, 12:11:15 AM] [Security System] Target mode (Night)
[7/14/2020, 12:11:15 AM] [Security System] Audio failed
Argument 'default:CARD=Device' provided as input filename, but '/opt/node/lib/node_modules/homebridge-securitysystem/sounds/en-US/target-night.mp3' was already specified.
```

**Comment by MiguelRipoll23** [comment]
@raixer sure, if you're using using the Homebridge UI go the plugins section

![image](https://user-images.githubusercontent.com/3296866/87359815-ea83d380-c568-11ea-8cf3-b2261c15c866.png)

then expand the `Advanced Options` section and locate the `Audio Arguments` option:

![image](https://user-images.githubusercontent.com/3296866/87359880-1dc66280-c569-11ea-87c9-34a535378ca8.png)

Once we got more information about what's happening I'll tell you what to write there  :P

**Comment by MiguelRipoll23** [comment]
@macjl what's the output when you execute this command?

> ffplay -devices

**Comment by macjl** [comment]
Here is the output : 
```
root@minii5:/opt# ffplay -devices
ffplay version 4.1.6-1~deb10u1 Copyright (c) 2003-2020 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Devices:
 D. = Demuxing supported
 .E = Muxing supported
 --
 DE alsa            ALSA audio output
  E caca            caca (color ASCII art) output device
 DE fbdev           Linux framebuffer
 D  iec61883        libiec61883 (new DV1394) A/V input device D  jack            JACK Audio Connection Kit
 D  kmsgrab         KMS screen capture
 D  lavfi           Libavfilter virtual input device
 D  libcdio          
 D  libdc1394       dc1394 v.2 A/V grab
 D  openal          OpenAL audio capture device
  E opengl          OpenGL output
 DE oss             OSS (Open Sound System) playback
 DE pulse           Pulse audio output
  E sdl,sdl2        SDL2 output device
 DE sndio           sndio audio playback
 DE video4linux2,v4l2 Video4Linux2 output device
 D  x11grab         X11 screen capture, using XCB
  E xv              XV (XVideo) output device
```

**Comment by MiguelRipoll23** [comment]
@macjl okay I think I figured this out:

1. Remove everything from the `Audio Arguments` option.
2. Restart Homebridge.
3. Execute on your terminal: SDL_AUDIODRIVER="alsa" AUDIODEV="hw:**1**,0" ffplay
   (You may need to change the number that comes after hw: until you get your sound card, the one I gave is you is the second one)

Hopefully it works now.

**Comment by macjl** [comment]
You got it!!!

I have added this to my docker-compose, and it's working now : 
```
    environment:
      AUDIODEV: "hw:2,0"
      SDL_AUDIODRIVER: "alsa"
```

So I think you don't have to add the 'audio_arguments' feature in your plugin.

Thank you!

**Comment by MiguelRipoll23** [comment]
Thanks both for your patience on this issue, great to hear that.

@raixer can you connect via SSH to your docker container and do the following steps?

1. Edit your ~/.bashsrc
2. Add the following lines at the end of the file:

> export AUDIODEV=hw:1,0
> export SDL_AUDIODRIVER=alsa

3. Save the file.
4. Try the plugin sounds.

You may need to try hw:2,0, hw:3,0... for it to work as the sound card may have a different identifier, hopefully we fix the issue for you too! :)

**Comment by raixer** [comment]
Oh I have no problems with audio. I am running homebridge on a mac. What I was asking before was about the audio_path. I didn't realize you had added that option in the GUI.

**Comment by MiguelRipoll23** [comment]
Sorry! I meant the author of this issue (@mfischcgn) instead.

Refer to [44#issuecomment-658295471](44#issuecomment-658295471) to solve this issue.

Thank you!

**Comment by raixer** [comment]
@MiguelRipoll23  I was just testing the update today. Took me a while to figure out how to make the custom sounds folder. Had to read the committed code in order to see that I have to have folder 'en-US' inside and the audio file has to follow the same naming convention. But finally got it working.
That info should be added in the documentation tho.

**Comment by MiguelRipoll23** [comment]
@raixer just added these changes to the beta channel:

- Language directory is now automatically created.
- Instructions are added to the `audio_path` directory.
- Updated README & plugin log to reflect the instructions file creation.

My biggest priority has been adding debug messages to the plugin, they're very helpful during testing. I was hoping to improve the documentation and Wiki this week but unfortunately I was quite busy.

Thanks!
