### ISSUE TITLE
ffplay stays running in the background after the first audio plays.

### ISSUE THREAD

**Issue by raixer** [MiguelRipoll23/homebridge-securitysystem#45]
**Describe the bug**
After an audio plays with ffplay, the process stays running in the background. This causes the screensaver on my computer to never activate. (I am using macOS)

**Expected behavior**
ffplay should be run with _-autoexit_ flag in order for the process to exit after playing the sound.

**Comment by raixer** [comment]
As a workaround for now I have added the following command chain of commands to be executed each time I arm or disarm the alarm.
"_sleep 5;pkill ffplay_"

But ideally I shouldn't be killing the process if it already supports _autoexit_.
It should be an easy fix to the code. Just gotta add it to your _options_ variable.

**Comment by MiguelRipoll23** [comment]
Thanks for the bug report and indicating the necessary fix.

Looped sounds will keep the process running and may block the screensaver as well but I'm not sure if there's a workaround for that, will check this out once I'm done with the other issues to confirm.

**Comment by raixer** [comment]
My pleasure. I am really loving this plugin. Greatly simplifies what would otherwise take various plugins to accomplish. The best selling point for me was the webhook and commands options.

**Comment by MiguelRipoll23** [comment]
Thank you for the words 😊

I just published a new beta update with the bugs encountered fixed, you can now try these changes executing the following command on your terminal:

`npm update -g homebridge-securitysystem@beta`

If you're a HOOBS user, please wait until the beta phrase has ended. Remember that you can leave the beta program anytime using the command below:

`npm update -g homebridge-securitysystem@latest`

Thanks!

**Comment by raixer** [comment]
Awesome!  Do I need sudo for that? I am always confused when to use sudo. When I started using hombridge I really messed up the perms all over.

**Comment by MiguelRipoll23** [comment]
Yes, sudo is required.

**Comment by raixer** [comment]
I ran the update but it didn't show anything. And still says v3.0.1

**Comment by MiguelRipoll23** [comment]
Use the following command instead:

sudo npm install -g --unsafe-perm homebridge-securitysystem@beta

**Comment by raixer** [comment]
Awesome! Installed. Trying it out.
