### ISSUE TITLE
saved state isn't working for Home state

### ISSUE THREAD

**Issue by raixer** [MiguelRipoll23/homebridge-securitysystem#46]
**Describe the bug**
I have save state configured. But when I restart homebridge the state goes back to Off.

**To Reproduce**
1. Configure save_state to yes
2. Restart Homebridge
3. Set system to Home
4. Restart Homebridge
5. System is back to Off

**Expected behavior**
State should be preserved across restarts.

**Plugin's configuration**
        {
            "name": "Security system",
            "default_mode": "Off",
            "arm_seconds": 0,
            "show_mode_pause_switch": false,
            "pause_minutes": 0,
            "siren_sensor": false,
            "siren_sensor_seconds": 5,
            "trigger_seconds": 0,
            "reset_minutes": 1,
            "siren_switch": true,
            "siren_mode_switches": false,
            "override_off": false,
            "unsafe_mode_switches": false,
            "hide_mode_off_switch": false,
            "audio": true,
            "audio_language": "en-US",
            "audio_alert_looped": false,
            "save_state": true,
            "webhook_url": "http://api.callmebot.com",
            "webhook_alert": "/start.php?source=web&user=<edited out>",
            "command_current_home": "sleep 5;pgrep -x 'ffplay'>& /dev/null; if [ $? -eq 0 ]; then pkill ffplay;fi",
            "command_current_away": "sleep 5;pgrep -x 'ffplay'>& /dev/null; if [ $? -eq 0 ]; then pkill ffplay;fi",
            "command_current_night": "/usr/local/Cellar/switchaudio-osx/1.0.0/SwitchAudioSource -s \"Built-in Output\";sleep 5;pgrep -x 'ffplay'>& /dev/null; if [ $? -eq 0 ]; then pkill ffplay;fi",
            "command_off": "/usr/local/Cellar/switchaudio-osx/1.0.0/SwitchAudioSource -s \"HDMI\";sleep 5;pgrep -x 'ffplay'>& /dev/null; if [ $? -eq 0 ]; then pkill ffplay;fi",
            "accessory": "security-system"
        }

**Comment by raixer** [comment]
Actually. It works for "Away" & "Night" modes.
If system is in "Home" mode it will go back to Off after restart.

**Comment by raixer** [comment]
@MiguelRipoll23  the state isn’t getting preserved across homebridge restarts. I tried it with Away mode. I haven’t tried it with any other modes yet.

**Comment by MiguelRipoll23** [comment]
I thought the latest version was bug free 😁

I revamped the code that handles the options a few weeks ago to be able to add new features easily, turns out I missed to load the `save_state` option from the configuration.

I just fixed it in a beta release but I will publish it to the release channel in a few hours.

Thanks for reaching back to me about this issue 👍
