### ISSUE TITLE
"current mode: Off" command is getting executed every time

### ISSUE THREAD

**Issue by raixer** [MiguelRipoll23/homebridge-securitysystem#47]
**Describe the bug**
If my current mode is Off and I use Shortcuts to set mode to Off the command associated to "current mode off" gets executed regardless.

**To Reproduce**
It is best to set a Shortcut to control the security system to off in order to reproduce this issue

**Expected behavior**
The command shouldn't be executed if my current mode is already Off.

**Plugin's configuration**
{
"name": "Security system",
"default_mode": "Off",
"arm_seconds": 0,
"show_mode_pause_switch": false,
"pause_minutes": 0,
"siren_sensor": false,
"siren_sensor_seconds": 5,
"trigger_seconds": 0,
"reset_minutes": 1,
"siren_switch": true,
"siren_mode_switches": false,
"override_off": false,
"unsafe_mode_switches": false,
"hide_mode_off_switch": false,
"audio": true,
"audio_language": "en-US",
"audio_alert_looped": false,
"save_state": true,
"webhook_url": "http://api.callmebot.com",
"webhook_alert": "/start.php?source=web&user=",
"command_current_home": "sleep 5;pgrep -x 'ffplay'>& /dev/null; if [ $? -eq 0 ]; then pkill ffplay;fi",
"command_current_away": "sleep 5;pgrep -x 'ffplay'>& /dev/null; if [ $? -eq 0 ]; then pkill ffplay;fi",
"command_current_night": "/usr/local/Cellar/switchaudio-osx/1.0.0/SwitchAudioSource -s "Built-in Output";sleep 5;pgrep -x 'ffplay'>& /dev/null; if [ $? -eq 0 ]; then pkill ffplay;fi",
"command_off": "/usr/local/Cellar/switchaudio-osx/1.0.0/SwitchAudioSource -s "HDMI";sleep 5;pgrep -x 'ffplay'>& /dev/null; if [ $? -eq 0 ]; then pkill ffplay;fi",
"accessory": "security-system"
}

**Comment by raixer** [comment]
Here is a log:

[7/3/2020, 10:28:45 AM] [Security system] Target mode (Off)
[7/3/2020, 10:28:45 AM] [Security system] Current mode (Off)
[7/3/2020, 10:28:51 AM] [Security system] Command output: output audio device set to "HDMI"

[7/3/2020, 10:34:24 AM] [Security system] Target mode (Off)
[7/3/2020, 10:34:29 AM] [Security system] Command output: output audio device set to "HDMI"

**Comment by raixer** [comment]
Perhaps a "Target mode: Off" should be added if someone wants to retain the function of executing a command every time the Off is set.

**Comment by MiguelRipoll23** [comment]
The reason of why a `Target mode: Off` event doesn't exist is because there's no delay to disarm the security system so the `Current mode: Off` event and mode are fired immediately.

This is intended behavior as adding a delay to disarm the security system didn't make sense to me from my perspective, I'm open to discuss and change the implementation though!

**Comment by raixer** [comment]
I am thinking it more like, if someone wants to execute a webhook/command when target is set to Off regardless that the current mode is already Off. 
And then you have those, like me, who want to execute the webhook/command only when the current mode transitions to the Off state.

**Comment by MiguelRipoll23** [comment]
That's a little bit tricky as lot of actions are done when a mode is changed or in this case repeated.

This is what would happen:

1. Target is set to Home.
2. Security system begins to arm.
3. Target is set to Home again (it has no finished arming from step 2)
4. Security system stops arming (it thinks the mode has changed and a new arming countdown will be next)
5. As the target mode is already the current mode, the new arming countdown is not started.
6. Security system is now indefinitely stuck `Arming...`

Not sure if worth it as it's a very sensitive area to omit certain actions based on different conditions and could make the plugin very unstable.

Is the use case very important?

**Comment by raixer** [comment]
For me it is not important. I was just giving it as an idea for whoever wanted that. But I don't need that function at this moment.
I do get what you mean for the arming scenario tho. I didn't think about that part.
