### ISSUE TITLE
Critical alerts aren’t audible on Sleep Focus

### ISSUE THREAD

**Issue by addisonjames** [MiguelRipoll23/homebridge-securitysystem#473]
### Plugin version

7.5.1

### Plugin configuration

Use Away and Night modes.

### Homebridge version

1.6.1

### What's your question?

Critical Alarm notifications work great on any focus but Sleep. When my phone is on Sleep focus, the critical notification doesn’t make noise. 
In my sleep focus settings I have Home app allowed on the app list, as well as “allow critical notifications” checked. 
What’s wrong wrong here? 

running iOS 16.5.1

**Comment by MiguelRipoll23** [comment]
Hey there @addisonjames,

I'm afraid this is something the plugin can't control. Apple finally implemented the security system notifications as critical not very long ago but still misses important behaviors like the one you're reporting. It should bypass the Sleep focus so I'd consider reporting this as a feature suggestion to Apple.
