### ISSUE TITLE
Different commands/webhooks on alert depending on the mode

### ISSUE THREAD

**Issue by raixer** [MiguelRipoll23/homebridge-securitysystem#48]
I understand "Siren Mode Switches" is a handy way to trigger an alarm only when the system is on that specific state. I actually have no need for that because I am using native Homekit support for setting a condition in which I first evaluate the current security system state before executing the action.
However, it would be really useful if the "Siren Mode Switches" also had different webhook or commands associated to them instead of always executing the same alert as the global Siren switch.

That way I could have different alert behaviors depending on the mode.

**Comment by raixer** [comment]
And while you are at it. Also make the play sound conditionally to the mode. So for example, if I am in Home mode I could run a specific command automatically but play no sound when the siren is triggered.

**Comment by MiguelRipoll23** [comment]
Seems like a great addition.

One of the things I try to do is to avoid creating lot of options that could scare easily new users by making the implementation as simple as possible.

Things we can do here:

- Pass the current selected mode as a parameter to webhook events.
  **Example:** ?currentMode=home
- Pass the current selected mode as a optional parameter to command events.
  **Example:** echo current mode is ${currentMode}
  **After transformation is done:** echo current home is home

What do you think? This way you can do the logic with the current selected mode more freely.

**Comment by raixer** [comment]
Yes that would work for me. 
Btw, I just tested the update and it is working perfectly.

**Comment by MiguelRipoll23** [comment]
That's awesome.

I need to do some heavy testing pf the previous changes until tomorrow to confirm that nothing is broken as some parts of the code are very sensitive, once I'm done with it I'm going to start the work on this. There would be another beta update so we can discuss if the implementation fits your needs before it's released to the general public.

Thank you!

**Comment by MiguelRipoll23** [comment]
I just published a new beta release with these changes:

- Added the ability to disable sounds by renaming the file (example: current-home-disabled.mp3).
- Added ${currentMode} parameter to command events (example: echo mode ${currentMode} set).
- Added ${currentMode} parameter to webhook events (example: ?modeSet=${currentMode}&hello=true).

It's **highly recommended** that you update to this version soon as possible as an issue when cancelling the alarm has been found on the v3.0.2 beta:

`npm install -g homebridge@beta`

As always, continue the discussion here if the implementation for these changes suggested don't fit your needs yet.

Thanks!

**Comment by raixer** [comment]
oh that was fast!  I will give it a try.  Thank you

**Comment by raixer** [comment]
Pretty good. One thing I noticed tho was that now with the new current-alert.mp3 it plays at the same time as current-triggered.mp3 when you have trigger_seconds set to 0. I disabled current-alert.mp3 so no big deal.
The other thing is that when I change to Off I lose the context of which mode it was previously set on. So if I had done something special for a specific mode that needs to be reverted when the mode changes to Off then I can't do that.

**Comment by raixer** [comment]
Just so you get a context on how I am using this. Instead of using the included webhook option I put the webhook request as a command because that was the only way I could differentiate if I needed to send the request or not:

            "command_alert": "if [  ${currentMode} == night ]; then echo 'Contacted Telegram'; (curl -s -o /dev/null 'http://api.callmebot.com/start.php?source=web&user=(edited)' &) ;fi",

That is working great. Altho, as a minor observation, for some reason the echo doesn't show in the logs until the curl command is completed.

**Comment by MiguelRipoll23** [comment]
> One thing I noticed tho was that now with the new current-alert.mp3 it plays at the same time as current-triggered.mp3 when you have trigger_seconds set to 0

I missed that one, my bad.

> The other thing is that when I change to Off I lose the context of which mode it was previously set on.

This means I need to add `webhook_target_off` and `command_target_off`, maybe we need to deprecate the current one and add the `current` prefix like the other ones to to keep it consistent.

I'll do some changes and see how it ends up.

Thanks for testing.

**Comment by MiguelRipoll23** [comment]
I just published a new beta release with these changes:

- Added current/target webhook and command options for Off mode. *.
  Now you should be able to receive the previous mode when setting the `Off` mode :)
- Fixed alert sound event playing when trigger_seconds is set to zero **
  Can you revert the workaround and see if it's completely fixed, now?

Thanks!

**Comment by raixer** [comment]
So far working good. 
Also when I installed the new version the audio files reverted back to the original. That is handy if I delete the audio file by mistake but will it do the same if I do update instead of install?

**Comment by MiguelRipoll23** [comment]
Not quite sure but probably.

I'll add an option to separate custom sounds/disabled ones from the original ones so they don't get overwritten, I didn't contemplate this so thanks again for reporting it.

**Comment by MiguelRipoll23** [comment]
I published another beta update with the option for custom sounds so they don't get overwritten or restored when the plugin is updated.

When this option is enabled the filename needs to have a `-custom` suffix before `.mp3` like these examples:

- current-home-custom.mp3
- target-home-custom.mp3
- triggered-custom.mp3

**Comment by raixer** [comment]
Excellent! working good here. With custom audio. I only put triggered as custom so that is the only audio that plays.
After a while here is what I ended up with:

            "command_target_off": "mode=${currentMode}; if [[ $mode == \"night\" || $mode == \"triggered\" ]]; then SwitchAudioSource -s \"HDMI\"; fi",
            "command_current_night": "SwitchAudioSource -s \"Built-in Output\"",
            "command_alert": "if [ \"${currentMode}\" == \"night\" ]; then echo 'Contacted Telegram'; (curl -s -o /dev/null 'http://api.callmebot.com/start.php?source=web&user=(edited out)'); else pkill ffplay; ntfy -t 'Alarm' send 'Alarm triggered'; fi",

The logic is that it will only play triggered sound & give me a call via Telegram when the mode is set to Night, otherwise it will send me a notification via Pushover which I have configured as priority 1 to bypass my Do Not Disturb on my phone.

**Comment by MiguelRipoll23** [comment]
I’m amazed by the things you guys do 😃

The way you’re doing it is correct when you don’t have control of the webhook server, also that is pretty nice as iOS is (at the moment) blocking alarm triggered notifications during Do Not Disturb mode.

By the way, you told me earlier that you observed that the output from the command wasn't live. Would you like to make it live?

**Comment by raixer** [comment]
Doesn't matter to me really. Perhaps the only time it would be an issue is when I turn Off the alarm before the command is finished. Then in the logs you see that "Contacted Telegram" after the current mode has changed to Off instead of right after it went into Triggered mode.
