### ISSUE TITLE
Default security mode

### ISSUE THREAD

**Issue by gaojie429** [MiguelRipoll23/homebridge-securitysystem#5]
Everytime I restart the homebridge, this plugin set the security mode to "off". 
However, I want change the default mode to "at home".
Any solution for this?

**Comment by MiguelRipoll23** [comment]
Sure but I'll have to implement it 😛

Do you want the state to be saved locally or prefer to have an option on the Homebridge configuration to set the default mode to whatever you want?

**Comment by gaojie429** [comment]
Thanks!!
I want the latter feature: set the default mode on the homebridge config file.

**Comment by MiguelRipoll23** [comment]
Use the command `npm update -g` to update your global packages or install the latest update as I just released a new version that adds the default mode option on the Homebridge configuration file. Please check the documentation on the sample-config file that you can find on this repository.

Thanks for the suggestion!

**Comment by gaojie429** [comment]
Wow, so fast!!
Thank you again!!
