### ISSUE TITLE
Only for understanding

### ISSUE THREAD

**Issue by Christian-CFP** [MiguelRipoll23/homebridge-securitysystem#50]
Hi Miguel,
so only for understanding. Can you give me a example of how maybe to use the "sensor" while trigger?
So that I can understand better for what I could use this feature.

**Comment by raixer** [comment]
I am using it in homekit to send an alert to Pushover every 15 seconds.

**Comment by Christian-CFP** [comment]
Ok, so this sensor is "active" when the trigger is active too? Or even after the siren kicks in?

**Comment by raixer** [comment]
when the siren kicks in the sensor "detects motion" and it will "detect motion" again every x interval you have specified. It does this until the siren or the security system have been turned off.

**Comment by Christian-CFP** [comment]
Oh, now I got it. Thank you.

**Comment by raixer** [comment]
Actually let me correct... When the siren kicks in, the sensor will wait the interval you have specified before it "detects motion". Then it will wait the interval again to "detect motion"

**Comment by raixer** [comment]
What I did in order to send a Pushover notification as soon as the siren kicks in, I have made an automation for when Siren is turned on. Then I have another automation for when the sensor "detects motion".

**Comment by Christian-CFP** [comment]
I see. Thanks for helping me out.
I still wait until Apple get us more rights to play with notifications in HK.
Still playing with iOS 14 but nothing in beta 2....

**Comment by MiguelRipoll23** [comment]
@raixer thanks for helping me out!

I've submitted to Apple Feedback Assistant a suggestion to improve the behavior of the security system notifications some time ago, they should skip Do Not Disturb and Sleep modes, especially the triggered one. Unfortunately, nothing has changed yet hopefully they add more control. 

Let's see what happens in a few months.
