### ISSUE TITLE
Siren Reset Question

### ISSUE THREAD

**Issue by johnnygeezz** [MiguelRipoll23/homebridge-securitysystem#51]
In a typical Siren Triggered situation, a Homekit Scene is triggered to turn lights on, etc. With the reset feature, how do you suggest resetting or returning those devices (lights etc) turned on to their initial state (likely off)? Should there be a secondary scene called 'Restore' to reset the lights to their off state? How would you handle?

**Comment by MiguelRipoll23** [comment]
I'd create an automation on the Home app for when the `Siren` switch turns off that turns off every light that was turned on when triggered.

Restoring them to their previous state is at the moment not possible on any HomeKit app but it would be a nice addition.

**Comment by johnnygeezz** [comment]
Yes. That's what I thought. Was just curious how you'd handle it. Thanks.
