### ISSUE TITLE
No alarm notification when iphone network connection restore

### ISSUE THREAD

**Issue by graupe95** [MiguelRipoll23/homebridge-securitysystem#523]
### Plugin version

8.0.2

### Plugin configuration

"name": "Alarmanlage",
            "serial_number": "S3CUR1TYSYST3M",
            "default_mode": "Away",
            "arm_seconds": 30,
            "trigger_seconds": 0,
            "reset_minutes": 10,
            "save_state": false,
            "proxy_mode": false,
            "test_mode": false,
            "trip_switch_name": "Trip",
            "trip_home_switch_name": "Trip Home",
            "trip_away_switch_name": "Trip Away",
            "trip_night_switch_name": "Trip Night",
            "trip_override_switch_name": "Trip Override",
            "mode_home_switch_name": "Mode Home",
            "mode_away_switch_name": "Mode Away",
            "mode_night_switch_name": "Mode Night",
            "mode_off_switch_name": "Mode Off",
            "mode_away_extended_switch_name": "Mode Away Extended",
            "mode_pause_switch_name": "Mode Pause",
            "audio_switch_name": "Audio",
            "away_arm_seconds": 30,
            "override_off": false,
            "reset_off_flow": false,
            "double_knock": false,
            "double_knock_seconds": 90,
            "double_knock_modes": [
                "Home",
                "Night",
                "Away"
            ],
            "tripped_sensor": true,
            "tripped_sensor_seconds": 5,
            "siren_sensor": true,
            "siren_sensor_seconds": 5,
            "reset_sensor": false,
            "mode_switches": true,
            "mode_off_switch": true,
            "mode_away_extended_switch": false,
            "mode_pause_switch": false,
            "pause_minutes": 0,
            "arming_lock_switch": false,
            "arming_lock_switches": false,
            "siren_switch": true,
            "siren_override_switch": true,
            "siren_mode_switches": true,
            "audio_switch": false,
            "audio": true,
            "audio_language": "de-DE",
            "audio_volume": "100",
            "audio_arming_looped": false,
            "audio_alert_looped": false,
            "_bridge": {
                "username": "0E:2E:C6:46:7E:2B",
                "port": 33409
            },
            "accessory": "security-system"

### Homebridge version

1.7.0

### What's your question?

Hello all,

last week my girlfriend came home and forgot to disarm the security system. The alarm was triggered. Her iPhone got the alarm message.
I was at work in a basement without any mobile connection. 
when my connection was restored she texted me it was her fault she triggered the alarm by openinh the door.
My iPhone does not have a missed notification about the alarm.

is that a configuration issue?
I think i should have get a notification but delayed but there was nothing.

can you help?
Thanks!

**Comment by graupe95** [comment]
Can somebody help?

**Comment by MiguelRipoll23** [comment]
Hey @graupe95,

Push notifications are only managed by the internal framework called HomeKit so plugin can't deliver notifications on their own. My understanding was that notifications ended up delivered once your're back online, if that's not the case you probably have to submit feedback to Apple.
