### ISSUE TITLE
How to connect to bluetooth speaker from HB security plugin

### ISSUE THREAD

**Issue by Santai65** [MiguelRipoll23/homebridge-securitysystem#525]
### Plugin version

V8.1.0

### Plugin configuration

Hi Miguel

thank you for the awesome security plugin.  I am a novice so please excuse my basic questions. I have got the plug in running with a very basic configuration  and can see it in my Home kit App.  

### Homebridge version

1.7.0

### What's your question?

I have connected a speaker directly to the audio port on my rp4 and cab hear the audio associated with switching the security system (via HomeKit ) through the Home, Away, Night and Off mode.  I would now like to replace the hardwired speaker with a blueetooth Wonderboom speaker.  I loaded the plugin and have read through the various help tutorials available but cant get it working.

The first issue I am stuck with is finding the Bluetooth Mac address of the speaker but cant find it- I am on window 11.  Are you able to point me in the right direction please?

Many thanks

**Comment by MiguelRipoll23** [comment]
Hey there,

Have you tried to use the Device Manager, select the device and go to the Details tab. From there you should be able to get it.

Also, if you prefer a simpler setup and you have either a HomePod or AirPlay speaker, you can do this natively on the Home app if you want.

**Comment by Santai65** [comment]
Hi Migeul,

Thanks for your reply.  I can't find it in Device Manager but will try your other suggestion using a Home pod or Airplay speaker

**Comment by Santai65** [comment]
Hi Miguel,

Yes please close this issue.  i am still working on the door switches with the guidance you recently gave me.

many thanks

Duncan
________________________________
