### ISSUE TITLE
Arm seconds ignored

### ISSUE THREAD

**Issue by CooperCGN** [MiguelRipoll23/homebridge-securitysystem#53]
Hi,

I only realized it today but since one of the latest updates the “arm_seconds” parameter seems to completely get ignored. I have set it to 30 seconds but whenever I change the alarm status it skips the arming phase completely and switches modes directly. I already removed the accessory and added it again but nothing changed. Any idea why this might be happening?

`{            "name": "Security system",            "default_mode": "Off",            "arm_seconds": 30,            "show_mode_pause_switch": false,            "pause_minutes": 0,            "siren_sensor": false,            "siren_sensor_seconds": 5,            "trigger_seconds": 0,            "reset_minutes": 3,            "siren_switch": true,            "siren_mode_switches": false,            "override_off": false,            "unsafe_mode_switches": false,            "hide_mode_off_switch": false,            "audio": false,            "audio_volume": "100",            "audio_language": "en-US",            "audio_alert_looped": false,            "save_state": true,            "accessory": "security-system"        } `

**Comment by MiguelRipoll23** [comment]
Can you set the save_state to false, restart the plugin and try again to see if it works?

Also, do you use Siri? It could be related as it may have turn off the delay option.

**Comment by CooperCGN** [comment]
Removing save state actually fixed it.

**Comment by MiguelRipoll23** [comment]
It may have saved the state incorrectly, that's weird.

Check your Homebridge Persist directory and remove the directory named `homebridge-securitysystem` to clear all the saved data from the plugin so you can still use the `save_state` option with no issues.

rm -rf ~/.homebridge/persist/homebridge-securitysystem

**Comment by CooperCGN** [comment]
Maybe it’s because I only used the off and away mode first and then later added night and home mode.
