### ISSUE TITLE
How to have a single trip switch?

### ISSUE THREAD

**Issue by rvaneeuwijk** [MiguelRipoll23/homebridge-securitysystem#535]
### Plugin version

8.1.1

### Plugin configuration

{
    "accessories": [
        {
            "name": "Home Security System",
            "arm_seconds": 0,
            "trigger_seconds": 0,
            "reset_minutes": 10,
            "home_arm_seconds": "null",
            "night_arm_seconds": "null",
            "away_arm_seconds": 30,
            "home_trigger_seconds": "null",
            "night_trigger_seconds": "null",
            "away_trigger_seconds": 30,
            "away_extended_trigger_seconds": "null",
            "double_knock_seconds": 90,
            "home_double_knock_seconds": "null",
            "away_double_knock_seconds": "null",
            "night_double_knock_seconds": "null",
            "disabled_modes": [
                "Night"
            ],
            "tripSwitch": true,
            "tripped_sensor": false,
            "trippedMotionSensor": false,
            "tripped_sensor_seconds": 5,
            "siren_sensor_seconds": 5,
            "pause_minutes": 0,
            "audio_volume": 100,
            "accessory": "security-system",
            "plugin_map": {
                "plugin_name": "homebridge-securitysystem"
            }
        }
    ]
}

### Homebridge version

1.7.0

### What's your question?

In the FAQ you write: "You can disable the Show Trip Mode Switches option under the switches section from the plugin settings and enable the global Trip switch with the option Show Trip Switch." I want to do this.

I tried adding various lines (e.g. "Show_Trip_Mode_Switches": false, "Show_Trip_Switch": true, "Trip_Switch": true) in the config file, but that I always end up with two separate trip switches for the two enabled modes (present and away). What are the lines I should add to the config file to have only one, global trip switch?

Note: I am using "Advanced" configuration on HOOBS.

Thanks,

Remco

**Comment by rvaneeuwijk** [comment]
I've found the solution using the field names and descriptions in the json file. To remove the trip switches for each mode, you need to set "siren_mode_switches": false. And to have a single trip switch for all modes, you need to set "siren-switch": true.

Tip: Would be really user friendly if you could ensure consistency between field names in your FAQ and the json file.

**Comment by MiguelRipoll23** [comment]
Hey there,

In order to show the global trip switch, you either have to enable the `Show Trip Switch` or use the JSON config:

```js
siren_switch: true
```

Finally, hide the trip mode switches disabling the option `Show Trip Mode Switches` or use JSON config:

```js
siren_mode_switches: false
```

That should work for you 💯

**Comment by MiguelRipoll23** [comment]
JSON field names will be fixed in the next release.
