### ISSUE TITLE
Feedback wanted

### ISSUE THREAD

**Issue by MiguelRipoll23** [MiguelRipoll23/homebridge-securitysystem#54]
Hello, everyone!

I'd like to hear some feedback from you about the usage of this plugin and your daily inconveniences or struggles that you may be experiencing when using it.

I'd appreciate so much if some of you did [this quick survey](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAN__s-Yyv5UMjVUME81QjdZRE9KSUhDSkNJVDVaN1pKNi4u) to improve any area that hasn't been mentioned yet.

### The journey
During last months and even weeks, lot of things have happened! These are some highlights of the new features that have arrived to this plugin:

**Settings UI:** it's easier than ever to change the plugin's settings using either Homebridge or HOOBS with the organized sections that were added.

**Audio**: this was implemented originally but its support was worse than expected and had to be removed but recently it has been brought back with a more supported and even better implementation.

**Test mode**: some users have connected this plugin to services that provide monitoring or send alerts to other devices using the webhook/command features and a way to reduce false alarms had to be added.

### Not possible? No problem
The procedure for unsupported features has changed, if the feature that you have requested is limited by HomeKit a label `unsupported` will be added to it and it'll be put on the roadmap anyways so the moment the limitations are over the feature can be added to the plugin.

### No more f#%k-ups
Every weekend I tried to improve this plugin internally as much as I can, every improvement meant higher stability and less time to add newly requested features, this is what happened:  

- Code was improved, **a lot**.
- Debug messages were added to troubleshoot issues.
- Reset mechanism was added to clear saved data (option `test_mode`).

Hopefully you all enjoying all the new features and are quite satisfied with the plugin, thank you for being an user and contributing to improve it during all this time and continuing to do so.

**Comment by 0ldF0x** [comment]
Congrats on the support, good job. But I think that you should do some refactoring there. Currently all your code is in one file with 1500+ lines of code. Break that file into separate modules...

**Comment by MiguelRipoll23** [comment]
@0ldF0x working on that! There's a branch named `alpha` where the TypeScript migration has begun but right now it's paused until some new stuff from Homebridge arrives so I can add all the custom characteristics that I use for the most adventurous users that would like to hide the switches.

Code refactoring is still happening at this moment on that big file, so the moment this code ends up migrated the quality of the code would be quite good.

**Comment by 0ldF0x** [comment]
Great👍 keep up the good work 🙂
