### ISSUE TITLE
Simple configiration of parameters in Homesecurity

### ISSUE THREAD

**Issue by Santai65** [MiguelRipoll23/homebridge-securitysystem#540]
### Plugin version

8.1.1

### Plugin configuration

Default down load configuration

### Homebridge version

1.7.0

### What's your question?

Hi Miguel

I am an absolute novice (who is very eager to learn!) making slow but steady progress with my alarm system using your plug in (Rp4 + Homebridge + Homesecurity) 
Are you able please to share some sample configs (via the GUI) that will execute on the following automation  examples as shown 
on your GitHub site 

Trigger | Actions
-- | --
Motion is Detected | Turn on Trip Night
Door is Opened | Turn on Trip Away

I have been struggling to understand the basic concepts of Modes, Switches  etc in the Home security plug in.  I have read through all the documents available.  However I am sure that with an example of the configs to execute on each of the above I will be able to improve my understanding of how things work and then do my own automation.

Many thanks for your help and patience 

Duncan

**Comment by MiguelRipoll23** [comment]
Hey,

No problem, you have to create the automations using the Home app installed by default in iOS.

This is a screen recording where I create an automation that when my motion sensor detects motion, it turns on the "Trip Away" switch.

https://github.com/MiguelRipoll23/homebridge-securitysystem/assets/3296866/d11a0801-c57e-4682-acc1-96b0a40bdc26

If my security system is set to the Away mode, then it will trip the security system and trigger it.

Trip switches are for tripping the security system. Mode switches are for bypassing HomeKit limitations in order to for example set the security system mode to away when leaving.

Feel free to ask more questions

**Comment by Santai65** [comment]
Hi Miguel,

Thank you so much for your patience and time.  I tried what you suggested on my system and it works !!!.  Now that I have this simple "hoe to do" information that you shared with me, I will continue to build my system.

Thanks once again.

I hope that it is ok if I come back to you with any more questions :)

**Comment by MiguelRipoll23** [comment]
Totally fine, you can use this issue to keep posting questions I will answer as soon as possible.
Thanks!

**Comment by Santai65** [comment]
Thank you MiguelSent from my iPhoneOn 23 Mar 2024, at 10:28 pm, Miguel Ripoll ***@***.***> wrote:﻿
Totally fine, you can use this issue to keep posting questions I will answer as soon as possible.
Thanks!

**Comment by Santai65** [comment]
Hey Miguel,

Sorry to bother you again!

I have configured on/off button to arm my security system now with a delay of 30 seconds - works fine. Instead of getting the standard "arming security system " message.  Instead of this message, I would like to add a .wav file of my own that plays via a connected speaker for the 30 seconds' delay.  Could you please provide me with some guidance as to how I achieve this?  

Many thanks for your patience.

Duncan

**Comment by Santai65** [comment]
Hey Miguel,

 

Thanks for your patience… I am nearly there.  I have put the AlarmOn sound (AlarmOn.mp3)  as shown below

***@***.***:~/my-sounds-directory/en-US $ ls

AlarmOn.mp3

***@***.***:~/my-sounds-directory/en-US $

 

However, when I try to follow your commands

 

*  Execute: sudo apt update , I get the following error

 

 

***@***.***:~ $ sudo apt update

sudo: unable to resolve host Homebridge228: Name or service not known

Hit:1 https://repo.homebridge.io stable InRelease

Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease                                                                         

Hit:3 http://raspbian.raspberrypi.org/raspbian bullseye InRelease

Reading package lists... Done

Building dependency tree... Done

Reading state information... Done

76 packages can be upgraded. Run 'apt list --upgradable' to see them.

 

*  Execute: sudo apt install ffmpeg

 

***@***.***:~ $ sudo apt install ffmpeg

sudo: unable to resolve host Homebridge228: Name or service not known

Reading package lists... Done

Building dependency tree... Done

Reading state information... Done

ffmpeg is already the newest version (8:4.3.6-0+deb11u1+rpt5).

0 upgraded, 0 newly installed, 0 to remove and 76 not upgraded.

 

I then tried to update /etc/hosts file as follows, but cannot have access to map 127.0.0.1 to Homebridge 228

 

 


I am sorry to keep bothering you, however, I am trying to learn how to use your great pguin

 

Thanks for your help

 

Duncan

**Comment by Santai65** [comment]
Hey Miguel

 

I have managed to fix the problem and installed ffmpeg below by doing some more research 😊

 

Here is the result. 

 

***@***.***:/var/lib/homebridge $ sudo apt install ffmpeg

Reading package lists... Done

Building dependency tree... Done

Reading state information... Done

ffmpeg is already the newest version (8:4.3.6-0+deb11u1+rpt5).

0 upgraded, 0 newly installed, 0 to remove and 76 not upgraded.

***@***.***:/var/lib/homebridge $

 

 

This is where the mp3 AlarmOn file is

***@***.***:/var/lib/homebridge $ cd /home/duncan/my-sounds-directory/en-US

***@***.***:~/my-sounds-directory/en-US $ ls

AlarmOn.mp3  en-US

 

This is the config in the plugin:

 



 

Unfortunately, the custom sound does not play when I arm the system ☹

 

Cheers

 

Duncan

 

 

From: Duncan Wallace ***@***.***> 
Sent: Saturday, March 30, 2024 8:49 PM
To: 'MiguelRipoll23/homebridge-securitysystem' ***@***.***>
Subject: RE: [MiguelRipoll23/homebridge-securitysystem] Simple configiration of parameters in Homesecurity (Issue #540)

 

Hey Miguel,

 

Thanks for your patience… I am nearly there.  I have put the AlarmOn sound (AlarmOn.mp3)  as shown below

***@***.***:~/my-sounds-directory/en-US $ ls

AlarmOn.mp3

***@***.***:~/my-sounds-directory/en-US $

 

However, when I try to follow your commands

 

*  Execute: sudo apt update , I get the following error

 

 

***@***.***:~ $ sudo apt update

sudo: unable to resolve host Homebridge228: Name or service not known

Hit:1 https://repo.homebridge.io stable InRelease

Hit:2 http://archive.raspberrypi.org/debian bullseye InRelease                                                                         

Hit:3 http://raspbian.raspberrypi.org/raspbian bullseye InRelease

Reading package lists... Done

Building dependency tree... Done

Reading state information... Done

76 packages can be upgraded. Run 'apt list --upgradable' to see them.

 

*  Execute: sudo apt install ffmpeg

 

***@***.***:~ $ sudo apt install ffmpeg

sudo: unable to resolve host Homebridge228: Name or service not known

Reading package lists... Done

Building dependency tree... Done

Reading state information... Done

ffmpeg is already the newest version (8:4.3.6-0+deb11u1+rpt5).

0 upgraded, 0 newly installed, 0 to remove and 76 not upgraded.

 

I then tried to update /etc/hosts file as follows, but cannot have access to map 127.0.0.1 to Homebridge 228

 

 


I am sorry to keep bothering you, however, I am trying to learn how to use your great pguin

 

Thanks for your help

 

Duncan

**Comment by MiguelRipoll23** [comment]
You're almost there, no worries.

You must rename the `AlarmOn.mp3` file to `target-home.mp3`, the moment you do this without any additional actions you should listen to the sound when arming the Home mode. If you want the sound to play when the Home mode is already armed you should name your file `current-home.mp3`.

Now let's say you want to play the sound when arming the Home, Away and Night modes, you should then duplicate your sound file 3 times and name them like this: `target-home.mp3`, `target-away.mp3` and `target-night.mp3`.

That will do it 💯

**Comment by Santai65** [comment]
YES !!! it worked you are a star developer and mentor , Miguel.  Thank you.

 

I can now progress to the next stage of building my HomeBridge-security system .  If you don’t mind, I may ask a few more questions as I progress.

 

Many thanks

 

Duncan

**Comment by MiguelRipoll23** [comment]
That's great to hear, glad to help.

BTW, are you from Australia by any chance?

**Comment by Santai65** [comment]
Yes I am Miguel, have you been here!Sent from my iPhoneOn 31 Mar 2024, at 7:17 pm, Miguel Ripoll ***@***.***> wrote:﻿
That's great to hear, glad to help.
BTW, are you from Australia by any chance?

**Comment by MiguelRipoll23** [comment]
I just wanted con confirm it was actually you 🙂

Thanks for supporting. Will issue a refund for the second donation as I am glad to help and don't mind helping at all. If life gets busier I probably would be able to answer in a few days top.

Feel free to ask all the questions you want in here, for real. This was my hobby project and I'm happy that it's useful for others.

Thanks again!

**Comment by Santai65** [comment]
Please don’t as I wanted to sponsor you in return for the good work you doSent from my iPhoneOn 31 Mar 2024, at 7:39 pm, Miguel Ripoll ***@***.***> wrote:﻿
I just wanted con confirm it was actually you 🙂
Thanks for supporting. Will issue a refund for the second donation as I am glad to help and don't mind helping at all. If life gets busier I probably would be able to answer in a few days top.
Feel free to ask all the questions you want in here, for real. This was my hobby project and I'm happy that it's useful for others.
Thanks again!

**Comment by Santai65** [comment]
Hey Miguel,

How are you?.

I am making good progress with my HomeBridge alarm - thanks to your help 🙂.

I have mapped out what I want to achieve ( see attached)

So, my Alarm system will consist of:


  *
HomeBridge as the platform
  *
 3 x Eva door sensors (Homekit enabled)
  *
1 x Strobe light (controlled via HomeKit enabled smart plug)
  *
1 x Siren (controlled via HomeKit enabled smart plug)
  *
On / Off switch Philips Hue (HomeKit enabled) to turn the alarm On and Off
  *
Powered speaker connected to rp4 (running Homebridge) to play various alarm audio eg Alarm On , Alarm off

In the flow diagram attached, I have achieved the areas shaded in blue.  Could you please provide me with some guidance as to how I can configure the various HomeBridge parameters to achieve the other areas in the flow diagram?

If you have any questions, please feel free to ask me.

Many thanks

Duncan
________________________________

**Comment by MiguelRipoll23** [comment]
Hey @Santai65,

Sure, could you attach the image again in a new comment? Looks like GitHub failed to upload it in your previous comment.

**Comment by MiguelRipoll23** [comment]
I've been studying your diagram, nice work by the way.

Here's some instructions based on what I've interpreted from your attached image.

**Main Door Open**

Create an automation in the Home app using the event "when a sensor detects something", choose your contact sensor for the main door and the action would be to turn on the trip switch (either the global one called "Trip" or one containing a mode). This automation will play the alarm triggered when opening the door after the delay if not disarmed.

**Back Door Open / Family Door Open**

You want to trigger the security system immediately with no delay, right? I've thought some long ago to add a "panic switch" that does this, however the idea was discarded to avoid turning it on accidentally either using the UI or Siri. My recommendation would be to keep the delay even for sensitive zones for avoiding false alarms triggered physically or virtually but a new optional switch that implements the idea could be added if you really need it.

To sound the siren and flash some lights connected to a smart plug when the security system has been triggered, you would have to create an automation inside the Home app using the event "when an accessory is controlled", choose the security system, pick "when the security system is triggered" and finally turn on the smart plug as your action.

_Note:_ I see that you want to flash the lights and make the siren sound only if the security system has been triggered by opening any door except the main one however this kind of condition is quite a complex one. Converting the automation to a shortcut to check if the main door is closed to turn on the smart plug could maybe work this out.

**Alarm switch off**

Create an automation using the event "when an sensor detects something", pick the triggered reset sensor and turn off the smart plug as an option (note: enable the triggered reset sensor in the plugin settings)

**Turn off siren only**

You want to stop the siren if the security system has been triggered for more than 10 minutes and switch to armed state, keeping the flashing lights on.

The way I'd do this to keep it simple would be to create an automation using the event "when an accessory is controlled", choose the security system, pick when is armed and turn off the siren switch as an action. This would always try to turn off the siren switch when is armed but there's no impact however. You may need to enable the advanced option "reset using off mode" if the automation is not working correctly while being in triggered state. Oh, reverting to the armed mode happens automatically if you set the "reset delay minutes" to 10.

Just to confirm, the flashing lights and siren are two different smart plugs?

**Comment by Santai65** [comment]
Thank you Miguel for the instructions, much appreciated.  Yes, I have a separate smart plug for the siren and strobe light.I will try the logic below and let you know the outcome.CheersDuncanSent from my iPhoneOn 13 Apr 2024, at 6:14 am, Miguel Ripoll ***@***.***> wrote:﻿
I've been studying your diagram, nice work by the way.
Here's some instructions based on what I've interpreted from your attached image.
Main Door Open
Create an automation in the Home app using the event "when a sensor detects something", choose your contact sensor for the main door and the action would be to turn on the trip switch (either the global one called "Trip" or one containing a mode). This automation will play the alarm triggered when opening the door after the delay if not disarmed.
Back Door Open / Family Door Open
You want to trigger the security system immediately with no delay, right? I've thought some long ago to add a "panic switch" that does this, however the idea was discarded to avoid turning it on accidentally either using the UI or Siri. My recommendation would be to keep the delay even for sensitive zones for avoiding false alarms triggered physically or virtually but a new optional switch that implements the idea could be added if you really need it.
To sound the siren and flash some lights connected to a smart plug when the security system has been triggered, you would have to create an automation inside the Home app using the event "when an accessory is controlled", choose the security system, pick "when the security system is triggered" and finally turn on the smart plug as your action.
Note: I see that you want to flash the lights and make the siren sound only if the security system has been triggered by opening any door except the main one however this kind of condition is quite a complex one. Converting the automation to a shortcut to check if the main door is closed to turn on the smart plug could maybe work this out.
Alarm switch off
Create an automation using the event "when an sensor detects something", pick the triggered reset sensor and turn off the smart plug as an option (note: enable the triggered reset sensor in the plugin settings)
Turn off siren only
You want to stop the siren if the security system has been triggered for more than 10 minutes and switch to armed state, keeping the flashing lights on.
The way I'd do this to keep it simple would be to create an automation using the event "when an accessory is controlled", choose the security system, pick when is armed and turn off the siren switch as an action. This would always try to turn off the siren switch when is armed but there's no impact however. You may need to enable the advanced option "reset using off mode" if the automation is not working correctly while being in triggered state. Oh, reverting to the armed mode happens automatically if you set the "reset delay minutes" to 10.
Just to confirm, the flashing lights and siren are two different smart plugs?
