### ISSUE TITLE
Could we have a "sensor" for when the alarm _starts_ the arming process (before the delay).

### ISSUE THREAD

**Issue by ssylvan** [MiguelRipoll23/homebridge-securitysystem#548]
### What are you missing?

I'd like to basically play a gentle beeping noise or whatever when I'm arming the alarm during the 30s delay before the system is armed. I tried doing an automation checking the 'armed' state in the Home app, but it only triggers once the security system is actually arm (i.e. after the delay). 

If we could have a trigger that fires once right when the arming delay starts counting down, that would be breat.

**Comment by MiguelRipoll23** [comment]
Hi @ssylvan,

While the plugin is on maintenance mode I also consider this sensor should be added for AirPlay audio control. This feature will be available in the next release.

Thanks for suggestion.

**Comment by ssylvan** [comment]
Awesome, thanks!

**Comment by MiguelRipoll23** [comment]
Unfortunately, this feature will stay in beta but once everything is polished will be released to the stable channel.
