### ISSUE TITLE
Latest stable version update fails trigger and reboots HB

### ISSUE THREAD

**Issue by fate8383** [MiguelRipoll23/homebridge-securitysystem#569]
### Plugin version

Latest

### Plugin configuration

Standart

### Homebridge version

Latest

### What happened?

![IMG_5028](https://github.com/MiguelRipoll23/homebridge-securitysystem/assets/17381874/4f2d093c-6897-4c8c-9304-46834ae085c7)
Opened the window which should trigger alarm, instead it did this above. Rebooted HB afterwards.

**Comment by MiguelRipoll23** [comment]
Hi @fate8383, 

Please downgrade to 8.1.2 or switch to the beta channel. That version has been unpublished due to a bug happening when the new arming sensor is disabled.

Sorry about that.

**Comment by fate8383** [comment]
That fixed it, I guess I missed the notification to downgrade. Thanks a lot!
