### ISSUE TITLE
Adding Panic Mode

### ISSUE THREAD

**Issue by 0berkampf** [MiguelRipoll23/homebridge-securitysystem#578]
### What are you missing?

Hi,

I’m using your great plugin with Node-Red and homebridge-automation plugin.
I would like to create an automation for a « Panic Mode »: when the SOS button is pressed on a smart remote control, the security system is triggered even if the current state is off. I’ve tried to assign the value ‘4’ to 'SecuritySystemCurrentState' or ‘SecuritySystemTargetState’ but it’s not working. Same with the option ‘Trigger During Off Mode’ checked.
Do you think I missed something in the settings of your plugin?
If not, do you think this Panic Mode could be implemented?

Thx for your help and your great work.

**Comment by MiguelRipoll23** [comment]
Hey there,
Does the “Trip Override” switch exposed when enabling the option “Show Trip Override Switch” works for you for this scenario?
