### ISSUE TITLE
Alarm audio playback to a Bluetooth speaker from Raspberry Pi Zero W

### ISSUE THREAD

**Issue by HumanSkunk** [MiguelRipoll23/homebridge-securitysystem#59]
Hi,

Firstly the plugin is awesome I have managed to integrate a number of sensors and Webhooks into the capability however I am looking to getting the alarm to play audio to a connected bluetooth speaker on the Pi.

I have managed to test and verify a bluetooth speaker with the pi and configured the connection with bluetoothctl and succeed in getting audio to playback using bluealsa. The Pi will auto reconnect to the bluetooth speaker when it boots.

I have set the location of the audio file in the config and installed but I am unsure what command is being used to initiate the playback. In order to push via bluetooth and not default to HDMI (which I think its doing) you need to insert arguments into the playback instruction:

`aplay -D bluealsa /home/pi/alarm.wav`

Would there be any way to have this feature added? Or if it is a function that is currently built in could you point me in the right direction to resolve?

**Comment by HumanSkunk** [comment]
Did a bit more playing which ultimately caused my to brick the pi due to running a command which obliterated a large amount of files! Luckily I took a back up of the Homebridge config.

After a morning of rebuilding, I used the Homebridge image in the end as I was running Stretch Lite anyways. Using the Config-X restore it rebuilt everything and loaded my original config, installed bluealsa and connected my speaker.

Added the lines to the .bashrc and gave the whole thing a restart. Ran the `ffplay -loglevel error -nodisp -i /usr/local/lib/node_modules/homebridge-securitysystem/sounds/en-US/current-triggered.mp3 -autoexit` and audio came out the speaker. Annoyingly using the home app and changing the alarm state does not trigger it like before.

**Comment by HumanSkunk** [comment]
In the end I have purchased a cheap USB speaker and connected it to the Pi. With a bit of tweaking on the default sound card I have it outputting successfully to the device. Still cant work out why the bluetooth connection isn't working, but it isn't something I need right now.

**Comment by MiguelRipoll23** [comment]
Once I got some free time I’d like to investigate what’s happening here, I consider it quite important for the plugin and I definitely want it working.

I’ll see what I can do, soon hopefully.

**Comment by HumanSkunk** [comment]
Let me know if you want me to test anything or generate any logs if you need anything to help debug it. Happy to help.
