### ISSUE TITLE
Trip Override instantly turned off

### ISSUE THREAD

**Issue by RDAM71** [MiguelRipoll23/homebridge-securitysystem#593]
### Plugin version

8.3.1

### Plugin configuration

{
    "name": "HB Système de sécurité",
    "serial_number": "S3CUR1TYSYST3M",
    "default_mode": "Off",
    "arm_seconds": 1,
    "trigger_seconds": 0,
    "reset_minutes": 10,
    "save_state": false,
    "proxy_mode": false,
    "test_mode": false,
    "trip_switch_name": "Trip",
    "trip_home_switch_name": "Trip Home",
    "trip_away_switch_name": "Trip Away",
    "trip_night_switch_name": "Trip Night",
    "trip_override_switch_name": "Sirène",
    "mode_home_switch_name": "Mode Home",
    "mode_away_switch_name": "Mode Away",
    "mode_night_switch_name": "Mode Night",
    "mode_off_switch_name": "Mode Off",
    "mode_away_extended_switch_name": "Mode Away Extended",
    "mode_pause_switch_name": "Mode Pause",
    "audio_switch_name": "Audio",
    "override_off": false,
    "reset_off_flow": false,
    "double_knock": false,
    "double_knock_seconds": 90,
    "double_knock_modes": [
        "Away"
    ],
    "arming_sensor": false,
    "tripped_sensor": false,
    "tripped_sensor_seconds": 5,
    "triggered_sensor": false,
    "triggered_sensor_seconds": 5,
    "reset_sensor": false,
    "mode_switches": false,
    "mode_off_switch": false,
    "mode_away_extended_switch": false,
    "mode_pause_switch": false,
    "pause_minutes": 0,
    "arming_lock_switch": false,
    "arming_lock_switches": false,
    "trip_switch": false,
    "trip_override_switch": true,
    "trip_mode_switches": false,
    "audio_switch": false,
    "audio": false,
    "audio_language": "en-US",
    "audio_volume": "100",
    "audio_arming_looped": false,
    "audio_alert_looped": false,
    "accessory": "security-system"
}

### Homebridge version

1.8.2

### What happened?

The Trip Override switch automatically and instantly turn off when I turn it on. Regardless of the system state, if it's on night, away, home or disable mode. Thanks for helping.

**Comment by MiguelRipoll23** [comment]
Could you please follow these steps?

1. Enable Homebridge debug logging (Settings, UI Settings, Advanced, Log settings)
2. Restart Homebridge
3. Start an iOS recording and reproduce the issue
4. Copy Homebridge log and post it here alongside the recording

Thank you.
