### ISSUE TITLE
Keep system state after Plugin/Homebridge reboot

### ISSUE THREAD

**Issue by spaceg00se-r** [MiguelRipoll23/homebridge-securitysystem#595]
### What are you missing?

I have a strange problem with my network that my shellies sometimes stop being detected after a few days. I already tried a gazillion things but nothing helped. The only thing that remains would be that I set up a script on my Raspberry Pi running Homebridge that restarts the service or even the Raspberry Pi for example every night. 
However this poses a problem since I run the security system armed at night. Therefore I kindly ask you if it would be possible to persist the arming state so that the system can be set to this state when Homebridge or the plugin restarts.
That would really be awesome!

**Comment by MiguelRipoll23** [comment]
Did you enable the option "Save Data Using Storage" in the plugin settings?

That should persist the state for reboots.

**Comment by spaceg00se-r** [comment]
Hi Miguel
How could I not see that 🙈! Perfect! Completely solves my problem. Nice! Thank you!

BTW: Do you know if your plugin is Homebridge 2.0 compatible?

**Comment by MiguelRipoll23** [comment]
No problem.
It's Homebridge 2.0 compatible, no worries!

**Comment by spaceg00se-r** [comment]
Nice! Thanks again.
