### ISSUE TITLE
Support for Homebridge 2.0

### ISSUE THREAD

**Issue by DimaLegeza** [MiguelRipoll23/homebridge-securitysystem#597]
### What are you missing?

Hey,

Soon Homebridge 2.0 will be released which will have some breaking changes to plugins.
Could you please check if this plugin is impacted and make it work with 2.0?

https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

**Comment by MiguelRipoll23** [comment]
It's safe to update to Homebridge 2.0, already tested. Be free to update as soon as you want.

**Comment by DimaLegeza** [comment]
Thanks a lot for the quick reply @MiguelRipoll23.
Maybe you can mark the plugin as compatible? I can see e.g. `homebridge-cmd4` did it somehow :)

**Comment by MiguelRipoll23** [comment]
Noted, will take a look.

**Comment by MiguelRipoll23** [comment]
New available update marks the plugin as Homebridge 2 compatible.
