### ISSUE TITLE
Alarm off

### ISSUE THREAD

**Issue by e-jors** [MiguelRipoll23/homebridge-securitysystem#6]
Hi :)
I love this alarm :)
But one little issues is when the alarm is set to off. Its still trigges the alarm when a sensor is trigged.

**Comment by MiguelRipoll23** [comment]
Sorry to hear that! I will release an update to fix this issue today and let you know about it here 🙂

As a workaround use your security system’s state mode as a condition until the update is available.

**Comment by MiguelRipoll23** [comment]
A new version (v1.1.1) has been published to solve this issue, update to this latest version using `npm update -g homebridge-securitysystem`.

Thank you the bug report, have fun!
