### ISSUE TITLE
Off first during Reset

### ISSUE THREAD

**Issue by johnnygeezz** [MiguelRipoll23/homebridge-securitysystem#61]
I'm using the Aqara hub for security sensors along with your HB plugin for more advanced functionality. When your plugin resets after an alarm trigger, say in 10 minutes, it goes back to the previous state, like AWAY. The Aqara doesn't reset since it only knows OFF and AWAY states. It never gets the turn off state command to rearm itself to away. 

Could you add into the reset command to first reset to off state and then go to previous state? 

Ex. Sys OFF - AWAY- SIREN- RESET: to OFF first- then back to previous AWAY

**Comment by MiguelRipoll23** [comment]
New beta update published with the feature requested added, you can now try these changes executing the following command on your terminal:

`npm install -g homebridge-securitysystem@beta`

**IMPORTANT:** If you're a HOOBS user, please wait until the beta phrase has ended.

Remember that you can leave the beta program anytime using the command below:

`npm install -g homebridge-securitysystem@latest`

Thanks!

**Comment by MiguelRipoll23** [comment]
A new option `reset_off` has been added to use the `Off` mode during the reset flow!
