### ISSUE TITLE
Get Reset State for automation

### ISSUE THREAD

**Issue by johnnygeezz** [MiguelRipoll23/homebridge-securitysystem#62]
If an alarm is triggered, you generally set automation to turn on a scene that turn on lights etc. The plugin is set to reset to previous state (AWAY) after 10 min, but the lights still stay on and don't reset to off. 

Can the Reset state be used in an automation to be a trigger to turn off the light scene or trigger another one to turn lights off?

I can't see how to use the reset in Eve for this automation.

**Comment by MiguelRipoll23** [comment]
There's no reset functionality available to security systems compatible with HomeKit so the plugin is just simulating a new mode change to provide this feature that is imposible to differentiate from a normal request. However, a fake motion sensor can be provided by the plugin to detect when a reset is being made and create automations based on this trigger.

Would this implementation help you? BTW, that's a really good idea.

**Comment by johnnygeezz** [comment]
This is how I have it now with a separate dummy motion. It would be useful to have in the plugin.

**Comment by MiguelRipoll23** [comment]
Both this feature and #61 would be added on a new beta release, hopefully by tomorrow.

**Comment by MiguelRipoll23** [comment]
This will be available on beta 2 once I find some time to do the changes and test them properly.

**Comment by MiguelRipoll23** [comment]
New beta update published with the feature requested added, you can now try these changes executing the following command on your terminal:

`npm install -g homebridge-securitysystem@beta`

**IMPORTANT:** If you're a HOOBS user, please wait until the beta phrase has ended.

Remember that you can leave the beta program anytime using the command below:

`npm install -g homebridge-securitysystem@latest`

Thanks!

**Comment by MiguelRipoll23** [comment]
New stable update just released with the feature requested added, you can now update the plugin using the Homebridge / HOOBS UI. If you were part of the beta program you can now leave it using the following command:

`npm install -g homebridge-securitysystem@latest`

Thanks!
