### ISSUE TITLE
HomeKit Notification Text Question for Alarm Adjustments Triggered by Geofence or Dummy Switch

### ISSUE THREAD

**Issue by danielraffel** [MiguelRipoll23/homebridge-securitysystem#623]
### Plugin version

9.0.0

### Plugin configuration

Homebridge Security System v 9.0.0

```
{
    "name": "Alarm System",
    "serial_number": "S3CUR1TYSYST3M",
    "default_mode": "Off",
    "arm_seconds": 0,
    "trigger_seconds": 0,
    "reset_minutes": 10,
    "save_state": false,
    "proxy_mode": false,
    "test_mode": false,
    "trip_switch_name": "Trip",
    "trip_home_switch_name": "Trip Home",
    "trip_away_switch_name": "Trip Away",
    "trip_night_switch_name": "Trip Night",
    "trip_override_switch_name": "notify Alarm was Disarmed",
    "mode_home_switch_name": "Mode Home",
    "mode_away_switch_name": "Mode Away",
    "mode_night_switch_name": "Mode Night",
    "mode_off_switch_name": "Mode Off",
    "mode_away_extended_switch_name": "Mode Away Extended",
    "mode_pause_switch_name": "Mode Pause",
    "audio_switch_name": "Audio",
    "override_off": true,
    "reset_off_flow": true,
    "double_knock": false,
    "double_knock_seconds": 90,
    "disabled_modes": [
        "Home",
        "Night",
        "Away"
    ],
    "arming_sensor": false,
    "tripped_sensor": false,
    "tripped_sensor_seconds": 5,
    "triggered_sensor": false,
    "triggered_sensor_seconds": 5,
    "reset_sensor": false,
    "mode_switches": true,
    "mode_off_switch": true,
    "mode_away_extended_switch": false,
    "mode_pause_switch": false,
    "pause_minutes": 0,
    "arming_lock_switch": false,
    "arming_lock_switches": false,
    "trip_switch": true,
    "trip_override_switch": true,
    "trip_mode_switches": true,
    "audio_switch": false,
    "audio": false,
    "audio_language": "en-US",
    "audio_volume": "100",
    "audio_arming_looped": false,
    "audio_alert_looped": false,
    "accessory": "security-system"
}
```

### Homebridge version

1.8.5

### What's your question?

Thank you for creating this plugin! I’ve got things partially working, but I’m looking for ways to refine my setup. Specifically, I’d like geofence-triggered alarm events (e.g., disarming the alarm when the first person arrives) to generate a native Apple HomeKit notification that says “Alarm was disarmed” rather than “Alarm was triggered.” This is similar to the notifications I receive when manually triggering the event.

Currently, I’m using a dummy switch in the Apple Home (AH) automation for “first person arrived/last person left,” which then triggers another automation to arm/disarm the alarm. However, this setup seems to result in notifications with the word “trigger” rather than “arm” or “disarm.”

I understand this behavior might be inherent to the way the Apple system is designed, but I wanted to check if there’s a possible workaround (besides using a third party push notification from pushover.net etc.) Below are my configurations and details.

**Alarm Disarmed security config**
note: ideally this notification would say "alarm was disarmed"

```
{
    "name": "Alarm Disarmed",
    "serial_number": "S3CUR1TYSYST3M",
    "default_mode": "Off",
    "arm_seconds": 0,
    "trigger_seconds": 0,
    "reset_minutes": 10,
    "save_state": false,
    "proxy_mode": false,
    "test_mode": false,
    "trip_switch_name": "Trip",
    "trip_home_switch_name": "Trip Home",
    "trip_away_switch_name": "Trip Away",
    "trip_night_switch_name": "Trip Night",
    "trip_override_switch_name": "notify was disarmed",
    "mode_home_switch_name": "Mode Home",
    "mode_away_switch_name": "Mode Away",
    "mode_night_switch_name": "Mode Night",
    "mode_off_switch_name": "Mode Off",
    "mode_away_extended_switch_name": "Mode Away Extended",
    "mode_pause_switch_name": "Mode Pause",
    "audio_switch_name": "Audio",
    "override_off": true,
    "reset_off_flow": true,
    "double_knock": false,
    "double_knock_seconds": 90,
    "disabled_modes": [
        "Home",
        "Night",
        "Away"
    ],
    "arming_sensor": false,
    "tripped_sensor": false,
    "tripped_sensor_seconds": 5,
    "triggered_sensor": false,
    "triggered_sensor_seconds": 5,
    "reset_sensor": false,
    "mode_switches": false,
    "mode_off_switch": true,
    "mode_away_extended_switch": false,
    "mode_pause_switch": false,
    "pause_minutes": 0,
    "arming_lock_switch": false,
    "arming_lock_switches": false,
    "trip_switch": true,
    "trip_override_switch": true,
    "trip_mode_switches": true,
    "audio_switch": false,
    "audio": false,
    "audio_language": "en-US",
    "audio_volume": "100",
    "audio_arming_looped": false,
    "audio_alert_looped": false,
    "accessory": "security-system"
}
```

Alarm Armed security config
note: ideally this notification would say "alarm was armed"
```
{
    "name": "Alarm Armed",
    "serial_number": "S3CUR1TYSYST3M",
    "default_mode": "Off",
    "arm_seconds": 0,
    "trigger_seconds": 0,
    "reset_minutes": 10,
    "save_state": false,
    "proxy_mode": false,
    "test_mode": false,
    "trip_switch_name": "Trip",
    "trip_home_switch_name": "Trip Home",
    "trip_away_switch_name": "Trip Away",
    "trip_night_switch_name": "Trip Night",
    "trip_override_switch_name": "notify was armed",
    "mode_home_switch_name": "Mode Home",
    "mode_away_switch_name": "Mode Away",
    "mode_night_switch_name": "Mode Night",
    "mode_off_switch_name": "Mode Off",
    "mode_away_extended_switch_name": "Mode Away Extended",
    "mode_pause_switch_name": "Mode Pause",
    "audio_switch_name": "Audio",
    "override_off": false,
    "reset_off_flow": false,
    "double_knock": false,
    "double_knock_seconds": 90,
    "disabled_modes": [
        "Home",
        "Night",
        "Away"
    ],
    "arming_sensor": false,
    "tripped_sensor": false,
    "tripped_sensor_seconds": 5,
    "triggered_sensor": false,
    "triggered_sensor_seconds": 5,
    "reset_sensor": false,
    "mode_switches": false,
    "mode_off_switch": true,
    "mode_away_extended_switch": false,
    "mode_pause_switch": false,
    "pause_minutes": 0,
    "arming_lock_switch": false,
    "arming_lock_switches": false,
    "trip_switch": true,
    "trip_override_switch": true,
    "trip_mode_switches": true,
    "audio_switch": false,
    "audio": false,
    "audio_language": "en-US",
    "audio_volume": "100",
    "audio_arming_looped": false,
    "audio_alert_looped": false,
    "accessory": "security-system"
}
```
I experimented with different versions of this config, restarting a few times, and this version seems to be the one that enabled the arm/disarm items to appear as separate tiles in Apple Home. This setup seems to have allowed me to view and add the ‘notify was disarmed’ and ‘notify was armed’ actions in AH automations. 
![image](https://github.com/user-attachments/assets/2ec4f32c-0330-4b1c-ba5b-5013722961a3)

 ```
   "trip_switch": true,
    "trip_override_switch": true,
    "trip_mode_switches": true,
```

**How the automations work...**  
I currently have an AH automation called ‘When the First Person Arrives Home’ that activates a dummy switch named ‘First Disarm Alarm.’ Another AH automation detects when this dummy switch is toggled, disarms the alarm, and activates the ‘Notify Was Disarmed’ switch, which triggers the alert message from Homebridge Security System. Similarly, I have an AH automation called ‘Last Person Leaves’ that triggers a dummy switch named ‘Last Arm Alarm.’ Another AH automation monitors this switch, arms the alarm, and activates the ‘Notify Was Armed’ switch, which also triggers an alert message from Homebridge Security System. 
![image](https://github.com/user-attachments/assets/cdad20af-446e-40a4-8fdd-73afbaeb2e3c)
![image](https://github.com/user-attachments/assets/a5fd4b31-f8db-402b-b54a-60c9f4f5440d)

**Currently, those above automations deliver notifications which say:**   

- "Studio Alarm Disarmed was triggered."
- "Studio Alarm Armed was triggered."

![image](https://github.com/user-attachments/assets/580de7aa-03da-45b8-bd4f-bdcd6e971a1e)

**Questions / Issues:**

1. Ideally, the notifications would say “Alarm was armed” or “Alarm was disarmed.” I’m not sure why it’s showing “Alarm Disarmed was triggered” instead—any idea how to adjust the language to reflect my desired state?

2. The critical alert is quite loud! For alarm arming/disarming, I’m not sure I need it to be that intense. I think I might prefer using a critical alert only if the alarm is set off. Is there a way to set normal push notifications for alarm arm/disarm changes and reserve the critical alert for if the alarm is set off?

3. I noticed that in AH, when I test triggering a dummy switch (e.g., “Notify Was Armed” or “Notify Was Disarmed”), it seems to leave the respective trigger in a “triggered” state. I’m not sure what this indicates or how to resolve it. Any thoughts? I am not certain but I think it might be blocking an alert from happening again.
![image](https://github.com/user-attachments/assets/462afb13-beda-4ca5-b63e-f73e545f5a70)

4. When I use the following config, I’m not entirely sure what enabling ‘trip’ does or whether I need to reset the ‘off’ switch. Any chance you could explain? 
    "trip_switch": true,
    "trip_override_switch": true,
    "trip_mode_switches": true,
    
   ![image](https://github.com/user-attachments/assets/c4e02055-8a60-4675-a5c8-4130c976bcf6)

**Comment by MiguelRipoll23** [comment]
Hi there!

I find it weird that you have multiple alarms, called "disarmed" and "armed". I'm understanding from your issue that you want to receive regular notifications when the mode changes.

I think you need to set up a single alarm, called "Alarm" and enable the mode switches in the plugin settings.

Edit your geofence automations to turn on the corresponding mode switch like home and away. This way you would receive the notifications like this:

![image](https://github.com/user-attachments/assets/cfddfdec-066a-49fa-a5e8-cbbd5a0924c5)

Let me know if it helps and thanks for your comments!

**Comment by MiguelRipoll23** [comment]
About your fourth question turning on a trip switch, either the global one or the mode ones starts a "countdown" (trip seconds in settings) to set off the security system.

If mode changes during this countdown, the security system will change to the requested mode and the countdown timer would be cancelled.

Trip mode switches require its corresponding mode to be currently selected, you won't be able to turn on an away switch if home mode is selected.

Trip override switch allows you to trip the security system in any mode, including "Disarmed" for situations where you may want to skip mode restrictions like SOS buttons.

**Comment by danielraffel** [comment]
**Thanks for following up, I followed your advice and it seems to be much better now.**

I just **deleted my Homebridge Security System pluging settings**. Then, I followed your suggestion and...

1) **created a new "Alarm"**
<img width="803" alt="image" src="https://github.com/user-attachments/assets/317b5529-91d0-4cd8-b6a1-5fed1dddb316">

2) **enabled "Show Mode Switches"**
<img width="746" alt="image" src="https://github.com/user-attachments/assets/bebad188-0c92-43f9-bebd-50fb5ca37eca">

3) **removed all the old arm/disarm stuff** I had in my HomeKit automations (which included automations with dummy switches)

4) followed your advice to configure automations to **Arm to 'Away' when last person leaves** 
![IMG_4705](https://github.com/user-attachments/assets/2eb8cfee-cacd-4ba4-9742-bd3142ec5971)

**and 'Disarm' when first person arrives**
![IMG_4704](https://github.com/user-attachments/assets/8054c4e2-52ea-4d6c-a069-6b113d4455c4)

**Good News**

**These automations appear to be working when I test them (I get the notifications with the language I was hoping for!)** (eg alarm was armed vs triggered)

![image](https://github.com/user-attachments/assets/1cbda533-c8a6-4977-94b0-e627f38d36dd)

**Background Context Might Be Worth Chiming in Over Here**
My original setup which did not work was [following a thread from reddit](https://www.reddit.com/r/homebridge/comments/1h3mdp4/how_to_get_homekit_notifications_for_alarm/) which may not be accurate.

**Early Observations**
I think I should live with this for a bit and see how it works. From some initial observations after setting this up:

1) When I manually adjust the alarm in HomeKit I don't reliably deliver alarm/disarm notifications 100% of the time. I dunno why but maybe I am changing things too much during testing...
![image](https://github.com/user-attachments/assets/f672498f-0ddd-41a9-a016-f1f3ab18f843)

2) I also notice when I "test" running the first person arrive/last person left automations they also don't reliably deliver alarm/disarm notifications 100$ of the time. Again, I dunno why but maybe I am changing things too much during testing...
![image](https://github.com/user-attachments/assets/d3b65eb9-1d25-42f8-9a64-a2d8720119b1)

**Side Note on Unreliable Push Notifications:**
No idea if this could be an issue with flakey notifications...I am using an [Eyezon Duo](https://www.eyezon.com/duo.php) with a Honeywell Vista 20p for a few weeks. I connected it to Apple HomeKit using this [Homebridge Envisalink Ademco plugin](https://github.com/haywirecoder/homebridge-envisalink-ademco#readme) and noticed the plugin mentioned, “Envisalink TPI interface only supports one connection: Once this plug-in is connected, any other connections will result in an error. Vice-versa, if Envisalink is being used for another purpose this module will not be able to connect.”

**Comment by MiguelRipoll23** [comment]
For your geofence automations, I know it feels weird but in order to skip iOS confirmation you need to use mode switches.

For example the automation for "The Last Person Leaves Home" must turn on the "Mode Away" switch that the plugin exposes. Don't use the security system unless you want to actually confirm the automation actions.

About the notifications, you will receive them in these two scenarios:

- someone else set a mode
- an automation set a mode
- you set a mode but you left the Home app or locked the device (I may be wrong here, conditions set by Apple)

Using the mode switches guarantees the notification will be pushed.

**Comment by danielraffel** [comment]
Aha! I have so many darn items in HomeKit I "missed" the Alarm mode settings, they got added to a default room and I didn't see them and I was using the wrong thing. Thank you for calling that out! 

Now that I have reconfigured my automations to use the modes like you suggested the geofence automations are working reliably.

![image](https://github.com/user-attachments/assets/b446f6b8-e040-42f6-a168-9e5be7c068f0)
![image](https://github.com/user-attachments/assets/73a98f86-0f5e-46e3-b565-dce5f1efb623)

One nice thing I noticed is that if I put the "alarm" in a "room" called the name of my home address I can get a nice message. For instance, I put "Alarm" in a room called "123 Main Street" then when it arms it will say "123 Main Street was armed"

If it's at all helpful to you I'd be happy to try to summarize what we did and shoot you some language you could consider adding to the FAQ. Totally your call, no pressure! Super appreciative of you taking the time to explain this to me.

**Comment by MiguelRipoll23** [comment]
That would be much appreciated! I did my best on the Wiki page but language barrier is a bitch sometimes 😅

Thanks, glad you got it working.

**Comment by danielraffel** [comment]
I'll take a stab and share something soon. In the meantime, I took a first stab at documenting everything I did.

https://danielraffel.me/2024/12/06/how-to-set-up-your-honeywell-alarm-with-apple-home-for-push-notifications-and-geofence-based-arming-disarming/

**Comment by danielraffel** [comment]
Here's some proposed text for the wiki on Automating Alarm Modes with Geofence Triggers in Apple Home App. Feel free to use or not! Thanks again for all your work on this.

**How do I set the alarm to arm automatically when the last person leaves home?**  
1. Open the Homebridge Security System plugin settings.  
2. Under the **Switches** section, enable the option for **Show Mode Switches**.  
<img width="736" alt="image" src="https://github.com/user-attachments/assets/4ee0ef85-1a9a-4c62-99ac-b9b65092613c">

3. Restart Homebridge to register the changes to the Security System plugin.  
4. Open the Apple Home app and confirm that four new mode switches (Away, Home, Night, Off) appear.  
5. Create or modify the automation "when the last person leaves": 
   - Trigger: **When the last person leaves home**.  
   - Action: **Turn on the `Mode Away` switch**.  
   - Result: The alarm arms in **Away** mode and pushes a notification that says "Alarm was armed for away."

![393377640-73a98f86-0f5e-46e3-b565-dce5f1efb623-2](https://github.com/user-attachments/assets/2b3571a0-2659-4ee6-a91c-984a1a564142)


**How do I set the alarm to disarm automatically when the first person arrives home?**  
1. Ensure the **Show Mode Switches** option is enabled in the plugin settings as described above.  
2. Create a new automation:  
   - Trigger: **When the first person arrives home**.  
   - Action: **Turn on the `Mode Off` switch**.  
   - Result: The alarm disarms (switches to **Off** mode) and pushes a notification that says "Alarm was disarmed."

![393377764-b446f6b8-e040-42f6-a168-9e5be7c068f0-2](https://github.com/user-attachments/assets/ed742cf6-3514-4784-9488-df9ceed0df11)


**Why Enable and Use Mode Switches in Geofence Automations?**  
The **Mode Switches** (Away, Home, Night, Off) provided by the plugin ensure the automations can run without manual intervention. Directly using the security system in automations will prompt for confirmation, which defeats the purpose of geofence triggers.


**When Will Alarm Notifications Be Sent?**  
Push notifications are sent in these scenarios:  
- When someone else sets a mode.  
- When an automation sets a mode.  
- When you set a mode, but the Home app is closed or the device is locked (conditions set by Apple).  

Using the **Mode Switches** guarantees that you’ll receive notifications for alarm state changes triggered by automations.

**Comment by danielraffel** [comment]
Stupid question: I haven't triggered my alarm to see what happens. When I do should it trigger a notification?

Also, is there a way to make just those events trigger a critical alert so I can be guaranteed to know that my alarm is actively going off?

**Comment by MiguelRipoll23** [comment]
If you turn a trip switch and remains on, it will start the countdown or switch to triggered state depending on your current settings.

The triggered state uses a critical notification, this is controlled by Apple.

Thanks for the help, will add it to the Wiki ASAP.

**Comment by danielraffel** [comment]
I guess I am not following. I just went and armed my alarm, then intentionally opened a door to trigger my alarm to sound. I hoped to get some sorta push notification on my phone from HomeKit but did not. Do you know what I need to do in the Apple Home app / your plugin to get a critical push notification when the alarm goes off?

**Comment by danielraffel** [comment]
Ah, figured it out.

**How do I get notifications when the Alarm goes off?**
Apple Home supports sending [Critical Alerts](https://support.apple.com/en-us/108781) on iOS 15 and iPadOS 15 or later. To ensure these alerts are active, verify that they are enabled under **Settings > Notifications > Home**. ![image](https://github.com/user-attachments/assets/5b47c333-592c-46ef-baae-6c5340d4e109)


Once set, if the security system trips Away, Home, or Night (e.g., the alarm is triggered), you’ll receive the respective alert automatically. While no additional automations are required to enable this feature it's worth testing to confirm it is setup and working correctly for you.

![IMG_4747](https://github.com/user-attachments/assets/98a78b52-162b-4021-a508-436b547040e9)

**Comment by danielraffel** [comment]
Question: After my alarm was triggered, I noticed that I had to physically access the keypad panel on the alarm and essentially press “cancel” to clear it before I could set an alarm mode through the Home app. Do you know of a way to perform this action remotely?

**Comment by jsiegenthaler** [comment]
The HomeKit security system user interface and notifications are provided by Apple. Which means Apple decide what notifications are sent and what the wording is. 

But you can set the alarm to automatically arm when the last person leaves home, and disarm when the first person arrives home. I use this plugin and I do this.

**Comment by jsiegenthaler** [comment]
The standard notifications are roomname accessoryname was armed for modename
And
roomname accessoryname was disarmed

So for me:
Apartment Security System was armed for away. 
Apartment Security System was disarmed. 

As these are standard notifications, they will appear in the language of your iPhone.
