### ISSUE TITLE
Mode pause untimed

### ISSUE THREAD

**Issue by johnnygeezz** [MiguelRipoll23/homebridge-securitysystem#63]
Time delay is useful to pause setting a mode like Away. Delay is hard set in config. Suggest if delay is set to 0 then it is untimed and just a manual toggle. 

0 = override until switch off
Time = override until time expires and then change mode to Away for example. 

Sometimes I need to disable the auto arming and don't have a set time to auto change it.

**Comment by MiguelRipoll23** [comment]
New beta update published with the feature requested added, you can now try these changes executing the following command on your terminal:

`npm install -g homebridge-securitysystem@beta`

**IMPORTANT:** If you're a HOOBS user, please wait until the beta phrase has ended.

Remember that you can leave the beta program anytime using the command below:

`npm install -g homebridge-securitysystem@latest`

Thanks!
