### ISSUE TITLE
Wrong behaviour of "Mode Night" switch in mode "away"

### ISSUE THREAD

**Issue by macjl** [MiguelRipoll23/homebridge-securitysystem#64]
**Describe the bug**
Hello,
I've noticed a behaviour that may not be correct with the 'unsafe_mode_switches'. When the alarm is in mode 'Away', and an automation switch the 'Mode Night' switch to off (even if it's already off), then, the alarm go to Off Mode.

**To Reproduce**
1. Make an automation that put the switch 'Mode Night' to 'Off'
2. Set manually the Alarm to Away
3. Execute the Automation created in step 1
4. => The alarm go in 'Off' Mode, as it should do nothing.

**Expected behavior**
In this case, I think the alarm should stay in the Away Mode.
For example, I have an automation that deactivate the Night Mode when someone get in the kitchen in the morning. With this bug, the alarm is deactivated if someone get in the kitchen, even if it was set in Away Mode when we are not at home.

**Plugin's configuration**
```
   "accessories": [{
      "accessory":            "security-system",
      "name":                 "Security System",
      "default_mode":         "off",
      "disabled_modes":       ["home"],
      "trigger_seconds":      60,
      "arm_seconds":          60,
      "reset_minutes":	      1,
      "siren_switch":         false,
      "siren_mode_switches":  true,
      "save_state":           true,
      "unsafe_mode_switches": true,
      "hide_mode_off_switch": true,
      "server_port":          9090,
      "server_code":          9090,
      "audio":                true,
      "webhook_url":          "https://api.telegram.org",
      "webhook_alert":        "/botxxxxxx-xxxxx/sendMessage?chat_id=xxxx&text=Alarme%20declenche.",
      "webhook_triggered":    "/botxxxxxx-xxxxx/sendMessage?chat_id=xxxx&text=Alarme%20sonne."
   }]
```

**Comment by MiguelRipoll23** [comment]
When the mode switches were added to the plugin I tried to avoid using the `No response` error as a way to block user actions that doesn't make sense so when a mode switch was turned off it disarmed the security system. Could you try to add a condition to the automation that checks if the current mode is not Away?

Hopefully that helps.

**Comment by macjl** [comment]
Hello,

I've set such a workaround. I have converted the action to an automation script, that check the switch status before taking the action. It seems to work for now.

I understand your internal architecture choices will not be able to correct this behaviour. So I will live with this workaround without problems!
But if you change that in the future, please tell me, so that will simplify my automations.

Thank you!

**Comment by raixer** [comment]
You know homekit natively supports conditions without using script? You just need to download a homekit app such as Eve.

**Comment by macjl** [comment]
Yes, I know that, but Eve requires that the action to perform has to be a scene. As I already have too much scenes, I don't want to add more. That's why I'm using a Homekit script instead.

**Comment by raixer** [comment]
You start by creating the automation in Home app then add the condition in Eve app. That way you don’t have to create a scene.

**Comment by raixer** [comment]
The reason I am pointing that out is because I find homekit scripts unreliable. It could be because I am using an iPad as home hub but I stopped using scripts because I couldn’t trust it would run every time.

**Comment by MiguelRipoll23** [comment]
I create automations on the Home app and edit them in Eve as well, makes them more simple.

I’m open to changing the implementation in the future though, I don’t want the plugin to be stuck with old choices. I just need to inform that a incoming implementation change is about to happen.

There would be an update to the plugin soon, after that I’m gonna rename a few options and see what else could be improved.

**Comment by MiguelRipoll23** [comment]
Implementation will be changed in a future release 🙂

**Comment by MiguelRipoll23** [comment]
New stable update just released with the feature requested added, you can now update the plugin using the Homebridge / HOOBS UI. If you were part of the beta program you can now leave it using the following command:

`npm install -g homebridge-securitysystem@latest`

Thanks!
