### ISSUE TITLE
Sound instructions

### ISSUE THREAD

**Issue by alxalxnet** [MiguelRipoll23/homebridge-securitysystem#66]
I can't find any instructions on how to use the sounds. Also, I looked everywhere on my HD but I can't find the sound folder with the mp3 files.

**Comment by MiguelRipoll23** [comment]
Sorry for the lack of documentation.

The sounds are located inside the plugin installation directory, it should be `/usr/local/lib/node_modules/homebridge-securitysystem/sounds`.

If you want to use your own sounds, create a directory somewhere and provide the path to it on the `Custom Audio Path` and restart Homebridge. When the plugin starts, a text file with instructions would be created telling you how to name your sounds for the plugin to play them depending of the event.
