### ISSUE TITLE
Option 'mode_off_switch' & 'unsafe_mode_switches' has been deprecated?

### ISSUE THREAD

**Issue by Christian-CFP** [MiguelRipoll23/homebridge-securitysystem#68]
Option 'mode_off_switch' has been deprecated, update your configuration.
Option 'unsafe_mode_switches' has been deprecated, update your configuration.

New option code needed?

**Comment by MiguelRipoll23** [comment]
They have been renamed (doing my best here to improve the name convention that I use).

hide_mode_off_switch -> mode_off_switch (false as value to hide)
unsafe_mode_switches -> mode_switches

The first deprecated message is wrong, it should say hide_mode_off_switch actually.

Sorry for the late reply!

**Comment by Christian-CFP** [comment]
Ok, thank you!
