### ISSUE TITLE
Difference CMD Alarm and Triggert?

### ISSUE THREAD

**Issue by Nastras** [MiguelRipoll23/homebridge-securitysystem#70]
Hello @MiguelRipoll23,

I need your help. I want to set my alarm system so that when the alarm is triggered a CMD command (command_triggered) is sent to me via a script.

After 60 seconds the CMD command (command_alert) should be executed and the sirens should start.

But I can't get it set up like this. In my case both scripts for both commands are executed immediately after the sirens are triggered.

Would be cool if you can give me a hint? Thank you!

![C4691346-CE6A-4210-8B12-F5471644E7B1](https://user-images.githubusercontent.com/27686185/95295395-4794da00-0877-11eb-9361-5f5eaa085cdc.jpeg)

**Comment by MiguelRipoll23** [comment]
Hello!

Looks like `command_alert` and `command_triggered` are executing at the same time, is that right?

I'm testing with a similar configuration but I can't reproduce this issue, can you run Homebridge in debug mode and show me the log? Execute `homebridge -D`.

It should like this once it's enabled:
![image](https://user-images.githubusercontent.com/3296866/95492511-760bd580-099b-11eb-8f36-7c916526414c.png)

Sorry for the delay.

**Comment by Nastras** [comment]
Hello @MiguelRipoll23 ,
sorry also for my late reply. Unfortunately I did not get the chance to test it again earlier.

So I have found the error now. I'm not sure if it is my fault that I have misunderstood something or that it is mixed up in the plugin.

I changed the paths to the scripts between "command_alert": and "command_triggered".

If I now trigger the alarm system I first get a push then it waits 60 seconds and then the alarm is triggered.

I understood it as follows: "command_alert" is the command that triggers the real alarm and "command_triggered" is the pre-alarm. But it seems to be exactly twisted.
Here again an excerpt from my current config to better understand it.

![57DD8400-52F1-49BC-B2B9-A20AA6FF888F](https://user-images.githubusercontent.com/27686185/95679825-9a52f680-0bd5-11eb-95c4-ec1f07f5a1e8.jpeg)



Thank you!

**Comment by MiguelRipoll23** [comment]
Actually `command_alert` is the warning and `command_triggered` is the event that should make the sirens sound ;)

**Comment by Nastras** [comment]
Ok so I got it wrong and the mistake was mine 😅
I couldn't read it directly from the plugin description so maybe you can make a more concrete hint.

Thanks and have a nice sunday!

**Comment by MiguelRipoll23** [comment]
I'll do my best to improve the documentation and name the options better, I think `server_warning` and `webhook_warning` would have been a better name for the option maybe (as life gets busier I try keep the plugin maintained but my time to do things right reduces so the options' names can be confusing).
