### ISSUE TITLE
Add proxy mode

### ISSUE THREAD

**Issue by Q3F1S9B** [MiguelRipoll23/homebridge-securitysystem#71]
Hey, 
Thank you for all your work !
I try to use my Somfy Home Alarm with your plugin and I am stuck with Loop.

1) I use weebhook to target a state in Home App ( It work juste fine )
    So Home to Somfy is ok

2) My issue concern : Somfy to Home/Homebridge
When a user activate/deactivate with his badge the alarm: 
   a. The alarm state change directly 
   b. I want to update the state in the Home App ( without targeting again to avoid loop ) 
       With the server option, it launch the corresponding webhook and target a second time user choice.
   c. I have a php script which return the state option arm/disarm/night/triggered 

How can I use this script to change to update state ( in a silent way ) ?

Sorry for my bad English

Regards.

**Comment by MiguelRipoll23** [comment]
Hey there,

With the current options this is not possible right now but it could be added though!

I'll see what I can do and report back soon as this feature makes the logic behind the mode changes a little bit more complicated although if implemented right it's not a problem.

**Comment by Q3F1S9B** [comment]
Thank You !

**Comment by MiguelRipoll23** [comment]
New beta update published with the feature requested added, you can now try these changes executing the following command on your terminal:

`npm install -g homebridge-securitysystem@beta`

(Advanced Options > Security system > Enable proxy mode  or `proxy_mode`)

**IMPORTANT:** If you're a HOOBS user, please wait until the beta phrase has ended.

Remember that you can leave the beta program anytime using the command below:

`npm install -g homebridge-securitysystem@latest`

Thanks!

**Comment by Q3F1S9B** [comment]
Thank You ! It's perfect !

**Comment by MiguelRipoll23** [comment]
New stable update just released with the feature requested added, you can now update the plugin using the Homebridge / HOOBS UI. If you were part of the beta program you can now leave it using the following command:

`npm install -g homebridge-securitysystem@latest`

Thanks!
