### ISSUE TITLE
Not able to install ffmpeg with instructions given

### ISSUE THREAD

**Issue by reibejoy** [MiguelRipoll23/homebridge-securitysystem#72]
It is not clear (to me) where to enter the command to install ffmpeg. 
I tried in the Docker terminal. Results: 

```
/homebridge # sudo apt install ffmpeg
sudo: apt: command not found
/homebridge # apt install ffmpeg
/bin/sh: apt: not found
/homebridge # 
```

How can I install ffmpeg for homebridge-securitysytsem? Can you provide some more detailed instructions.

**Comment by MiguelRipoll23** [comment]
Hello!

Sorry for the delay.

Which operative system is installed on your docker container? Can you run `uname -r` and print the result here?

Also which device are you using?

Thanks.

**Comment by reibejoy** [comment]
Sure. 

`/homebridge # uname -r
4.2.8`

**Comment by MiguelRipoll23** [comment]
I added the `hep wanted` tag as I can't find more information about this to help you unfortunately.

**Comment by macjl** [comment]
Hello,

Can you submit this command in the container : 
`cat /etc/issue`

**Comment by reibejoy** [comment]
Sure. It replied: 
`Welcome to Alpine Linux 3.12
Kernel \r on an \m (\l)`

**Comment by macjl** [comment]
So try a : 
`apk add ffmpeg`

**Comment by reibejoy** [comment]
That worked. ffmpeg was installed. I switched sound to "on" in the settings and restarted homebridge. 
There error I get now is this one: 

```
[11/11/2020, 9:37:27 AM] [Security system] Target mode (Home)
[11/11/2020, 9:37:27 AM] [Security system] Audio failed
ALSA lib confmisc.c:767:(parse_card) cannot find card '0'
ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1246:(snd_func_refer) error evaluating name
ALSA lib conf.c:4693:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory

[11/11/2020, 9:37:27 AM] [Security system] Audio failed
ALSA lib conf.c:5181:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2642:(snd_pcm_open_noupdate) Unknown PCM default
No more combinations to try, audio open failed
Failed to open file '/homebridge/node_modules/homebridge-securitysystem/src/../sounds/en-US/target-home.mp3' or configure filtergraph 
```

**Comment by Karrypto** [comment]
did you install homebridge using the official instruction for QNAP? 

https://github.com/oznu/docker-homebridge/wiki/Homebridge-on-QNAP

After that it’s maybe easier to install ffmpeg via the homebridge-camera-ffmpeg plugin to automatically install all the needed dependencies.

https://github.com/Sunoo/homebridge-camera-ffmpeg

just an idea 🤔 

basically I’m not a friend of the NAS versions of homebridge...maybe it’s better to use a stand alone raspberry pi version if you want to use more specific plugins... you will certainly run into problems more often I guess

**Comment by reibejoy** [comment]
Yeah, I used the official guide. 
Just tried with what you proposed but the error remained the same.
