### ISSUE TITLE
Sensor to be able to trigger a sound(s) when in arm-delay or trigger-delay states?

### ISSUE THREAD

**Issue by jdberry** [MiguelRipoll23/homebridge-securitysystem#73]
I'd like to be able to trigger sounds on my HomePod, using a sensor, when in the arm-delay or trigger-delay states, perhaps similar to how the siren-sensor works. It looks like this might be possible with the web hooks but that requires more additional accompanying infrastructure... i.e., other dummy timers, switches, etc.

**Comment by MiguelRipoll23** [comment]
Hello!

On the Home app you can do actions when the security system arms, disarms or triggers using the `Automation` tab, you can detect individual modes like `Home`, `Night` or  `Away` by enabling the mode switches feature (Advanced Options > Switches > Show Mode Switches or JSON option `mode_switches` to true) and then using `An Accessory is Controlled` to detect when the switches turn on when the mode is selected.

**Comment by MiguelRipoll23** [comment]
Did the answer provided helped you? Request more information if needed.

**Comment by jdberry** [comment]
Sorry, I'm just getting back to this issue. I'm not sure we're understanding each other.

Here's what I'd like to do:

1. Set an arm delay (arm_seconds, presumably) perhaps to 120 seconds.
2. Set a trigger delay (trigger_seconds, presumably) perhaps to 140 seconds.
3. When the system is armed, but during the 120 second delay period before it's actually armed, play a sound repeatedly on my HomePod.
4. Likewise, when the system is triggered, but during the 140 second trigger delay, play a sound repeatedly on my HomePod.

siren_sensor and siren_sensor_seconds seems to control behavior like this for when the siren is actually going off, though I haven't tested this yet. A similar mechanism would seem appropriate for the delay period(s).

In my testing just now with mode switches, I can't seem to get even somewhat close to any of this. In fact, it seems to me that arm_seconds isn't working at all? I set it to 30 seconds, and then arm the system to Away, and I immediately see logs for "Target mode (Away)" and "Current mode (Away)". I would have expected the log for "Current mode (Away)" to come 30 seconds after the target mode since I set arm_seconds to 30?

**Comment by MiguelRipoll23** [comment]
Can you please share your config?

It’s really weird that the mode is switching immediately, are you using the `Save Using Local Storage` / `save_state` option?

Right now, it isn’t posible to loop an arming sound but it could be interesting to add this feature.
