### ISSUE TITLE
mode_off_switch parameter no effect

### ISSUE THREAD

**Issue by Karrypto** [MiguelRipoll23/homebridge-securitysystem#74]
Hi Miguel, 
seems the "mode_off_switch" parameter is currently not working...

"mode_off_switch": false, - still shows the switch in HomeKit unless you use the "mode_switches":false parameter of course :)

**Comment by MiguelRipoll23** [comment]
Hello!

Thanks for reporting this issue, it has been fixed on the beta channel.
A stable version will be published on Sunday :)

**Comment by MiguelRipoll23** [comment]
New stable update just released with the bug encountered fixed, you can now update the plugin using the Homebridge / HOOBS UI. If you were part of the beta program you can now leave it using the following command:

`npm install -g homebridge-securitysystem@latest`

Thanks!
