### ISSUE TITLE
Alarm triggered by http request

### ISSUE THREAD

**Issue by maxime-killinger** [MiguelRipoll23/homebridge-securitysystem#75]
I have a motion sensor that can send http requests. Is it possible to trigger the alarm from a http request ?

**Comment by MiguelRipoll23** [comment]
Sure!

Go to the server section from the plugin's settings and set the `Port` option to 8081 for example.
Then send a request to http://homebridge_ip_address_here:8081/triggered

**Comment by maxime-killinger** [comment]
Hi ! 

Thank you, but I get the error 
`{"error":false} `

Do you have any idea of what I’m doing wrong ?

**Comment by MiguelRipoll23** [comment]
That response it's indicating that no errors happened (see the the false value) so your request has been done correctly and you should see the security system trigger actually :)

**Comment by maxime-killinger** [comment]
Thank's. Indeed, it's working just fine.
