### ISSUE TITLE
Homekit System Status

### ISSUE THREAD

**Issue by RLP1369** [MiguelRipoll23/homebridge-securitysystem#77]
The Homekit icon shows the system “Off” regardless of which mode it is actually in.  Is this a known issue or how is it resolved?
Also, the trigger delay is set for 60, but the system triggers as soon as the automation trigger occurs.  Again, is this a known issue and/or how does one resolved this?
Thank you!

**Comment by Karrypto** [comment]
What do you mean with HomeKit icon ? The alarm light symbol of the security device in Home app turns red as soon as an mode ist armed (not during „arm_seconds“ ). 

regarding the „trigger_seconds“...hmm...for me I can say it works as it should. Maybe a config mistake ?

**Comment by Underlyingglitch** [comment]
You mentioned the trigger delay. That's my question too. I set up 2 automations in the Eve app. One for "away" mode and one for "stay" mode. When motion is detected, and the security system is set to......, trigger the alarm scene (containing a siren and some lights). This is working fine, except it always triggers instantly, no delay no matter what i set it too. Can someone help me?

If I need to create a new issue, that's fine by me, but since you are asking this as well....

**Comment by Karrypto** [comment]
nope, I just tested it again, works like it should. Seems you have a rule issue. 
I created this simple rule for the test:

Start via Home App and add automation:

Trigger: if light bulb set to ON (in your case the motion sensor)
Action: set "Mode Triggered" Switch to ON 
+
then add the condition (via Eve App): "Security" is set to "Away" 
(you can directly use the security device and select the mode, not the mode away switch)

So for the test, if I switch my selected light bulb on and Security is set to "Away" before, then the switch "Mode Triggered" will be set to ON. It took exactly the 20 seconds I've set in the config before the security system alarm and siren was activated.

**Comment by MiguelRipoll23** [comment]
Hello!

Can you share your config?

**Comment by Underlyingglitch** [comment]
```
{
            "name": "Alarm systeem",
            "default_mode": "Off",
            "arm_seconds": 10,
            "trigger_seconds": 10,
            "reset_minutes": 10,
            "audio": false,
            "audio_language": "en-US",
            "save_state": false,
            "proxy_mode": false,
            "test_mode": false,
            "override_off": false,
            "reset_off_flow": false,
            "siren_sensor": false,
            "siren_sensor_seconds": 5,
            "reset_sensor": false,
            "mode_switches": false,
            "mode_off_switch": true,
            "mode_pause_switch": false,
            "pause_minutes": 0,
            "siren_switch": true,
            "siren_mode_switches": false,
            "audio_volume": "100",
            "audio_alert_looped": false,
            "server_port": 8888,
            "server_code": 1317,
            "accessory": "security-system"
        }
```
So this is my config. If you need any other settings, let me know. I have a siren connected as a switch. I want to use a certain amount of time before the siren gets triggered. In this case being `trigger_settings` because my front door is connected to the security system. 

@Karrypto You mentioned the 'Triggered state' a few times. In the Eve app, I can check whether the state of the alarm is set to Triggered, but I can't set it as Triggered. So how would I do this?

**Comment by Karrypto** [comment]
hmm Ok I try more specific...

set  **"mode_switches": true**
-> this will expose switch devices for the different modes and a "mode triggered" switch device in Home App

**1st rule**
-----------

### **Eve App automation:**

**Trigger:**  Select all your window / door sensors and set it to OPEN

**Condition:** search for the "SECURITY" device and enable "Status" -> then select "Away"

**Action:** Eve only allows a scene as action...so here you can select any scene you have, we will remove this again in next step

### **Apple Home App automation**

- edit the rule we just created in the Eve App and **deselect the scene** from the step before  ( "select devices and scenes..." )
- then select the **"mode triggered" switch device** and set it to ON

1st rule finished

**2nd rule**
---------------------

### **Apple Home App automation**

**Trigger:** search and select "Security" device and click next 
-> now you can choose the different states...select the "trigger" state

(please note, my GUI is not in english, so I didn't know the exact wording for the mode "trigger" of the security device )

**Action:** select the switch of your real Siren device and set it to ON

2nd rule finished

Hope it's more clear now 🤔 🤞

**Comment by MiguelRipoll23** [comment]
@RLP1369 I can't reproduce your issue, can you paste the log here when the plugin starts? It should print`Trigger delay (10 second/s)`, if you are sending a HTTP request to trigger it remember to use the `&delay=true` parameter.

**Comment by MiguelRipoll23** [comment]
Go to the security system’s accessory settings on the Home app and tap on the show as separate tiles option to solve the icon issue.

@Karrypto thanks for your help!
