### ISSUE TITLE
Not finding the previous Alarm Status after Homebridge restart

### ISSUE THREAD

**Issue by chaot4ever** [MiguelRipoll23/homebridge-securitysystem#78]
After a restart of Homebridge the Securitysystem Status always goes to the Default Mode from the Settings.
I always have to set the previous Mode back manually.
Is it possible for the Securitysystem to find an set the previous Mode after Homebridge restart?

**Comment by MiguelRipoll23** [comment]
Sure! Use the `Save Using System Storage` (UI) or `save_state` (JSON) option.

**Comment by chaot4ever** [comment]
Tested it: If you have 3 Accessorys installed and they have a different state while Homebridge is restarting the Securitysystem Status is after the Homebridge restart shows for all of them the same status.
Here is the specific config.jason printout:
` "accessories": [
        {
            "name": "AlarmstatuS",
            "default_mode": "Off",
            "arm_seconds": 0,
            "trigger_seconds": 0,
            "reset_minutes": 10,
            "audio": false,
            "audio_language": "de-DE",
            "save_state": true,
            "proxy_mode": false,
            "test_mode": false,
            "override_off": false,
            "reset_off_flow": false,
            "disabled_modes": [
                "Home",
                "Night"
            ],
            "siren_sensor": false,
            "siren_sensor_seconds": 5,
            "reset_sensor": false,
            "mode_switches": false,
            "mode_off_switch": false,
            "mode_pause_switch": false,
            "pause_minutes": 0,
            "siren_switch": false,
            "siren_mode_switches": false,
            "audio_volume": "100",
            "audio_alert_looped": false,
            "accessory": "security-system"
        },
        {
            "name": "AlarmStatus",
            "default_mode": "Off",
            "arm_seconds": 0,
            "trigger_seconds": 0,
            "reset_minutes": 10,
            "audio": false,
            "audio_language": "de-DE",
            "save_state": true,
            "proxy_mode": false,
            "test_mode": false,
            "override_off": false,
            "reset_off_flow": false,
            "disabled_modes": [
                "Night"
            ],
            "siren_sensor": false,
            "siren_sensor_seconds": 5,
            "reset_sensor": false,
            "mode_switches": false,
            "mode_off_switch": true,
            "mode_pause_switch": false,
            "pause_minutes": 0,
            "siren_switch": false,
            "siren_mode_switches": false,
            "audio_volume": "100",
            "audio_alert_looped": false,
            "accessory": "security-system"
        },
        {
            "name": "Alarmstatus",
            "default_mode": "Off",
            "arm_seconds": 0,
            "trigger_seconds": 0,
            "reset_minutes": 10,
            "audio": false,
            "audio_language": "de-DE",
            "save_state": true,
            "proxy_mode": false,
            "test_mode": false,
            "override_off": false,
            "reset_off_flow": false,
            "disabled_modes": [
                "Home",
                "Night"
            ],
            "siren_sensor": false,
            "siren_sensor_seconds": 5,
            "reset_sensor": false,
            "mode_switches": false,
            "mode_off_switch": true,
            "mode_pause_switch": false,
            "pause_minutes": 0,
            "siren_switch": false,
            "siren_mode_switches": false,
            "audio_volume": "100",
            "audio_alert_looped": false,
            "accessory": "security-system"
        }`

**Comment by MiguelRipoll23** [comment]
Oh.. I see.

When I developed this plugin I didn’t even consider that someone would have more than one security system so I never tested it with more than one.

I’ll look into this as soon as I can, the weeks ahead I would be quite busy unfortunately but I’d have some free time at the end,

Thank you for reporting this issue.

**Comment by MiguelRipoll23** [comment]
Unfortunately this is not possible at the moment as it requires Homebridge to proporcionate an identifier per accessory from the same plugin to allow multiple storage sessions to work.

I'm gonna add this to the backlog to implement it once it's supported, thank you.
