### ISSUE TITLE
Interval polling of current status vía webhook

### ISSUE THREAD

**Issue by homebri121** [MiguelRipoll23/homebridge-securitysystem#80]
Could it be possible to poll current alarm's status vía a webhook every X seconds and override HomeKit's value?

**Comment by MiguelRipoll23** [comment]
You mean polling to other security system or the one that this plugin exposes?

**Comment by homebri121** [comment]
Make a call to an URL and obtain current status of the alarm (the one exposed by the plugin)

So, for example, if you connect the alarm using any other method, it can be updated on Home app

**Comment by MiguelRipoll23** [comment]
If you enable the server option, there’s an endpoint `/status` to get the current and target modes, also endpoints to arm, disarm or trigger the security system as well.

You can find documentation about them on the repository‘s README.

Is this what you’re looking for, right?

**Comment by homebri121** [comment]
yes, i thought it was only to retrieve info from homekit, not to set any status

Last question, any way to remove the big switch that appears on homekit on the side of the options of the alarm? (arm, away, home etc.)

**Comment by homebri121** [comment]
Yes, thanks O:)

**Comment by homebri121** [comment]
solved!
