### ISSUE TITLE
Second system causes webhooks to fail

### ISSUE THREAD

**Issue by cdc31** [MiguelRipoll23/homebridge-securitysystem#81]
I’ve got one security system set up with webhooks  for „Current Mode“. Works well.

I added a second security system for the cellar. 

Now the webhooks don’t work anymore. The log shows they were sent but they don’t arrive. I’ve added webhooks to the second system, but that also doesn’t work.

Deleting the second system immediately makes the webhooks work again!

Thanks!

Clemens

**Comment by MiguelRipoll23** [comment]
Hello!

I've created two security systems with different webhook endpoints (`/target/home1` for the first one, `/target/home1` for the second one), only the second endpoint gets called on both security systems... looks like an issue with Homebridge loading the configuration.

Also, even though it has been supported from the very beginning the ability to create multiple security systems is heavily discouraged and may be removed in a future update. It doesn't play nice with the storage, server and audio features and that could be a risky issue that affects the plugin's behavior. The alternative is to use conditions for the available security system's modes.

Sorry for the delay!

**Comment by cdc31** [comment]
Thanks for the feedback, I’ve now created a second homebridge instance to make it work as intended.
