### ISSUE TITLE
Audio not playing?

### ISSUE THREAD

**Issue by tobias-vdp** [MiguelRipoll23/homebridge-securitysystem#84]
Installed ffmpeg on a PI - but unfortuately the standard sounds are not playing - config below - any idea how to solve this? currently using a separate plugin (Sonos Alarm) to send audio to connected airplay 2 speakers - but would prefer to directly output audio

"accessories": [
        {
            "name": "Defcon 2",
            "default_mode": "Off",
            "arm_seconds": 0,
            "trigger_seconds": 0,
            "reset_minutes": 10,
            "audio": true,
            "audio_language": "de-DE",
            "save_state": true,
            "proxy_mode": false,
            "test_mode": false,
            "override_off": false,
            "reset_off_flow": false,
            "siren_sensor": true,
            "siren_sensor_seconds": 5,
            "reset_sensor": true,
            "mode_switches": false,
            "mode_off_switch": false,
            "mode_pause_switch": false,
            "pause_minutes": 0,
            "siren_switch": false,
            "siren_mode_switches": false,
            "audio_volume": "100",
            "audio_arming_looped": true,
            "audio_alert_looped": true,
            "accessory": "security-system"
        },

**Comment by MiguelRipoll23** [comment]
Hello!

Can you run Homebridge using debug mode using the following command, change modes and paste the log here?

`homebridge -D`

You may need to select the correct speaker that is connected to your device by executing the following commands by changing the number in bold, try 0, 1, 2...):

`export SDL_AUDIODRIVER=“alsa”
export AUDIODEV=“hw:**0**,0”`

**Comment by tobias-vdp** [comment]
[9.1.2021, 17:17:09] [Defcon 2] Target mode (Night)
[9.1.2021, 17:17:09] [Defcon 2] Current mode (Night)
[9.1.2021, 17:17:14] [Defcon 2] Target mode (Away)
[9.1.2021, 17:17:14] [Defcon 2] Current mode (Away)
[9.1.2021, 17:17:18] [Defcon 2] Target mode (Night)
[9.1.2021, 17:17:18] [Defcon 2] Current mode (Night)
[9.1.2021, 17:17:19] [Defcon 2] Target mode (Home)
[9.1.2021, 17:17:19] [Defcon 2] Current mode (Home)
[9.1.2021, 17:17:20] [Defcon 2] Target mode (Off)
[9.1.2021, 17:17:20] [Defcon 2] Current mode (Off)

**Comment by tobias-vdp** [comment]
hoobs@homebridge:/var/lib/homebridge $ export SDL_AUDIODRIVER=“alsa”
hoobs@homebridge:/var/lib/homebridge $ export AUDIODEV=“hw:0,0”
hoobs@homebridge:/var/lib/homebridge $ export AUDIODEV=“hw:1,0”
hoobs@homebridge:/var/lib/homebridge $ export AUDIODEV=“hw:2,0”
hoobs@homebridge:/var/lib/homebridge $ export AUDIODEV=“hw:3,0”
hoobs@homebridge:/var/lib/homebridge $ export AUDIODEV=“hw:4,0”
hoobs@homebridge:/var/lib/homebridge $ export AUDIODEV=“hw:5,0”
hoobs@homebridge:/var/lib/homebridge $ export AUDIODEV=“hw:6,0”
hoobs@homebridge:/var/lib/homebridge $

**Comment by tobias-vdp** [comment]
so basically i changed the audiodriver / audiodevice - the modes are being changed as well - but the audio is still not playing

**Comment by MiguelRipoll23** [comment]
Can execute the following commands and change modes again?

sudo hoobs service stop
hoobs -D

Paste the log again here, looks like debug mode wasn't activated correctly.

**Comment by tobias-vdp** [comment]
hmmm, actually i´m using config-ui-x together with a systemd startscript - unfortunately i don´t seem to be able to set it into debug mode.... will keep trying

**Comment by tobias-vdp** [comment]
hope this works better?

Jan 09 17:52:46 homebridge homebridge[3124]: [9.1.2021, 17:52:46] [Defcon 2] Target mode (Home)
Jan 09 17:52:46 homebridge homebridge[3124]: 2021-01-09T16:52:46.203Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.194] Sending HTTP event '58.12' with data: {"characteristics":[{"aid":58,"iid":12,"value":0}]}
Jan 09 17:52:46 homebridge homebridge[3124]: 2021-01-09T16:52:46.205Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.181] Sending HTTP event '58.12' with data: {"characteristics":[{"aid":58,"iid":12,"value":0}]}
Jan 09 17:52:46 homebridge homebridge[3124]: 2021-01-09T16:52:46.206Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.64] Muting event '58.12' notification for this connection since it originated here.
Jan 09 17:52:46 homebridge homebridge[3124]: 2021-01-09T16:52:46.207Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.203] Sending HTTP event '58.12' with data: {"characteristics":[{"aid":58,"iid":12,"value":0}]}
Jan 09 17:52:46 homebridge homebridge[3124]: 2021-01-09T16:52:46.209Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.193] Sending HTTP event '58.12' with data: {"characteristics":[{"aid":58,"iid":12,"value":0}]}
Jan 09 17:52:46 homebridge homebridge[3124]: 2021-01-09T16:52:46.210Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.146] Sending HTTP event '58.12' with data: {"characteristics":[{"aid":58,"iid":12,"value":0}]}
Jan 09 17:52:46 homebridge homebridge[3124]: 2021-01-09T16:52:46.212Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.92] Sending HTTP event '58.12' with data: {"characteristics":[{"aid":58,"iid":12,"value":0}]}
Jan 09 17:52:46 homebridge homebridge[3124]: 2021-01-09T16:52:46.213Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.64] HTTP Response is finished
Jan 09 17:52:46 homebridge homebridge[3124]: 2021-01-09T16:52:46.215Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.194] Sending HTTP event '58.11' with data: {"characteristics":[{"aid":58,"iid":11,"value":0}]}
Jan 09 17:52:46 homebridge homebridge[3124]: 2021-01-09T16:52:46.218Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.181] Sending HTTP event '58.11' with data: {"characteristics":[{"aid":58,"iid":11,"value":0}]}
Jan 09 17:52:46 homebridge homebridge[3124]: 2021-01-09T16:52:46.219Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.64] Sending HTTP event '58.11' with data: {"characteristics":[{"aid":58,"iid":11,"value":0}]}
Jan 09 17:52:46 homebridge homebridge[3124]: 2021-01-09T16:52:46.222Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.203] Sending HTTP event '58.11' with data: {"characteristics":[{"aid":58,"iid":11,"value":0}]}
Jan 09 17:52:46 homebridge homebridge[3124]: 2021-01-09T16:52:46.223Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.193] Sending HTTP event '58.11' with data: {"characteristics":[{"aid":58,"iid":11,"value":0}]}
Jan 09 17:52:46 homebridge homebridge[3124]: 2021-01-09T16:52:46.225Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.146] Sending HTTP event '58.11' with data: {"characteristics":[{"aid":58,"iid":11,"value":0}]}
Jan 09 17:52:46 homebridge homebridge[3124]: 2021-01-09T16:52:46.227Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.92] Sending HTTP event '58.11' with data: {"characteristics":[{"aid":58,"iid":11,"value":0}]}
Jan 09 17:52:46 homebridge homebridge[3124]: [9.1.2021, 17:52:46] [Defcon 2] Current mode (Home)
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.184Z HueClient2 request(get, /lights, null)
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.661Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.64] HTTP request: /prepare
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.662Z HAP-NodeJS:HAPServer [0E:6C:50:4C:98:47] HAP Request: PUT /prepare
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.664Z HAP-NodeJS:HAPServer [0E:6C:50:4C:98:47] Received prepare write request with pid 18038752520978518000 and ttl 5000
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.667Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.64] HTTP Response is finished
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.681Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.64] HTTP request: /characteristics
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.684Z HAP-NodeJS:HAPServer [0E:6C:50:4C:98:47] HAP Request: PUT /characteristics
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.687Z HAP-NodeJS:Accessory [Homebridge 1A6D] Processing characteristic set: [{"aid":58,"iid":12,"value":1}]
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.687Z HAP-NodeJS:Accessory [Homebridge 1A6D] Timed write request got acknowledged for pid 18038752520978518000
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.688Z HAP-NodeJS:Accessory [Homebridge 1A6D] Setting Characteristic "Security System Target State" to value 1
Jan 09 17:52:48 homebridge homebridge[3124]: [9.1.2021, 17:52:48] [Defcon 2] Target mode (Away)
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.699Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.194] Sending HTTP event '58.12' with data: {"characteristics":[{"aid":58,"iid":12,"value":1}]}
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.703Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.181] Sending HTTP event '58.12' with data: {"characteristics":[{"aid":58,"iid":12,"value":1}]}
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.705Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.64] Muting event '58.12' notification for this connection since it originated here.
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.705Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.203] Sending HTTP event '58.12' with data: {"characteristics":[{"aid":58,"iid":12,"value":1}]}
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.707Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.193] Sending HTTP event '58.12' with data: {"characteristics":[{"aid":58,"iid":12,"value":1}]}
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.709Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.146] Sending HTTP event '58.12' with data: {"characteristics":[{"aid":58,"iid":12,"value":1}]}
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.710Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.92] Sending HTTP event '58.12' with data: {"characteristics":[{"aid":58,"iid":12,"value":1}]}
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.712Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.64] HTTP Response is finished
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.715Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.194] Sending HTTP event '58.11' with data: {"characteristics":[{"aid":58,"iid":11,"value":1}]}
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.716Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.181] Sending HTTP event '58.11' with data: {"characteristics":[{"aid":58,"iid":11,"value":1}]}
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.718Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.64] Sending HTTP event '58.11' with data: {"characteristics":[{"aid":58,"iid":11,"value":1}]}
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.720Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.203] Sending HTTP event '58.11' with data: {"characteristics":[{"aid":58,"iid":11,"value":1}]}
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.721Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.193] Sending HTTP event '58.11' with data: {"characteristics":[{"aid":58,"iid":11,"value":1}]}
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.723Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.146] Sending HTTP event '58.11' with data: {"characteristics":[{"aid":58,"iid":11,"value":1}]}
Jan 09 17:52:48 homebridge homebridge[3124]: 2021-01-09T16:52:48.725Z HAP-NodeJS:EventedHTTPServer [::ffff:10.10.10.92] Sending HTTP event '58.11' with data: {"characteristics":[{"aid":58,"iid":11,"value":1}]}
Jan 09 17:52:48 homebridge homebridge[3124]: [9.1.2021, 17:52:48] [Defcon 2] Current mode (Away)

**Comment by tobias-vdp** [comment]
Jan 09 17:58:03 homebridge homebridge[3124]: [9.1.2021, 17:58:03] [Defcon 2] Current mode (Away)
Jan 09 17:58:03 homebridge homebridge[3124]: 2021-01-09T16:58:03.231Z HueClient2 request(get, /lights, null)
Jan 09 17:58:03 homebridge homebridge[3124]: [9.1.2021, 17:58:03] [Defcon 2] Unable to save state.
Jan 09 17:58:03 homebridge homebridge[3124]: [9.1.2021, 17:58:03] [Defcon 2] [Error: ENOSPC: no space left on device, write] {
Jan 09 17:58:03 homebridge homebridge[3124]:   errno: -28,
Jan 09 17:58:03 homebridge homebridge[3124]:   code: 'ENOSPC',
Jan 09 17:58:03 homebridge homebridge[3124]:   syscall: 'write'
Jan 09 17:58:03 homebridge homebridge[3124]: }
Jan 09 17:58:04 homebridge homebridge[3124]: 2021-01-09T16:58:04.020Z ciao:Responder Sending response via unicast to {"address":"10.10.10.193","port":5353,"interface":"eth0"} (took 10 ms): [PTR] answers and [TXT,SRV,A,AAAA,NSEC,NSEC] additionals with size 322B (UPS: 1440)
Jan 09 17:58:04 homebridge homebridge[3124]: 2021-01-09T16:58:04.145Z ciao:Responder Sending response via unicast to {"address":"10.10.10.146","port":5353,"interface":"eth0"} (took 9 ms): [PTR] answers and [TXT,SRV,A,AAAA,NSEC,NSEC] additionals with size 322B (UPS: 1440)
Jan 09 17:58:06 homebridge homebridge[3124]: 2021-01-09T16:58:06.759Z follow-redirects options {
Jan 09 17:58:06 homebridge homebridge[3124]:   protocol: 'https:',
Jan 09 17:58:06 homebridge homebridge[3124]:   maxRedirects: 21,
Jan 09 17:58:06 homebridge homebridge[3124]:   maxBodyLength: 10485760,
Jan 09 17:58:06 homebridge homebridge[3124]:   path: '/api/v1/statusschedule.php?controller_id=112116&api_key=D912-6745-6745-4613',
Jan 09 17:58:06 homebridge homebridge[3124]:   method: 'GET',
Jan 09 17:58:06 homebridge homebridge[3124]:   headers: {
Jan 09 17:58:06 homebridge homebridge[3124]:     Accept: 'application/json, text/plain, */*',
Jan 09 17:58:06 homebridge homebridge[3124]:     'User-Agent': 'axios/0.19.2'
Jan 09 17:58:06 homebridge homebridge[3124]:   },
Jan 09 17:58:06 homebridge homebridge[3124]:   agent: undefined,
Jan 09 17:58:06 homebridge homebridge[3124]:   agents: { http: undefined, https: undefined },
Jan 09 17:58:06 homebridge homebridge[3124]:   auth: undefined,
Jan 09 17:58:06 homebridge homebridge[3124]:   hostname: 'app.hydrawise.com',
Jan 09 17:58:06 homebridge homebridge[3124]:   port: null,
Jan 09 17:58:06 homebridge homebridge[3124]:   nativeProtocols: {
Jan 09 17:58:06 homebridge homebridge[3124]:     'http:': {
Jan 09 17:58:06 homebridge homebridge[3124]:       _connectionListener: [Function: connectionListener],
Jan 09 17:58:06 homebridge homebridge[3124]:       METHODS: [Array],
Jan 09 17:58:06 homebridge homebridge[3124]:       STATUS_CODES: [Object],
Jan 09 17:58:06 homebridge homebridge[3124]:       Agent: [Function],
Jan 09 17:58:06 homebridge homebridge[3124]:       ClientRequest: [Function: ClientRequest],
Jan 09 17:58:06 homebridge homebridge[3124]:       IncomingMessage: [Function: IncomingMessage],
Jan 09 17:58:06 homebridge homebridge[3124]:       OutgoingMessage: [Function: OutgoingMessage],
Jan 09 17:58:06 homebridge homebridge[3124]:       Server: [Function: Server],
Jan 09 17:58:06 homebridge homebridge[3124]:       ServerResponse: [Function: ServerResponse],
Jan 09 17:58:06 homebridge homebridge[3124]:       createServer: [Function: createServer],
Jan 09 17:58:06 homebridge homebridge[3124]:       validateHeaderName: [Function: hidden],
Jan 09 17:58:06 homebridge homebridge[3124]:       validateHeaderValue: [Function: hidden],
Jan 09 17:58:06 homebridge homebridge[3124]:       get: [Function: get],
Jan 09 17:58:06 homebridge homebridge[3124]:       request: [Function: request],
Jan 09 17:58:06 homebridge homebridge[3124]:       maxHeaderSize: [Getter],
Jan 09 17:58:06 homebridge homebridge[3124]:       globalAgent: [Getter/Setter]
Jan 09 17:58:06 homebridge homebridge[3124]:     },
Jan 09 17:58:06 homebridge homebridge[3124]:     'https:': {
Jan 09 17:58:06 homebridge homebridge[3124]:       Agent: [Function: Agent],
Jan 09 17:58:06 homebridge homebridge[3124]:       globalAgent: [Agent],
Jan 09 17:58:06 homebridge homebridge[3124]:       Server: [Function: Server],
Jan 09 17:58:06 homebridge homebridge[3124]:       createServer: [Function: createServer],
Jan 09 17:58:06 homebridge homebridge[3124]:       get: [Function: get],
Jan 09 17:58:06 homebridge homebridge[3124]:       request: [Function: request]
Jan 09 17:58:06 homebridge homebridge[3124]:     }
Jan 09 17:58:06 homebridge homebridge[3124]:   }
Jan 09 17:58:06 homebridge homebridge[3124]: }
Jan 09 17:58:08 homebridge homebridge[3124]: 2021-01-09T16:58:08.184Z HueClient2 request(get, /lights, null)
Jan 09 17:58:08 homebridge homebridge[3124]: 2021-01-09T16:58:08.697Z ciao:Responder Sending response via unicast to {"address":"10.10.10.92","port":5353,"interface":"eth0"} (took 7 ms): [PTR] answers and [TXT,SRV,A,AAAA,NSEC,NSEC] additionals with size 322B (UPS: 1440)
Jan 09 17:58:13 homebridge homebridge[3124]: 2021-01-09T16:58:13.183Z HueClient2 request(get, /lights, null)
Jan 09 17:58:18 homebridge homebridge[3124]: 2021-01-09T16:58:18.184Z HueClient2 request(get, /lights, null)
Jan 09 17:58:22 homebridge homebridge[3124]: 2021-01-09T16:58:22.057Z ciao:Responder Sending response via unicast to {"address":"10.10.10.193","port":5353,"interface":"eth0"} (took 12 ms): [PTR] answers and [TXT,SRV,A,AAAA,NSEC,NSEC] additionals with size 322B (UPS: 1440)
Jan 09 17:58:23 homebridge homebridge[3124]: 2021-01-09T16:58:23.182Z HueClient2 request(get, /lights, null)

**Comment by MiguelRipoll23** [comment]
Looks like debug messages from the plugin are discarded, I’ll gonna provide additional details using Homebridge Config X soon.

**Comment by MiguelRipoll23** [comment]
> Can execute the following commands and change modes again?
> 
> sudo hoobs service stop
> hoobs -D
> 
> Paste the log again here, looks like debug mode wasn't activated correctly.

Did this worked? You should be seeing something like this:

![image](https://user-images.githubusercontent.com/3296866/104128877-45588500-536a-11eb-8ab8-72b0dd86fec4.png)

**Comment by tobias-vdp** [comment]
took me quite some time to figure this out:

when using hb-service / config-ui-x the d parameter needs to be added to the /etc/default/homebridge file:
![6F1A8DFE-1924-489B-8A7F-A612DC25A50A](https://user-images.githubusercontent.com/61106646/104131762-c3238d00-5378-11eb-86ee-84e1fc9fb79a.jpeg)
 
the output then looks like this
![18CD4A3D-E5EE-449D-BC3F-E3BCFD6542ED](https://user-images.githubusercontent.com/61106646/104131734-95d6df00-5378-11eb-8333-21fc3f6beee1.jpeg)

**Comment by tobias-vdp** [comment]
update: when manually launching ffplay, it seems to work - but without any output to the speakers

![1ED9DC86-DFFD-4429-93B1-A3774258F4BE](https://user-images.githubusercontent.com/61106646/104131877-af2c5b00-5379-11eb-8c8d-63799012928d.jpeg)

**Comment by MiguelRipoll23** [comment]
Just to confirm, is there a non-AirPlay speaker connect to your Homebridge device using the headphone jack or USB?

If you want to play these sounds on your AirPlay speaker that requires importing those sounds to your iTunes library and playing them using a Home automation.

**Comment by tobias-vdp** [comment]
ah - ok - now i understand ;) i have several sonos airplay 2 speakers  - and the idea was to use them as audio output device - the regular automation seems to require some apple music subscription that i do not have - will give the sonos alarm extension a try, perhaps i can use this together with your great plugin ;)
