### ISSUE TITLE
Alarm is never triggered

### ISSUE THREAD

**Issue by bosco90** [MiguelRipoll23/homebridge-securitysystem#85]
Hello,
The alarm never triggers when a sensor detects a change, like a door opens.

I've tried to set the alarm in Away mode and then open a door, but nothing happened, not even a notification on iPhone.

Should the plugin work with every HomeKit accessory or I'm missing something?

The Plugin configuration is the following:
        {
            "name": "Allarme",
            "default_mode": "Off",
            "arm_seconds": 0,
            "trigger_seconds": 15,
            "reset_minutes": 10,
            "audio": false,
            "audio_language": "en-US",
            "save_state": false,
            "proxy_mode": false,
            "test_mode": false,
            "override_off": false,
            "reset_off_flow": true,
            "siren_sensor": false,
            "siren_sensor_seconds": 5,
            "reset_sensor": false,
            "mode_switches": false,
            "mode_off_switch": true,
            "mode_pause_switch": false,
            "pause_minutes": 0,
            "siren_switch": true,
            "siren_mode_switches": false,
            "audio_volume": "100",
            "audio_arming_looped": false,
            "audio_alert_looped": false,
            "accessory": "security-system"
        }

At the moment I've made some automations that "triggers" the alarm but it's not the best experience.

Thanks for your time and your work!
Cheers.

**Comment by MiguelRipoll23** [comment]
Hello!

Does a simple automation with no conditions works? Something like "when door opens, turn on siren switch".
Does `Sensor (Triggered)` gets written in the Homebridge log file?

I've seen something like this happening with the plugin when a door sensor is involved, probably related to the iOS version the Home Hub is running. Can you also please confirm if your Home Hub is on the latest version?

Thank you.

**Comment by bosco90** [comment]
Thanks for the answer!
I got it completely wrong, the center of the alarm is the siren!! Now I've changed my automations so that the siren Is enabled and everything is working fine, from the delay to the triggering (btw: "Sensor (Triggers)" gets written in the Homebridge logs when the siren is enabled).

Thank you so much for solving this, and sorry if I've misunderstood the mechanic of the plugin.

**Comment by MiguelRipoll23** [comment]
No worries, although there’s a way to trigger the security system without the switch it requires powerful apps like Eve to do so. The switch is great enough for Home app users.
