### ISSUE TITLE
this.sendModeOffError is not defined

### ISSUE THREAD

**Issue by mczac** [MiguelRipoll23/homebridge-securitysystem#86]
at /usr/local/lib/node_modules/homebridge-securitysystem/src/index.js:971:14

function this.sendModeOffError isn't defined in the source code

**Comment by MiguelRipoll23** [comment]
New beta update published with the bug encountered fixed, you can now try these changes executing the following command on your terminal:

`npm install -g homebridge-securitysystem@beta`

**IMPORTANT:** If you're a HOOBS user, please wait until the beta phrase has ended. 

Remember that you can leave the beta program anytime using the command below:

`npm install -g homebridge-securitysystem@latest`

Thanks!

**Comment by MiguelRipoll23** [comment]
Thank you for reporting this issue, fix hit the release channel and it's available now.
