### ISSUE TITLE
Double Knock

### ISSUE THREAD

**Issue by ashpole** [MiguelRipoll23/homebridge-securitysystem#87]
Hi,

On other security systems I’ve used what I think is called Double Knock to cut down on false alarms: When a sensor triggers an alarm, the system waits a predefined number of seconds to see if it gets another sensor trigger (including the original one again) before considering it a definite alarm condition and sounding the bell/siren. If there’s no second trigger then the system reverts to waiting for another first trigger.

I don’t think your (excellent, by the way) Security System has this facility unless it’s hidden in the “siren_sensor” functionality?

Cheers,

Mike

**Comment by MiguelRipoll23** [comment]
Hey there,

That’s an helpful feature indeed, I’d like to ask you some question in order to implement it the best way.

Most HomeKit sensors allow you to set the amount of time that should pass for them to trigger again, in your case what’s the minimum time that is set?

How much time should pass to revert back to two triggers? Should it be editable by the user or it’s pretty much standard?

I did my little research on commercial security systems but I missed this kind of features that fit well under HomeKit limitations so I really appreciate these kind of suggestions coming up.

**Comment by ashpole** [comment]
Hi,

Thank you for getting back to me, I really appreciate it.

Let me answer your second point first. This should be somewhere between a sensor’s cool down period (the minimum time before it can trigger again, as you say normally set by the manufacturer or a sensor’s design) and the maximum time you want to look for a real intruder to activate the same or a different sensor - the higher this figure, the more likely a faulty sensor will still trigger a false alarm. 

In my experience, I’ve seen maximum times to look for a second sensor trigger between 1 and 5 minutes - it’s unlikely an intruder would not trigger a sensor twice within 1 to 2 minutes, so 1 to 5 minutes would be a good window for the user to be able to select, perhaps defaulting to 90 seconds. That said, the longer times are usually on systems where the first sensor CANNOT be used to confirm a second trigger; and shorter windows used on systems where the first sensor CAN be used for confirmation.

With regard to your first question, I don’t think you need worry about that - unless I’ve missed something.

Within your system I would envisage:

1. Function as present;
2. Checkbox enables Double Knock, defaults to 90 second window for ANY second trigger;
3. Advance setting (or in Config file) to allow Double Knock window to be set between 60 and 300 seconds.

Old type intruder alarms used to have this facility but it became redundant on most systems with passive infra sensors because those manufacturers started to build it into the sensor. Therefore, when a sensor activated it was far more likely to be a true activation and not a bug or spider! 

Does that all make sense? Please say if I’ve not explained something.

Mike

**Comment by ashpole** [comment]
I should have mentioned that I implemented a crude workaround!

I set up a dummy switch in Homebridge that turns off after 60 seconds of being turned on. When a sensor activates, a check is done on the dummy switch, if it’s off it is turned on; if it’s on then your security system is triggered!

Mike

**Comment by MiguelRipoll23** [comment]
Thank you so much for the information.

There's an upcoming update that will introduce some minor under the hood improvements from a major TypeScript rewrite of the plugin that I'm working on in parallel, it will be available someday next week on the release channel.

I'll try to add this on the beta channel next weekend 🙂

**Comment by ashpole** [comment]
No problem, happy to be of help. I’m retired now so don’t get much chance to stretch my brain!

Looking forward to the beta.

**Comment by MiguelRipoll23** [comment]
I just added this feature to a new beta update that you can install using the following command:

`npm install -g homebridge-securitysystem@beta`

The option is available under the `Advanced Options > Sensors` section but in the near future there will be a new section which would consist of basic features. Be free to submit any feedback during the beta phrase to improve the implementation if it doesn't fit your needs yet.

Thanks!

**Comment by ashpole** [comment]
That was quick, thank you.

I'm having a problem moving to the beta.  I'm going into Homebridge, selecting Terminal, running npm install -g homebridge-securitysystem@beta and then restarting Homebridge.

When it restarts it's still at v3.7.0 latest.

What am I doing wrong?!?

Cheers,

Mike

**Comment by MiguelRipoll23** [comment]
Are you using Homebridge or HOOBS?

**Comment by ashpole** [comment]
Homebridge.

**Comment by MiguelRipoll23** [comment]
Can you try again like this?

`npm install -g --unsafe-perm homebridge-securitysystem@beta`

**Comment by ashpole** [comment]
That didn’t fix it directly, but I have fixed it now by uninstalling the latest version and then loading the beta!

Thanks for your help.

Mike

**Comment by ashpole** [comment]
Suggested change to description:

Requires the same sensor or other ones to be triggered twice within a time window.

"Requires any two sensors to be triggered within the time window to activate the siren."

Not sure about the last word (siren), needs to be the same as you use elsewhere for single sensor trigger.

Mike

**Comment by MiguelRipoll23** [comment]
Unfortunately HomeKit doesn't allow you to know which sensor triggered your accessory due to security, that's why I worded it like that.

It means that the same sensor could still trigger it again as we can't know the source.

**Comment by ashpole** [comment]
I've read my words again and don't like them! Your's are more accurate - I'll go back to sleep now ;)

**Comment by ashpole** [comment]
Testing so far:

When setting system to Away, single sensor activations are ignored if left to time out ie no double knock. 

Double sensor activations within time window result in alarm being triggered correctly. But, I let the system revert to set mode, ie Away, it seems to require just a single sensor activation to trigger the alarm. 

Also, the Siren switch seems “very sticky” and reluctant to turn off. When the system reverted to Away the Siren switch did not move to off; and even turning OFF the Security System left the Siren switch turned on.

**Comment by MiguelRipoll23** [comment]
What do you mean by revert? Trying to set a mode and cancellation the mode change before it gets armed?

I will try to reproduce, thanks for the testing.

**Comment by ashpole** [comment]
Here’s some logs, I set Away, trigger the system with a double knock, it stays in Alarm until it resets, then I activate one sensor and the alarm goes off.

[2/20/2021, 11:48:47 AM] [Security system] Target mode (Away)
[2/20/2021, 11:48:47 AM] [Security system] Sensor (Not armed)
[2/20/2021, 11:48:52 AM] [Security system] Current mode (Away)
[2/20/2021, 11:49:16 AM] [Security system] Sensor (Knock)
[2/20/2021, 11:49:18 AM] [Security system] Sensor (Triggered)
[2/20/2021, 11:49:28 AM] [Security system] Current mode (Triggered)
[2/20/2021, 11:50:05 AM] [Security system] Sensor (Cancelled)
[2/20/2021, 11:50:05 AM] [Security system] Target mode (Off)
[2/20/2021, 11:50:05 AM] [Security system] Sensor (Knock)
[2/20/2021, 11:50:05 AM] [Security system] Current mode (Off)
[2/20/2021, 11:50:12 AM] [Security system] Target mode (Away)
[2/20/2021, 11:50:17 AM] [Security system] Current mode (Away)
[2/20/2021, 11:50:47 AM] [Security system] Sensor (Knock)
[2/20/2021, 11:50:58 AM] [Security system] Sensor (Triggered)
[2/20/2021, 11:51:08 AM] [Security system] Current mode (Triggered)
[2/20/2021, 11:52:08 AM] [Security system] Sensor (Knock)
[2/20/2021, 11:52:08 AM] [Security system] Current mode (Away)
[2/20/2021, 11:52:27 AM] [Security system] Sensor (Triggered)
[2/20/2021, 11:52:37 AM] [Security system] Current mode (Triggered)
[2/20/2021, 11:53:37 AM] [Security system] Sensor (Knock)
[2/20/2021, 11:53:37 AM] [Security system] Current mode (Away)
[2/20/2021, 11:53:57 AM] [Security system] Sensor (Reset)
[2/20/2021, 11:53:57 AM] [Security system] Target mode (Off)
[2/20/2021, 11:53:57 AM] [Security system] Sensor (Knock)
[2/20/2021, 11:53:57 AM] [Security system] Current mode (Off)
[2/20/2021, 11:54:17 AM] [Security system] Sensor (Reset)

**Comment by ashpole** [comment]
> What do you mean by revert? Trying to set a mode and cancelling the mode change before it gets armed?
> 
> I will try to reproduce, thanks for the testing.

Revert —> After “Reset Delay Minutes”

**Comment by MiguelRipoll23** [comment]
Thank so much for the logs, can you try again with the latest beta?

**Comment by ashpole** [comment]
Will do, might have to be in the morning (UK). 



📤 Sent from my iPad Pro

**Comment by MiguelRipoll23** [comment]
I've moved some sections outside the advanced options section and added descriptions to clarify what they do, trying to improve the learning curve for new users 😛

**Comment by ashpole** [comment]
That’s always a good idea, and for old farts like me 😂 I’ve been busy so far today, I’ve got beta3 installed but not tested. 

📤 Sent from my iPad Pro

**Comment by beatpaul** [comment]
Hi!
Thanks for the great Plugin - especially the new double knock feature seams to be great.
I have one more idea für for this feature:
would it be possible to set it up separately for AWAY und NIGHT mode?
The reason is, that e.g. for my 
-> night mode the Door Sensor is the only sensors (that will probably not be triggered twice by a thief :)  -> no double knock for me)
-> away mode there are more Sensors (Motion, Door, etc. -> so double knock is great)

Paul

**Comment by ashpole** [comment]
Double knock is used to help minimise false alarms. In the case of a home system, it might be considered acceptable to not have DK enabled during the Night as you’re there to react. So perhaps, at a system level, DK should be enabled in Away mode only. 

I have internal door sensors and some motion sensors active at night so DK at Night works for me but I could live without it. 



📤 Sent from my iPad Pro

**Comment by MiguelRipoll23** [comment]
You're right, I will deliver another beta update soon to only use double-knock if the Away mode is selected.

**Comment by MiguelRipoll23** [comment]
Just published the new beta update, enjoy!

**Comment by ashpole** [comment]
Great, I will!

Thank you for all your hard work. 



📤 Sent from my iPad Pro

**Comment by MiguelRipoll23** [comment]
It's now out of beta and live on the release channel, looks good.

**Comment by ashpole** [comment]
It does look good, I haven’t found any bugs in DK. 

Again, thank you for your hard work and you’re fast too!




📤 Sent from my iPad Pro
