### ISSUE TITLE
Away + Pet Mode Option

### ISSUE THREAD

**Issue by cscott365** [MiguelRipoll23/homebridge-securitysystem#88]
Would love an "Away Mode with Pet" which I could change the sensors I use to fire the alarm in the automation settings. Some of the internal motion sensors fire on pet motion and some do not. So having multiple "Away" mode options would be amazing to be better protected when we take the pet with us somewhere. Currently use a dummy switch for it, but sometimes I forget to flip it.

**Comment by MiguelRipoll23** [comment]
Hey there,

Do you mean by using a switch or being part of the mode selector screen that the Home app displays? The modes that are displayed are limited by iOS but if you mean a switch I can see it being helpful as you don’t have to deal with the both the security system and the switch.

**Comment by cscott365** [comment]
The more I think about this, I see it as a switch. The switch would allow for automation to choose different motion sensors based upon I have a pet in the house or not. Some of my motion sensors trip by pet movement, while others will not. So when we take the pets with us, I can make the system more sensitive by turning the Pet in House switch off. I can always do this via a dummy switch in Homebridge, but it might be a nice switch to have integrated into the Security System.

**Comment by MiguelRipoll23** [comment]
I thinking how I can make the your current setup easier, the thing is a pet switch will still require to set the security system to a mode **and** activating the pet switch.

One pet switch for every arming mode is overkill I think, is there a simpler way that could help you? I'm trying to don't create way too many switches but sometimes there's no other way.

**Comment by cscott365** [comment]
Pet mode would ONLY apply to Away Mode. All other modes, the person is likely home, so the pet setting would not apply in that case. IMHO

**Comment by cscott365** [comment]
I might just look to do it as a Dummy Switch and then I can tweak sensors via node-red automation.

**Comment by MiguelRipoll23** [comment]
That's right, my bad.

If you still consider this a feature that must be implemented keep the issue open until next weekend for me to add it.

Thanks!

**Comment by cscott365** [comment]
Only a nice to have feature. I will keep it open, but low priority. Also going to fork your code and take a look at any thoughts I have on other things that might help.

**Comment by cscott365** [comment]
Been thinking more on this, and to be more in line with a "common" feature, a "Vacation" Switch would work for this. In essence when "Vacation" is on, I can use that for more sensitive settings to trigger the siren and it would be more along the lines of something the greater population would like to see. Because the only time that I would be taking the pets out of the house would be during vacation. ;-)

**Comment by MiguelRipoll23** [comment]
I really like the idea, it could be some kind of `Super Away` mode  for enhanced protection 😃

How would you create the automations, like this?

Pet-friendly sensor is triggered -> if `Mode Super Away` is `On` turn on `Siren Away`
Pet-unfriendly sensor is triggered -> if `Mode Away` is `On` and `Mode Super Away` is `Off` turn on `Siren Away`.

The only disadvantage of this implementation is that you require a more advanced HomeKit app to be able to add these conditions but it's not a big issue.

**Comment by MiguelRipoll23** [comment]
Oh, I'm refactoring the code from the plugin a little bit.

There's a TypeScript migration that I'd like to see happening but it requires a lot of time and effort, I already started with the basics but I'm waiting for Homebridge to keep improving their APIs (they added promises recently) to continue. Once it's done, the code would be easier to understand,

**Comment by cscott365** [comment]
Yes, doing more of my  work in node-red for the advanced automation side of this. For now I have a vacation switch that when turned on brings more sensors into the fold for turning on the siren. So vacation switch Off, use standard sensors and rules. Vacation switch On use more sensors and be more sensitive to firing and alerting. Different motion sensors and glass break sensors. Window open sensors perhaps, but I can choose those with the switch. Right now I just use a dummy switch from another plugin.

**Comment by MiguelRipoll23** [comment]
I just published a new update in the beta channel that introduces this switch, I accept suggestions for the name as I'm not good naming things 😅

**Comment by cscott365** [comment]
I think "Extended Away" would be a good technical name for this.

**Comment by MiguelRipoll23** [comment]
That will do, thanks! Will rename it soon.

Meanwhile you can switch to the beta channel executing the following:
`npm i -g --unsafe-perm homebridge-securitysystem@beta`

**Comment by MiguelRipoll23** [comment]
It's now in the release channel, enjoy.
