### ISSUE TITLE
Security System Status Should Persist Across Homebridge Restart

### ISSUE THREAD

**Issue by cscott365** [MiguelRipoll23/homebridge-securitysystem#89]
When system is armed, the status should persist across a Homebridge restart. Currently it appears that the system will revert back to off if the Homebridge service is restarted in anyway.

**Comment by MiguelRipoll23** [comment]
Hey there,

You can use the "Save Using System Storage" or "save_state" (JSON) option to persist the current state after a Homebridge restart.

**Comment by cscott365** [comment]
Perfect! I was a little confused by the wording of "Save Using System Storage". Perhaps titling that differently would be great, but really appreciate the quick response and features of this tool. Working on implementing in my node-red setup and will see if we can get all the way there. Great work!

**Comment by MiguelRipoll23** [comment]
Noted, thank you for the feedback.
