### ISSUE TITLE
Option to change name of "Siren" switch

### ISSUE THREAD

**Issue by gerritfries** [MiguelRipoll23/homebridge-securitysystem#9]
First of all I'd like to thank you for this great plugin.
I was wondering if you could add the option to change the name of the "Siren" switch. I know it's a minor issue, but I really would like to give it a different name.

¡Muchas gracias!

Edit: So sorry about this. I woke up early today and forgot that I could change the name in the Home App. Please close this issue.

**Comment by MiguelRipoll23** [comment]
No problem! Thanks for the words :)
