### ISSUE TITLE
Switches Do Not Report On/Off Like Other Switches in Homebridge

### ISSUE THREAD

**Issue by cscott365** [MiguelRipoll23/homebridge-securitysystem#90]
**Describe the bug**
When the Mode Buttons change, I do not see an event like an On/Off that fires like a light switch or even a Dummy Switch. It makes it hard to automate in a tool like node-red where I am looking for a homebridge event.

**To Reproduce**
1. Install node-red
2. Install https://flows.nodered.org/node/node-red-contrib-homebridge-automation
3. Configure the automation plugin
4. Check for events from the Security System
5. Compare to events from other plugins

**Expected behavior**
When the Mode changes, the accessories should fire events that are visible in node-red like the other accessories in homebridge.

**Additional context**
I notice that the Security System is listed as an "accessories" area of homebridge, where ALL of my other plugins are "platforms". Not sure why that is, but perhaps that is part of the issue.

**Comment by MiguelRipoll23** [comment]
I'm not completely sure what's happening here, I'd report the issue to the `node-red-contrib-homebridge-automation` author. The plugin being listed as an accessory is actually fine and it should find the devices correctly using the Homebridge API.

**Comment by cscott365** [comment]
Hmmm....it finds the accessories just fine. It is the events that do not fire. This is the only plugin not firing in my node-red setup. It is also the only plugin that is an accessory vs a platform in the Homebridge configuration. So I can find the accessory, but when the accessory switches to On or Off, there is no event that fires across the platform. Going to dig further and run some debug later when I have time. Will see if I can find a section of code from other plugins vs this one that might be different in how they fire. 

Thanks for the response as always!

**Comment by MiguelRipoll23** [comment]
Sorry for the brief response, was a little bit exhausted. 

Do you see the same issue with the Homebridge UI? You must run the insecure mode (using the -I argument) and go to the `Accessories` tab. 

If you see the switches firing there, it may be an issue with the other plugin.

![image](https://user-images.githubusercontent.com/3296866/108749327-f93f5980-753f-11eb-901c-8134682dd918.png)

**Comment by cscott365** [comment]
All good, and not worried about brief responses. Everything fires in the UI just fine. The Security System are the only things not firing in node-red. I wonder if it could also be an issue of me running them in a child bridge. All of my plugins (currently 9) run as child bridges for performance and stability. But perhaps the accessory tag does not work as a child bridge. Will move it back to the main bridge and see if that causes them to fire across. Time for some research and debugging. :-)

**Comment by cscott365** [comment]
Hmmm...going to close this as it appears to be node-red plugin related and not here. Sorry for the extra cycles.
