### ISSUE TITLE
Alarm Sensor vs Motion Sensor

### ISSUE THREAD

**Issue by cscott365** [MiguelRipoll23/homebridge-securitysystem#93]
Not sure of the feasibility, but I think the "Siren Triggered" and "Reset Event" would be better as "Alarm Sensors" vs "Motion Sensors". It is more to what they are, and they would be more appropriately marked in the Homekit UI.

**Comment by MiguelRipoll23** [comment]
The name of the accessory type is controlled by HomeKit, unfortunately. Hoping to see some improvements in the future.
