### ISSUE TITLE
Silent alarm

### ISSUE THREAD

**Issue by beatpaul** [MiguelRipoll23/homebridge-securitysystem#94]
Hi!
Sometimes it would be really usefull to get a silent alarm (e.g. on your mobile) first before the real (loud) alarm starts.
That could be another switch that turns on after certain time the primary alarmswitch is triggered.
In my situation e.g if  a friend enters the apartment i could get a notification first an have some time to switch of the security system before the alarm noise turns on.

what do u think?

greets 
Paul

**Comment by ashpole** [comment]
I like that.

+1


📤 Sent from my iPad Pro

**Comment by MiguelRipoll23** [comment]
Hey there,

You can create an automation based on when a siren switch is turned on to play a warning sound to an AirPlay speaker or use one of the sounds provided by the plugin that plays locally.

Notifications can only be sent by sensors, unfortunately. Will this work for the use case? Once the warning sound is heard, the user (which should have access to the security system accessory as well) must disarm it.

**Comment by beatpaul** [comment]
@MiguelRipoll23 
Hi!
Thx for your replay, but i think we‘re not talking about the same :)
It just would be really comfortable to have a dedicated warning switch that u can use for a „notification process“ of your choice before the alarm turns on 

(like the warning option in webhooks)

greez paul

**Comment by MiguelRipoll23** [comment]
Would it be used to trigger an accessory or send notifications? Only some kind of accessories like motion sensors can trigger a notification.

**Comment by MiguelRipoll23** [comment]
Sorry, it’s a little bit unclear if the use case is to receive notifications or exclusively to automate an accessory. If the use case is to receive notifications it has to be a sensor, otherwise the Home app won’t let you receive notifications of it.

**Comment by beatpaul** [comment]
sorry for being unclear, i try again:
from my side its not met to trigger any notification necessarily -> just a switch like the "siren switch" that first switches before the actual "siren switch" triggers

like the "warning option in webhooks" that sends a warning before the actual alarm turns on

**Comment by beatpaul** [comment]
1. Security System is on
2. alarm is triggered -> `first switch turns on`  -> i can the do an `automation for sending a telegram notification to myself e.g.`
3. **wait a specific time** -> so i can react to the telegram notification (check the webcam, maybe it just was the cat e.g)
4. `second switch turns on` --> alarm is triggered  (if i didn't reset the sec system during step 3)

but never mind everything works fine so far, thx for the great plugin and your support

**Comment by MiguelRipoll23** [comment]
Looks to me that all you just need is to increase the `Trigger Delay Seconds` a little bit, you can set for example 60 or 90 seconds which would be enough to react to the notification triggered by the warning webhook and then cancel it by turning off the `Siren switch` which will abort the trigger phrase.

Here's why: alternative flows for triggering the security system are dangerous, the test cases are increased and the plugin stability may suffer during important fixes that require shorter testing. However, if there's anything that can be done to improve this only flow don't hesitate to suggest it right here in this issue.

**Comment by beatpaul** [comment]
thanks for your tip -> got everything working with setting the `trigger delay seconds` to 90 
--> using the siren switch for making an automation that sends me a message
--> when security system after 90 sc.triggers --> ALARM :)

thx for your help!
