### ISSUE TITLE
Ignore trigger delay for 'Night' mode

### ISSUE THREAD

**Issue by CameronSmith93** [MiguelRipoll23/homebridge-securitysystem#95]
Hi there,

First of all, thanks for making this excellent plugin!

I was hoping to have the option to ignore the trigger delay time period for the 'Night' mode - given that this is the mode that will be activated when everyone is home and asleep, I'd want to know immediately if the alarm has been tripped as opposed to waiting the standard time period that would apply for the 'Away' mode for example.

Not sure if this is possible already, but would be a nice feature to have.

Thanks!

**Comment by MiguelRipoll23** [comment]
It's now available on the beta channel, just disable the `Arm Night Mode With Delay` option that you can find under the advanced options section.

`npm install -g homebridge-securitysystem@beta`

Thanks!

**Comment by MiguelRipoll23** [comment]
Feature it's now in the stable channel, enjoy!

**Comment by CameronSmith93** [comment]
Hi there,

Thanks so much for adding this - really appreciate it.

I haven't had a chance to test yet, but just wanted to confirm as I'm a bit confused with the wording of the feature addition:

Does this new feature ignore the **arm** delay _or_ does it ignore the **trigger** delay?
I was looking to ignore the trigger delay rather than the arm delay but the description reads otherwise.

In any case, I'm looking forward to testing over the next few days!

**Comment by MiguelRipoll23** [comment]
I misunderstood the feature request, my bad. I'll release another update ASAP.

My apologies 😅

**Comment by MiguelRipoll23** [comment]
Added option `Trigger During Night Mode With Delay` to enable/disable the trigger delay in the latest beta, thanks!

**Comment by MiguelRipoll23** [comment]
Feature it's now in the stable channel, enjoy!
