### ISSUE TITLE
Get alarm state changes in HomeKit

### ISSUE THREAD

**Issue by Arnwald** [MiguelRipoll23/homebridge-securitysystem#97]
Hi,

I would like to know if there is a way to change the alarm status in HomeKit when it is set from the device. I can set the status with Home, but when I set it from the device the status stays the same in Home.

Thank you.

**Comment by MiguelRipoll23** [comment]
Hey there,

Which device? This plugin is a virtual security system, which means that there's no compatibility layer for real security systems to act in their behalf.

**Comment by Arnwald** [comment]
I made a Python bridge to interact with my Ajax hub. The script is able to send Homebridge commands to the hub and to get the hub state, and I would like to pass this information to the Homebridge plugin.
I am not familiar with js, so I don’t know if this is feasible without too much work.

**Comment by MiguelRipoll23** [comment]
Oh, enable the server option in settings and [check this out](https://github.com/MiguelRipoll23/homebridge-securitysystem).

If you want to do it viceversa, use the webhooks feature.

**Comment by MiguelRipoll23** [comment]
Sorry, check the link again now it’s correct.

**Comment by Arnwald** [comment]
I couldn’t wait to try and it’s working :-)
Thank you again !

**Comment by MiguelRipoll23** [comment]
Great to hear that, have fun?
